docs/design/mobile/2.3/asset-library.md, docs/design/mobile/2.3/basic-interactions/application-structure.md, docs/design/mobile/2.3/basic-interactions/edit.md, docs/design/mobile/2.3/basic-interactions/navigation.md, docs/design/mobile/2.3/basic-interactions/notifications.md, docs/design/mobile/2.3/basic-interactions/settings.md, docs/design/mobile/2.3/basic-interactions/view-modes.md, docs/design/mobile/2.3/design-library/body-0.md, docs/design/mobile/2.3/design-library/button.md, docs/design/mobile/2.3/design-library/header-0.md, docs/design/mobile/2.3/design-library/picker.md, docs/design/mobile/2.3/design-library/pop-up.md, docs/design/mobile/2.3/design-library/progress-and-process.md, docs/design/mobile/2.3/design-library/scroll.md, docs/design/mobile/2.3/design-library/search-0.md, docs/design/mobile/2.3/design-library/slider.md, docs/design/mobile/2.3/design-library/text-field.md, docs/design/mobile/2.3/design-principles.md, docs/design/mobile/2.3/new-tizen-2.md, docs/design/mobile/2.3/ui-overview.md, docs/design/mobile/2.3/visual-style/colors.md, docs/design/mobile/2.3/visual-style/display.md, docs/design/mobile/2.3/visual-style/icons.md, docs/design/mobile/2.3/visual-style/touch-feedback.md, docs/design/mobile/2.3/visual-style/typography-0.md
Re-sizing images in the Design-mobile-2.3 directory.
=> Resize images in Design-mobile-2.3 directory

docs/design/mobile/design-patterns/app-handling.md, docs/design/mobile/design-patterns/app-structure.md, docs/design/mobile/design-patterns/navigation-design.md, docs/design/mobile/design-patterns/notifications.md, docs/design/mobile/design-patterns/screen-layout.md, docs/design/mobile/design-patterns/screen-orientations.md, docs/design/mobile/design-patterns/settings.md, docs/design/mobile/design-patterns/widgets.md, docs/design/mobile/design-principles.md, docs/design/mobile/styles.md, docs/design/mobile/ui-components/navigation-elements.md, docs/design/mobile/ux-overview/gestures.md, docs/design/mobile/ux-overview/hardware-keys.md, docs/design/mobile/ux-overview/home-structure.md
Part 1 was for the 2.3 directory.
Part 2 is for the rest of the directories in mobile.
=> Resize images in Design mobile docs Part 2

docs/design/tv/styles/color-swatch.md, docs/design/tv/ui-components/presentation-views/progress/activity-indicator.md, docs/design/tv/ui-components/presentation-views/progress/progress-indicator.md, docs/design/tv/ux-overview/controls.md
Some image links are updated with <img src...> tags for resizing or proper display.
Video links are updated.
=> Update Design-tv documents

docs/design/introduction/air.md, docs/design/introduction/styles/animations.md, docs/design/introduction/styles/colors.md, docs/design/introduction/styles/device-compatibility.md, docs/design/introduction/styles/iconography.md, docs/design/introduction/styles/typography.md
Image sizes are aligned.
Video links are updated.
=> Resize image files in design introduction documents

docs/design/mobile/2.3/basic-interactions/application-structure.md, docs/design/mobile/2.3/basic-interactions/edit.md, docs/design/mobile/2.3/basic-interactions/navigation.md, docs/design/mobile/2.3/basic-interactions/notifications.md, docs/design/mobile/2.3/design-library/picker.md, docs/design/mobile/2.3/design-library/scroll.md, docs/design/mobile/2.3/design-library/text-field.md, docs/design/mobile/2.3/design-principles.md, docs/design/tv/ui-components/presentation-views/progress/activity-indicator.md, docs/design/tv/ui-components/presentation-views/progress/progress-indicator.md
Video links are changed with \<video\> tags.
=> Change video links in Design-Mobile / TV documents

docs/design/introduction/air.md, docs/design/introduction/styles/animations.md, docs/design/introduction/styles/colors.md, docs/design/introduction/styles/device-compatibility.md, docs/design/introduction/styles/terminology.md, docs/design/introduction/styles/typography.md
Some image tags are corrected, such as the width attirbute.
Captions of videos or images are sometimes not properly displayed in italic as intentioned, so a blink line is inserted.
Unnecessary blank lines are deleted; hidden special characters would be removed, too.
For a new line, 2 spaces are inserted in terminology.md file.
=> Update design intro documents

docs/application/tizen-studio/TOC.md, docs/application/tizen-studio/native-tools/cover-code.md, docs/application/tizen-studio/native-tools/ui-builder.md, docs/application/tizen-studio/release-notes/2-2-release-notes.md, docs/application/tizen-studio/setup/download.md
- Add tizen studio 2.2 release notes
- Deprecate UI Component Designer
- Add Remote Inspector Known issue.
=> Add chrome known issue

docs/application/native/tutorials/details/app-filtering.md
Added 'media.audio_recording', 'media.video_recording' descriptions to app-filtering.md.
It's related TCSACR-129.
=> Add feature description

docs/application/design/wearable/styles.md
- Delete unnecessary special characters
- Add a link to iconography
=> Delete special characters

docs/blog/dotnet/xamarin/add-tizen-project-to-your-xamarin-forms-app.md
Made few minor language edits.
=>  Update add-tizen-project-to-your-xamarin-forms-app.md

docs/application/native/guides/TOC.md, docs/application/native/guides/connectivity/overview.md, docs/application/native/guides/connectivity/stc.md
=> Fix wrong url in N chaprana n chaprana

docs/application/native/guides/TOC.md, docs/application/native/guides/connectivity/overview.md, docs/application/native/guides/connectivity/stc.md
Signed-off-by: Nishant Chaprana <n.chaprana@samsung.com>
=> Integrate STC (Smart Traffic Control) native API guide.

docs/application/dotnet/guides/device/settings.md
To use property and event of Tizen.System.SystemSettings class,
http://tizen.org/feature/systemsetting feature needs to add in "tizen-manifest.xml"
=> Add feature "http://tizen.org/feature/systemsetting" description.

docs/application/native/guides/device/system.md
Signed-off-by: Kichan Kwon <k_c.kwon@samsung.com>
=> Fix invalid key name

docs/application/native/guides/connectivity/overview.md, docs/application/native/guides/connectivity/stc.md
Signed-off-by: Nishant Chaprana <n.chaprana@samsung.com>
=> Resolved review comments for native connectivity guide (overview.md and stc.md)

docs/application/distribute/TOC.md, docs/application/distribute/how-to-distribute/binary.md, docs/application/distribute/how-to-distribute/display.md, docs/application/distribute/how-to-distribute/item.md, docs/application/distribute/how-to-distribute/overview.md, docs/application/distribute/how-to-distribute/sales.md, docs/application/distribute/how-to-distribute/submit-application.md, docs/application/distribute/validation/defects-tips/fail-install-execute-or-terminate-application.md
=> Change links to have full path names in TOC.md for distribute documents

docs/application/dotnet/guides/app-management/message-port.md
Update dotnet message-port guides
=> Update dotnet message-port guides

docs/application/native/guides/device/system.md
Signed-off-by: Kichan Kwon <k_c.kwon@samsung.com>
=> Update the description about the principle of making TizenID

docs/application/tizen-studio/rt-ide/overview.md
Update for Tizen RT IDE latest version.
=> Update Tizen RT Guide.

docs/application/tizen-studio/TOC.md, docs/application/tizen-studio/release-notes/2-3-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md
Signed-off-by: KARTHIK VENKATESH BHAT/SRI-Bangalore-Tizen/./삼성전자 <kv.bhat@corp.samsungelectronics.net>
=> Update Release Notes for Tizen Studio 2.3

docs/application/design/TOC.md, docs/application/distribute/TOC.md, docs/application/vstools/tools/certificate-manager.md, docs/application/vstools/tools/emulator-manager.md
=> Fix minor errors in vstools.

docs/application/dotnet/guides/app-management/app-controls.md, docs/application/dotnet/guides/nui/styling-controls-with-JSON.md, docs/application/dotnet/guides/nui/videoview.md, docs/application/native/guides/device/system.md, docs/application/native/guides/ui/dali/actors.md, docs/application/native/guides/ui/dali/constraints.md, docs/application/native/guides/ui/dali/event-handling.md, docs/application/native/guides/ui/dali/flexcontainer.md, docs/application/native/guides/ui/dali/model3dview.md, docs/application/native/guides/ui/dali/resources.md, docs/application/native/guides/ui/dali/tableview.md, docs/application/native/guides/ui/dali/textlabel.md, docs/application/native/guides/ui/dali/touchdata.md, docs/application/native/tutorials/details/sec-privileges.md, docs/application/tizen-studio/index.md, docs/application/tizen-studio/release-notes/2-3-release-notes.md, docs/application/tizen-studio/rt-ide/getting-started/overview.md, docs/application/tizen-studio/rt-ide/overview.md, docs/application/tizen-studio/setup/prerequisites.md
- Sync md files with Tizen Developer Site, the latset version.
- Fix minor issues such as space, wrong url, line break, etc.
=> Fix minor issues and Sync with Tizen Developer Site.

docs/application/web/api/5.0/device_api/tv/index.html, docs/application/web/api/5.0/device_api/tv/tizen/mediacontroller.html
[ACR] http://suprem.sec.samsung.net/jira/browse/TWDAPI-189
Change-Id: I9a95148fc76244fce486d421d2c3329cc6d8cf65
Signed-off-by: Piotr Kosko <p.kosko@samsung.com>
=> [Mediacontroller] Adding module for TV profile

docs/application/dotnet/guides/notification/attach-panel.md, docs/application/native/guides/notification/attach-panel.md, docs/application/native/tutorials/details/app-filtering.md
Add description for new feature (http://tizen.org/feature/attach_panel)
to AttachPanel guide page and Tizen feature introduction page.
Signed-off-by: ChulSeung Kim <charles0.kim@samsung.com>
=> Add description for new feature on guide and feature introduction pages.

docs/application/native/guides/notification/attach-panel.md
Hi, 
I fixed wrong expressions that indicated in here(#226)
Please review this modification.
Thank you.
Signed-off-by: cskim <charles0.kim@samsung.com>
=> Fix wrong expression of attach panel guide

docs/application/native/guides/device/system.md
Add attach_panel feature due to this ACR(http://suprem.sec.samsung.net/jira/browse/ACR-1126).
I got a request from Ms. Kang to add new features to these files.
- docs/application/native/tutorials/details/app-filtering.md 
- docs/application/native/guides/device/system.md
But app-filtering.md is already modified with adding the new feature due to another ACR(http://suprem.sec.samsung.net/jira/browse/TCSACR-131).
So I modified system.md only for  that.
Thank you.
=> Add attach_panel feature

docs/application/web/api/4.0/device_api/mobile/tizen/ppm.html, docs/application/web/api/4.0/device_api/wearable/tizen/ppm.html, docs/application/web/api/5.0/device_api/mobile/tizen/ppm.html, docs/application/web/api/5.0/device_api/wearable/tizen/ppm.html
Changed value description in case if requested
privilege is not listed in config.xml file
ACR: TWDAPI-191
=> [PPM] Fix requestPrivilege method description

docs/application/native/guides/device/settings.md, docs/application/native/tutorials/details/app-filtering.md
[SystemSettings] add descriptions for new features.
- SYSTEM_SETTINGS_KEY_DEVELOPER_OPTION_STATE
- SYSTEM_SETTINGS_KEY_AUTOMATIC_TIME_UPDATE
- feature descriptions about systemsettings
=> Add description for systemsettings new features

docs/application/dotnet/guides/multimedia/media-playback.md, docs/application/native/guides/multimedia/media-playback.md
http://suprem.sec.samsung.net/jira/browse/ACR-1170
=> [player] add guide for native api about 360 playback

docs/application/native/guides/text-input/overview.md, docs/application/native/guides/text-input/voice-control-engine.md
ACR-1175
Signed-off-by: sungrae jo <seongrae.jo@samsung.com>
=> Add VCE(Voice-Control-Engine) guide

docs/application/native/guides/connectivity/bluetooth.md
Remove bluetooth deprecated APIs regarding ACR-1180.
=> Remove bluetooth deprecated APIs

docs/application/web/api/5.0/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/5.0/device_api/wearable/tizen/humanactivitymonitor.html, docs/application/web/guides/sensors/ham.md
ACR: TWDAPI-178
Signed-off-by: Lukasz Bardeli <l.bardeli@samsung.com>
=> [HAM] Add Sleep Detector, Stress Monitor documentation and guide

docs/application/dotnet/guides/device/settings.md
For AutomaticTimeUpdate and AutomaticTimeUpdateChangedEventArgs class
Signed-off-by: jinwang.an <jinwang.an@samsung.com>
=> Modifiy feature about tizen.org/feature/network.telephoney

docs/application/tizen-studio/TOC.md, docs/application/tizen-studio/release-notes/2-4-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md
Signed-off-by: KARTHIK VENKATESH BHAT/Tizen/Staff Engineer/삼성전자 <kv.bhat@corp.samsungelectronics.net>
=> Add Tizen Studio 2.4 Release Notes

docs/open-source-project/release-notes/tizen-5-0-m1.md
Tizen 5.0 Public M1 release note
=> add tizen 5.0 M1 release note

styleguide/style.md
The latest updates of markdown style is old version so roll it back.
=> Roll markdown style back

docs/application/native/guides/TOC.md, docs/application/native/guides/device/system.md, docs/application/native/guides/security/device-certificate-manager.md, docs/application/native/guides/security/overview.md, docs/application/native/tutorials/details/app-filtering.md
http://suprem.sec.samsung.net/jira/browse/ACR-1198
Change-Id: Iccacf297dae2a8562514380b3020cbfd20f28b3b
=> Add Device Certificate Manager API guide and feature description.

docs/application/native/guides/app-management/package-manager.md
Change-Id: I679e6150824014ca5a8a0adaf1ca313b3dd90131
Signed-off-by: Sangyoon Jang <jeremy.jang@samsung.com>
=> Add a guide for package archive info APIs

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
Signed-off-by: pr.jung <pr.jung@samsung.com>
Add vibration feature
N/A
- ACR: ACR-1113
=> [ACR-1113]Add vibration feature

docs/application/native/guides/multimedia/thumbnail-images.md
Modified the guide with new function instead of the removed function
- ACR: ACR-1112
=> Update media-content guide

docs/application/native/guides/internationalization/i18n.md
Signed-off-by: Lukasz Pik <lu.pik@samsung.com>
Fix link to wearable version of immutable index.
=> Fix link path to immutable index

docs/application/native/guides/device/system.md, docs/application/native/guides/multimedia/media-playback.md, docs/application/native/tutorials/details/app-filtering.md
This modification is for ACR-1219.
=> [Player][ACR-1219] Add 360 video feature key

docs/application/native/guides/multimedia/media-playback.md
- Fix media stream link in Player module.
=> [Player] Fix link of media stream api

docs/application/native/getting-started/mobile/first-app.md, docs/application/native/getting-started/wearable-watch/first-app-watch.md, docs/application/native/getting-started/wearable-widget/first-app-widget.md, docs/application/native/getting-started/wearable/first-app.md, docs/application/native/guides/multimedia/media-playback.md, docs/application/native/tutorials/details/app-filtering.md, docs/application/native/tutorials/details/event-handling.md, docs/application/native/tutorials/details/sec-privileges.md, docs/application/native/tutorials/feature/app-connectivity-operation.md, docs/application/native/tutorials/feature/best-practice-battery.md, docs/application/native/tutorials/process/app-dev-process.md, docs/application/native/tutorials/process/setting-properties.md, docs/application/native/tutorials/ui-builder/ui-builder-app-design.md, docs/application/native/tutorials/ui-builder/ui-builder-overview.md, docs/application/tizen-studio/index.md, docs/application/web/getting-started/mobile/first-app.md, docs/application/web/getting-started/wearable-watch/first-app-watch.md, docs/application/web/getting-started/wearable-widget/first-app-widget.md, docs/application/web/getting-started/wearable/first-app.md, docs/application/web/tutorials/sign-certificate.md
- Fix broken links of native and web tutorial & getting started docs.
- Fix broken layout
- native/tutorials/details/app-filtering.md
- native/guides/multimedia/media-playback.md
Mostly bug fix for Issue #328
=> Fix link and display issues

docs/application/tizen-studio/common-tools/certificate-registration.md, docs/application/vstools/tools/certificate-manager.md
Signed-off-by: Karthik Bhat <kv.bhat@samsung.com>
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Add developer note while creating certification.

docs/application/native/guides/TOC.md, docs/application/native/guides/multimedia/audio.md, docs/application/native/guides/multimedia/sound-manager.md
Revise audio document
The summary is revised in audio.md.
sound.md is renamed to sound-manager.md for Sound-Manager API.
=> Revise audio document

docs/application/native/guides/multimedia/image-edit.md
Deprecate image_util_transform_set_hardware_acceleration
image_util_transform_set_hardware_acceleration() API were deprecated.
So removed related sample code.
=> [ACR-1120]Update image-edit.md

docs/application/dotnet/api/overview.md
Add link for Tizen.Wearable.CircularUI github at dotnet API overview
N/A
N/A
=> Add link for Tizen.Wearable.CircularUI

docs/application/tizen-studio/TOC.md, docs/application/tizen-studio/release-notes/2-5-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md
Signed-off-by: Karthik Bhat <kv.bhat@samsung.com>
Adding Tizen Studio 2.5 Release Notes
=> Add Tizen Studio 2.5 Release Notes

docs/application/native/guides/TOC.md, docs/application/native/guides/multimedia/sound-pool.md
We missed sound-pool.md when converting HTML files to Markdown files.
=> Add sound-pool.md

docs/application/native/guides/device/system.md
Add Content Features (ACR-1129)
Feature added
http://tizen.org/feature/content.scanning.others (new), http://tizen.org/feature/content.filter.pinyin (new)
- ACR: ACR-1129
=> [ACR-1129] Add new content features (Update system.md)

docs/application/native/guides/multimedia/radio.md
Signed-off-by: Gilbok Lee <gilbok.lee@samsung.com>
update radio.md due to removal of enum
- ACR: ACR-1154
=> [Radio][ACR-1154] update radio.md due to removal of enum

docs/application/native/api/mobile/4.0/group__CAPI__MEDIA__CONTROLLER__CLIENT__MODULE.html, docs/application/native/api/mobile/4.0/group__CAPI__MEDIA__CONTROLLER__SERVER__MODULE.html, docs/application/native/api/mobile/4.0/group__CAPI__PREFERENCE__MODULE.html, docs/application/native/api/mobile/4.0/search-config.php, docs/application/native/api/wearable/4.0/group__CAPI__MEDIA__CONTROLLER__CLIENT__MODULE.html, docs/application/native/api/wearable/4.0/group__CAPI__MEDIA__CONTROLLER__SERVER__MODULE.html, docs/application/native/api/wearable/4.0/group__CAPI__PREFERENCE__MODULE.html, docs/application/native/api/wearable/4.0/search-config.php
Update Native API Reference files according to sunggyu.choi's request.
=> Update Native 4.0 api reference files (files for 04/10)

docs/application/web/api/5.0/device_api/mobile/tizen/feedback.html, docs/application/web/api/5.0/device_api/wearable/tizen/feedback.html, docs/application/web/guides/device/feedback.md
[Features]
1. Added 'vibration' feature in related feature section
2. Some stylistic changes - missing dots, indents etc.
[ACR] TWDAPI-193
Signed-off-by: Piotr Kosko <p.kosko@samsung.com>
=> [Feedback] Added related section to module

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
Add description for new feature security.privacy_privilege
- ACR: ACR-1177
=> [ACR-1177] Add security.privacy_privilege feature

docs/application/native/guides/TOC.md, docs/application/native/guides/app-management/rpc-port.md, docs/application/native/guides/app-management/tidl.md
Add  rpc-port.md and tidl.md for ACR-1263
- ACR: ACR-1263
=> [rpc-port] [ACR 1263] Add  rpc-port.md and tidl.md

docs/application/native/guides/multimedia/media-playback.md, docs/application/native/guides/multimedia/raw-audio.md
Remove deprecated APIs in Multimedia docs (wav-player/tone-player/audio-io).
- ACR:  http://suprem.sec.samsung.net/jira/browse/ACR-1134
=> Update doc (wav-player/tone-player/audio-io) for removed deprecated APIs

docs/open-source-project/release-notes/tizen-4-0-m3.md
=> Tizen 4.0 M3 release note

docs/application/dotnet/api/overview.md
Seperate Tizen.Wearable.CircualrUI API description to new API subject.
- previous CircularUI description is only one line and link.
- For supporting Gear watch .NET application.  CircularUI API link should be more easily found.
so seperate CircularUI description to new API subject.
N/A
N/A
=> Seperate Tizen.Wearable.CircualrUI to new API subject

docs/application/native/guides/ui/efl/efl-util.md
Add guides for efl_util_input_initialize_generator_with_sync().
- ACR: ACR-1266
=> [efl-util][ACR-1266]

docs/application/dotnet/samples/system/overview.md
Add detailed description to distingish similar applications.
=> [Dotnet/Sample/SystemInfo] Add detailed description for systeminfo applications

docs/application/native/guides/multimedia/raw-audio.md
Update raw-audio doc for sample type / sample rate extension
ACR: http://suprem.sec.samsung.net/jira/browse/ACR-1259
=> [raw-audio][ACR-1259] Update for sample type / sample rate extension

docs/application/dotnet/samples/system/overview.md
Fix incorrect description of UI control name
=> [Dotnet/Sample/Systeminfo] Fix incorrect description of UI control name

docs/application/dotnet/guides/text-input/input-method.md
Add New guide for floating keyboard
ACR: TCACR-163
=> [TCSACR-163]Add floating keyboard API guide

docs/application/dotnet/guides/device/attached-devices.md
Update doc for Tizen.System
Add descriptions for RequestLock/ReleaseLock/set State.
Remove descriptions for deprecated apis
N/A
http://suprem.sec.samsung.net/jira/browse/TCSACR-168
http://suprem.sec.samsung.net/jira/browse/TCSACR-170
=> Update doc for Tizen.System

docs/application/native/guides/TOC.md, docs/application/native/guides/connectivity/overview.md, docs/application/native/guides/connectivity/softap.md
Add New guide for SoftAP
- ACR: ACR-1176
=> [ACR-1176] Add guide for SoftAP

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
- Add bluetooth.le.5_0 feature
- n/a
- ACR: ACR-1289
=> [ACR-1289] Add bluetooth.le.5_0 feature

docs/application/native/guides/messaging/push-server.md, docs/application/native/guides/messaging/push.md
- Fix wrong push message field
- Add note for backgroundLaunch and BACKGROUNDLAUNCH option
- Add 8090 port for firewall exception
No ACR
=> Fix wrong push message field, add note for backgrounLaunch

docs/application/native/guides/security/privacy-related-permissions.md
Signed-off-by: Ernest Borowski <e.borowski@partner.samsung.com>
Add information about checking & requesting multiple privileges in single callback
- ACR: ACR-1253
http://suprem.sec.samsung.net/jira/browse/ACR-1253
=> [Native/guide] Add information about checking & requesting multiple privileges in single callback

docs/application/dotnet/api/netstandard-limitations.md, docs/application/dotnet/api/overview.md
Add .NET Standard API limitation doc on Tizen.
Add link for .NET Standard API limitation doc to dotnet api overview.
=> add netstandard api limitation

docs/application/native/guides/ui/dali/videoview.md
Update DALi documents about video view property for Tizen 4.0 
- ACR: ACR-1151, ACR-1171
=> [ACR-1151, ACR-1171] Update DALi documents about video view property for Tizen 4.0 

docs/application/tizen-studio/common-tools/command-line-interface.md
Signed-off-by: Vidhyadhar Jain <vidhyadhar.1@samsung.com>
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Update build-app command in CLI docs

docs/application/native/guides/TOC.md, docs/application/native/guides/connectivity/overview.md, docs/application/native/guides/connectivity/zigbee.md
Signed-off-by: Nishant Chaprana <n.chaprana@samsung.com>
- Added documentation for Zigbee framework.
- ACR: http://suprem.sec.samsung.net/jira/browse/ACR-884
=> Add Zigbee documentation

docs/application/native/guides/multimedia/sound-manager.md
Signed-off-by: Sangchul Lee <sc11.lee@samsung.com>
Add guide of new APIs for USB output device
ACR: ACR-1278
=> [sound-manager][ACR-1278] Add guide of new APIs for USB output device

docs/application/native/guides/security/privacy-related-permissions.md
Add information about checking the permission(s) of the application
with the specified app_id.
ACR: ACR-1296
http://suprem.sec.samsung.net/jira/browse/ACR-1296
=> [Native/guide] Add info about checking app permission(s)

docs/application/tizen-studio/native-tools/manifest-text-editor.md
Fix typo reported by m.s.jang.
=> Fix typo in tizen studio

docs/application/native/tutorials/details/app-filtering.md, docs/application/web/tutorials/app-filtering.md
Add `http://tizen.org/feature/display.state` feature to app-filtering.md files.
http://suprem.sec.samsung.net/jira/browse/ACR-1304
=> Add display.state 5.0 feature

docs/application/native/guides/notification/minicontrol.md, docs/application/native/guides/notification/overview.md
Signed-off-by: mk5004.lee <mk5004.lee@samsung.com>
Update minicontrol.md for wearable profile
- ACR: ACR-1302
=> [Minicontrol][ACR-1302] Update minicontrol.md

docs/application/native/tutorials/details/app-filtering.md, docs/application/native/tutorials/details/sec-privileges.md
Modifying some document formats.
Handling comments about other sections in #405.
=> Modifying some document formats

docs/application/dotnet/api/overview.md
Since the PR #350 is having merge conflict. I have closed that PR.
And raised a new PR.
=> Review of Overview.md

docs/open-source-project/release-notes/tizen-5-0-m1.md
chagne "Tizen 5.0 Public M1 release" to "Tizen 5.0 Public M1 Release Notes" for consistency.
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Change the Title of Tizen 5.0 M1 Release Notes

docs/application/toc_all.md, docs/blog/toc_all.md, docs/iot/toc_all.md, docs/open-source-project/toc_all.md
Merge all TOC.md to docs/*/toc_all.md to restruct LNB.
=> Merge all TOC.md to toc_all.md

docs/application/dotnet/guides/TOC.md, docs/application/dotnet/guides/index.md, docs/application/dotnet/guides/nlp/nlp.md, docs/application/dotnet/guides/nlp/overview.md
Add guide for Nlp api usage
- ACR: ACR-169
http://suprem.sec.samsung.net/jira/browse/TCSACR-169
=> Add document for Nlp

docs/application/native/tutorials/details/app-filtering.md, docs/application/native/tutorials/details/sec-privileges.md, docs/iot/TOC.md, docs/iot/guides/update-control-api.md
Add guide for new API: update control
- ACR: ACR-1285
=> Add guide for update control API

docs/application/dotnet/guides/app-management/app-controls.md
- SendLauncherRequest -> SendLaunchRequest
Signed-off-by: mk5004.lee <mk5004.lee@samsung.com>
=> [App-control][Non-ACR] Fix typo

docs/application/dotnet/guides/nlp/nlp.md
Remove lemmatize related info from guide for Nlp
API Changes
ACR: ACR-187
http://suprem.sec.samsung.net/jira/browse/TCSACR-187
=> Remove lemmatize related info from guide for Nlp

docs/open-source-project/TOC.md, docs/open-source-project/release-notes/tizen-5-0-m2.md
Create Tizen 5.0 M2 Release note
=> Create Tizen 5.0 M2 Release note

docs/application/dotnet/guides/multimedia/media-content.md, docs/application/dotnet/guides/multimedia/media-controller.md, docs/application/dotnet/guides/multimedia/media-playback.md, docs/application/dotnet/guides/multimedia/media-recording.md, docs/application/dotnet/guides/multimedia/raw-audio.md, docs/application/dotnet/guides/multimedia/stream-recorder.md
- Fix typo in media-contnet.md, media-controller.md, media-playback.md, media-recording.md, raw-audio.md, stream-recorder.md
- Add missing privilege description in media-controller.md.
- Remove Tizen.Xamarin.Forms.Extension.MediaView.
=> Fix description for multimedia

docs/application/tizen-studio/release-notes/3-0-release-notes.md
Updating Tizen Studio Release notes
=> Removing Chrome check for Web Inspector

docs/application/dotnet/samples/account/overview.md, docs/application/dotnet/samples/appfw/overview.md, docs/application/dotnet/samples/context/overview.md, docs/application/dotnet/samples/location/overview.md, docs/application/dotnet/samples/multimedia/overview.md, docs/application/dotnet/samples/network/overview.md, docs/application/dotnet/samples/system/overview.md, docs/application/dotnet/samples/ui/overview.md
Add the repository link of new sample apps
- Add repo link
- Fix wrong information of SystemInfo app
- Rename 2nd SystemInfo app to SystemInfo2
=> Add the repository link of new sample apps

docs/application/native/guides/multimedia/media-controller.md
Update guide for ACR-1274
- ACR: ACR-1274
=> Add document for ACR-1274

docs/iot/TOC.md
[IoT] Add two missed files to iot/TOC.md.
=> [IoT] Add two missed files to iot/TOC.md

docs/iot/TOC.md, docs/iot/guides/iot-api.md
Signed-off-by: Jihoon Park <jpark0@samsung.com>
- Correct wrong links and formats in TOC.md
- Correct a wrong link in guides/iot-api.md
N/A
N/A
=> [IoT] Correct improper links

docs/application/native/api/mobile/2.3.1/doxygen_html_stylesheet.css, docs/application/native/api/mobile/2.4/doxygen_html_stylesheet.css, docs/application/native/api/mobile/2.4/navtree.js, docs/application/native/api/mobile/3.0/doxygen_html_stylesheet.css, docs/application/native/api/mobile/3.0/navtree.js, docs/application/native/api/mobile/4.0/doxygen_html_stylesheet.css, docs/application/native/api/mobile/4.0/navtree.js, docs/application/native/api/wearable/2.3.2/navtree.js, docs/application/native/api/wearable/3.0/navtree.js, docs/application/native/api/wearable/4.0/navtree.js, docs/application/toc_all.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Change api reference page layout

docs/iot/getting-started/artik-no-sd-5.0.md, docs/iot/getting-started/artik-sd-5.0.md, docs/iot/getting-started/rpi3-5.0.md
Signed-off-by: Jihoon Park <jpark0@samsung.com>
- Change the binary link from snapshots to milestones
- Add a note to update the latest IoT Extension SDK
N/A
N/A
=> Update the link to access to the binaries

docs/application/dotnet/api/netstandard-limitations.md, docs/application/dotnet/api/overview.md
Modify wrong information in netstandard-limitations.md
N/A
N/A
=> Update netstandard limitations

docs/iot/getting-started/things-app-development-5.0.md
Signed-off-by: Jihoon Park <jpark0@samsung.com>
Correct a wrong file name (device_def.json -> master.json)
N/A
N/A
=> Correct a wrong file name (device_def.json -> master.json)

docs/application/tizen-studio/rt-ide/getting-started/debug.md, docs/application/tizen-studio/rt-ide/getting-started/flash.md
Made minor modifications to the original content.
=> Review of Flash.md

docs/application/dotnet/guides/multimedia/audio.md
Update guide page for audio management
- TCSACR-175
=> Update guide page for audio management - TCSACR-175

docs/application/tizen-studio/setup/install-sdk.md
Made minor changes in the content. Please review.
=> English review for Installing Tizen Studio page

docs/application/dotnet/guides/multimedia/raw-audio.md
Update the guide of Raw Audio Playback and Recording
- TCSACR-178
=> Update audio guide - TCSACR-178

docs/application/dotnet/samples/account/overview.md, docs/application/dotnet/samples/appfw/overview.md, docs/application/dotnet/samples/content/overview.md, docs/application/dotnet/samples/context/overview.md, docs/application/dotnet/samples/location/overview.md, docs/application/dotnet/samples/messaging/overview.md, docs/application/dotnet/samples/network/overview.md, docs/application/dotnet/samples/social/overview.md, docs/application/dotnet/samples/telephony/overview.md, docs/application/dotnet/samples/uix/overview.md, docs/application/dotnet/samples/watch/overview.md
Add simple description in case there is no sample to let readers know.
=> Add simple description in case there is no sample

docs/application/index.md
Fix a broken link on application/index.md
=> Fix a broken link on application/index.md

docs/application/tizen-studio/setup/openjdk.md, docs/application/tizen-studio/setup/prerequisites.md
Add OpenJDK installation guide.
=> Add OpenJDK installation guide

docs/application/tizen-studio/release-notes/3-1-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md, docs/application/toc_application.md
Signed-off-by: vivek ellur <vivek.ellur@samsung.com>
Add Tizen Studio 3.1 Release Notes .
=> Release notes for Tizen studio 3.1 release

docs/application/web/api/2.3.2/device_api/wearable/tizen/systeminfo_capability_keys.html, docs/application/web/api/2.4/device_api/mobile/tizen/systeminfo_capability_keys.html, docs/application/web/api/3.0/device_api/mobile/tizen/systeminfo_capability_keys.html, docs/application/web/api/3.0/device_api/tv/tizen/systeminfo_capability_keys.html, docs/application/web/api/3.0/device_api/wearable/tizen/systeminfo_capability_keys.html, docs/application/web/api/4.0/device_api/mobile/tizen/systeminfo_capability_keys.html, docs/application/web/api/4.0/device_api/tv/tizen/systeminfo_capability_keys.html, docs/application/web/api/4.0/device_api/wearable/tizen/systeminfo_capability_keys.html, docs/application/web/api/5.0/device_api/mobile/tizen/systeminfo_capability_keys.html, docs/application/web/api/5.0/device_api/tv/tizen/systeminfo_capability_keys.html, docs/application/web/api/5.0/device_api/wearable/tizen/systeminfo_capability_keys.html
Files were deleted by mistake with #494 , this commit is restoring them for all versions.
Reference commit which the files were recovered from is 57c80ea8.
=> [Capability] Restoring systeminfo_capability_keys.html for all versions

docs/application/native/tutorials/details/native-removed-history.md
Add new removed functions and alternatives in 5.5
=> Add new removed functions and alternatives

docs/iot/toc_all.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Change the menu title to IoT Partners

docs/open-source-project/porting/kernel.md, docs/open-source-project/porting/system.md
Describe kernel configuration options required by resourced swap module.
Fix minor grammar error.
=> Porting resourced guide

docs/application/dotnet/getting-started/app-filtering.md, docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md, docs/application/web/tutorials/app-filtering.md
Signed-off-by: pr.jung <pr.jung@samsung.com>
Add external storage feature
N/A
ACR-1319
=> Add external storage feature

docs/application/dotnet/getting-started/app-filtering.md, docs/application/dotnet/guides/device/settings.md
[TCSACR-215][Add Accessibility feature]
=> [Settings] Add features: http://tizen.org/feature/accessibility.*

docs/application/dotnet/guides/app-management/app-controls.md
- Add an explanation of SendLaunchRequestAsync() method
- ACR: TCSACR-198
=> Add an explanation of SendLaunchRequestAsync() method

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
ACR-1318] add new features
- http://tizen.org/feature/accessibility.grayscale
- http://tizen.org/feature/accessibility.negative
=> [ACR-1318] add new features

docs/application/native/guides/device/runtime.md
=> Remove the description about deprecated enum values

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_DropdownMenu.htm
[Problem] Examples contained mixed JS and HTML code,
some function signatures return types were missing
[Solution] Code examples were separated and missing return types were added
=> DropdownMenu: Improve documentation redability

docs/application/native/guides/ui/efl/wearable/component-circle-slider.md
Updated tizen wearable UX applies to version 4.0 or higher.
=> Fix component-circle-slider dependency in docs.

docs/application/native/guides/app-management/app-controls.md
- Add the description about app_control_send_launch_request_sync() and app_control_send_launch_request_async() functions.
- ACR: ACR-1340
=> Modify AppControl guide

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html
Adding new methods and attributes  to control repeatState and deprecate repeatMode
ACR: TWDAPI-204
Signed-off-by: Lukasz Bardeli <l.bardeli@samsung.com>
=> [Mediacontroller] Adding and deprecating attributes and methods

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_button.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_checkbox.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circleprogressbar.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_indexscrollbar.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_list.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_pageindicator.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_popup.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_processing.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_sectionchanger.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_selector.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_slider.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_snaplistview.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_toggleswitch.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_virtuallist.htm
[Problem] HTML Templates haven't got included example photos or videos.
[Solution] Adding example photos and videos to html templates.
=> Adding photos and videos to HTML Templates

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ColoredListview.htm
[Problem] Code example contained mixed HTML and JS code
[Solution] Separate JS and HTML code in examples
=> Mobile,ColoredListView: Improve widget documentation readability

docs/application/native/guides/connectivity/nfc.md
Add note for HCE application performance
=> Add note for HCE application performance

docs/application/tizen-studio/release-notes/3-2-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
Release notes for Tizen studio 3.2 release
=> Release notes for Tizen studio 3.2 release

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Button.htm
[Problem] HTML and JS code in examples was mixed
[Solution] Separate HTML and JS code in samples
=> Button: Separate HTML and JS code in examples

docs/application/native/guides/security/privilege.md
=> [ACR-1341] Add guide for new API

docs/application/native/guides/device/system.md
Signed-off-by: lokilee73 <changjoo.lee@samsung.com>
- ACR: http://suprem.sec.samsung.net/jira/browse/ACR-1343
=> [ACR-1343] Add a description for thermal API in guides

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Navigation.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Progress.htm
Signed-off-by: Dominik Orliński <d.orlinski@samsung.com>
=> Separate JS from HTML in code snippets

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_selector.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_swipelist.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_viewSwitcher.htm
[Problem] In some code snippets there are self invoked function.
[Solution] Remove from examples self invoked function
Signed-off-by: Dominik Orliński <d.orlinski@samsung.com>
=> Remove self invoked function from JS code snippets

docs/application/toc_all.md
Fix broken link for w3c menu tree.
=> Fix broken link for w3c menu tree

docs/application/native/guides/text-input/autofill-manager.md, docs/application/native/guides/text-input/autofill-service.md, docs/application/native/guides/text-input/autofill.md, docs/application/native/guides/text-input/overview.md, docs/application/toc_all.md
Signed-off-by: Jihoon Kim <jihoon48.kim@samsung.com>
- Add autofill document
- ACR: ACR-1311
=> [ACR-1311] Add autofill document

docs/application/dotnet/guides/multimedia/camera.md, docs/application/dotnet/guides/multimedia/overview.md, docs/application/dotnet/guides/overview.md, docs/application/toc_all.md
Update camera page for adding RgbPlane.
TCSACR-185
=> Update camera and multimedia page

docs/application/dotnet/guides/multimedia/camera.md
Update camera md file.
- TCSACR-185
=> Update camera page

docs/application/dotnet/guides/security/requesting-permissions.md
Add new section that describes how to use new API that support
checking & requesting multiple privileges in single API call.
Signed-off-by: Ernest Borowski <e.borowski@partner.samsung.com>
- Add new section that describes how to use new API that support
checking & requesting multiple privileges in single API call.
- change code blocks type to `csharp`
- ACR: ACR-1288
=> [ACR-1288] Update guide about checking & requesting privileges.

docs/application/web/api/5.5/device_api/tv/tizen/tvwindow.html
[TvWindow] Add subtitles and Closed Captions support inside TvWindow
Subtitles and CC can now be shown in TvWindow when using RF stream.
[ACR] TWDAPI-200
Subtitles and CC can now be shown in TvWindow when using RF stream.
---
[ACR] TWDAPI-200
=> [TvWindow] Add subtitles and Closed Captions support inside TvWindow

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Progress.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Radio.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SearchInput.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SectionChanger.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ToggleSwitch.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_sectionchanger.htm
[Problem] Some method does not have return value in their declaration despite that they return value
[Solution] Fill missing return types
Signed-off-by: Dominik Orliński <d.orlinski@samsung.com>
=> Missing return types in method signatures

docs/application/tizen-studio/release-notes/2-3-release-notes.md, docs/application/tizen-studio/release-notes/2-4-release-notes.md, docs/application/tizen-studio/release-notes/2-5-release-notes.md, docs/application/tizen-studio/release-notes/3-0-release-notes.md, docs/application/tizen-studio/release-notes/3-1-release-notes.md
Made minor modification to the content.
=> Review of Release Notes

docs/application/web/guides/data/data-filter.md
[ACR] http://suprem.sec.samsung.net/jira/browse/TWDAPI-210
Marked filtering attribute as deprecated
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [Content] Deprecated filtering attribute

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_slider.htm
[Problem] Wearable slider documentation did not provide useful information
[Solution] Edit slider widget documentation
=> Improve wearable slider documentation

docs/application/native/guides/applications/overview.md
Add the note about the app_get_display_state() function
- ACR: ACR-1310
=> Add the note about the app_get_display_state() function

docs/application/web/api/2.3.2/device_api/wearable/tizen/content.html, docs/application/web/api/2.4/device_api/mobile/tizen/content.html, docs/application/web/api/3.0/device_api/mobile/tizen/content.html, docs/application/web/api/3.0/device_api/tv/tizen/content.html, docs/application/web/api/3.0/device_api/wearable/tizen/content.html, docs/application/web/api/4.0/device_api/mobile/tizen/content.html, docs/application/web/api/4.0/device_api/tv/tizen/content.html, docs/application/web/api/4.0/device_api/wearable/tizen/content.html, docs/application/web/api/5.0/device_api/mobile/tizen/content.html, docs/application/web/api/5.0/device_api/tv/tizen/content.html, docs/application/web/api/5.0/device_api/wearable/tizen/content.html
=> Added remark with link to 'Data Filtering and Sorting' guide.

docs/iot/getting-started/things-app-development-5.0.md, docs/iot/getting-started/things-app-development.md, docs/iot/getting-started/things-cloud-setup.md, docs/iot/guides/things-api-guide-5.0.md
=> Update devworkspace URL

docs/application/native/tutorials/details/native-removed-history.md
Add newly removed enums in Tizen 5.5
=> Add newly removed items

docs/application/web/api/index.md
[Web API Reference] Redirect to mobile/index.html
=> [Web API Reference] Redirect to mobile/index.html

docs/application/dotnet/get-started/mobile/first-app.md, docs/application/dotnet/get-started/tv/first-app.md, docs/application/dotnet/get-started/wearable/first-app.md, docs/application/native/get-started/mobile/first-app.md, docs/application/native/get-started/wearable-watch/first-app-watch.md, docs/application/native/get-started/wearable-widget/first-app-widget.md, docs/application/native/get-started/wearable/first-app.md, docs/application/toc_all.md, docs/application/web/get-started/mobile/first-app.md, docs/application/web/get-started/tv/first-app.md, docs/application/web/get-started/wearable-watch/first-app-watch.md, docs/application/web/get-started/wearable-widget/first-app-widget.md, docs/application/web/get-started/wearable/first-app.md
Change "Creating" of the Get-started page titles and navigation bar menu title to "Create".
=> Change 'Creating' to 'Create' in Get-started pages

docs/application/tizen-studio/index.md
The version information in tizen-studio/index.md should be updated.
- The latest version : to Tizen Studio 3.2
- The 64 bits only version : from Tizen Studio 3.5
=> Update Tizen Studio index.md

docs/application/vstools/tools/certificate-manager.md, docs/application/vstools/tools/memory-profiler-user-manual.md, docs/application/vstools/tools/project-wizard.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Dev fix character header

docs/application/dotnet/guides/connectivity/bluetooth.md
Remove the deprecated APIs in the guide
- ACR: TCSACR-235
=> [Bluetooth][TCSACR-235] Remove the deprecated APIs in the guide

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html, docs/application/web/guides/multimedia/media-controller.md
Add documentation for WebAPI playlist feature.
ACR: http://suprem.sec.samsung.net/jira/browse/TWDAPI-199
=> [TWDAPI-199] Playlist for mediacontroller guide

docs/application/native/guides/device/system.md
- Add a guide about device type key.
- ACR: ACR-1381
=> Add a guide about device type key

docs/application/dotnet/guides/connectivity/bluetooth.md
Remove the deprecated APIs in the guide
- ACR: TCSACR-238
=> [Bluetooth][TCSACR-238] Remove the deprecated APIs in the guide

docs/application/vstools/tools/certificate-manager.md, docs/application/vstools/tools/memory-profiler-user-manual.md, docs/application/vstools/tools/project-wizard.md
Pull request for fix issue
https://github.sec.samsung.net/RS8-TIZENWEBSITE/docs.tizen.org/issues/198
=> Live fix md header

docs/application/vstools/tools/certificate-manager.md, docs/application/vstools/tools/memory-profiler-user-manual.md, docs/application/vstools/tools/project-wizard.md
Pull request for fix issue
https://github.sec.samsung.net/RS8-TIZENWEBSITE/docs.tizen.org/issues/198
=> Master fix md header

docs/application/native/tutorials/details/native-removed-history.md
newly deleted enum
PLAYER_DISPLAY_TYPE_OBSOLETE_EVAS_WNONE, PLAYER_DISPLAY_TYPE_OBSOLETE_NONE_WEVAS
newly deleted functions
elm_ctxpopup_direction_available_get()
elm_win_profiles_set()
=> Add new removed items of Tizen Native API

docs/application/tizen-studio/setup/prerequisites.md
Change Supported OS Version
Signed-off-by: seok.oh <seok.oh@samsung.com>
=> change supported OS version

docs/open-source-project/release-notes/tizen-5-5-m1.md, docs/platform/release-notes/tizen-5-5-m1.md, docs/platform/toc_all.md
Update Tizen 5.5 Public M1 Release Note after reviewing https://github.com/Samsung/tizen-docs/pull/707
.
=> Update Tizen 5.5 Public M1 Release Note

docs/platform/release-notes/tizen-5-5-m1.md
Removed special character in 5.5 release notes.
=> Remove special character in 5.5 release notes

docs/application/web/api/5.5/device_api/tv/tizen/systeminfo.html
ACR: TWDAPI-223
Signed-off-by: Lukasz Bardeli <l.bardeli@samsung.com>
=> [SystemInfo] Add SERVICE_COUNTRY property

docs/application/dotnet/guides/multimedia/media-content.md
Remove guide for deprecated APIs. (TCSACR-243)
=> [MediaContent] Remove guide for deprecated APIs

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html, docs/application/web/guides/multimedia/media-controller.md
http://suprem.sec.samsung.net/jira/browse/TWDAPI-221
[mediacontroller] Add API to get/set server icon URI.
+ readonly attribute MediaControllerServerInfo::iconURI
+ attribute MediaControllerServer::iconURI
+ MediaControllerServer::updateIconURI()
ACR: http://suprem.sec.samsung.net/jira/browse/TWDAPI-221
=> Add server icon API.

docs/application/dotnet/guides/app-management/overview.md, docs/application/dotnet/guides/app-management/widget-control.md, docs/application/toc_all.md
Signed-off-by: hyunho <hhstark.kang@samsung.com>
Add widget control guide
=> Add widget control guide

docs/application/dotnet/guides/app-management/event.md, docs/application/dotnet/guides/app-management/overview.md, docs/application/toc_all.md
- Adds guide for EventManager
- ACR: TCSACR-227
=> [TCSACR-227] Adds guide for EventManager

docs/application/dotnet/guides/multimedia/metadata.md
Add new API(Composer property) and deprecate old one(Author property)
- TCSACR-209
=> [TCSACR-209] Add new API and delete deprecated one

docs/application/dotnet/guides/multimedia/camera.md
Add new preview format.
- TCSACR-173
=> [TCSACR-173] Add new preview format

docs/application/dotnet/guides/connectivity/internet-download.md, docs/application/dotnet/guides/connectivity/webview.md, docs/application/toc_all.md
This patch adds guide for WebView of dotnet application.
=> Add guide for WebView

docs/application/dotnet/guides/multimedia/media-controller.md
Update guide for MediaController Playlist
- TCSACR-188
=> [TCSACR-188] Update guide for MediaController Playlist

docs/application/dotnet/samples/content/overview.md, docs/application/dotnet/samples/general/overview.md, docs/application/dotnet/samples/network/overview.md, docs/application/dotnet/samples/ui/overview.md, docs/application/dotnet/samples/watch/overview.md
Add the download link for newly approved apps
=> Add the download link for newly approved apps

docs/application/web/api/5.5/device_api/mobile/tizen/tizen.html, docs/application/web/api/5.5/device_api/tv/tizen/tizen.html, docs/application/web/api/5.5/device_api/wearable/tizen/tizen.html
tizen.Bundle interface definition.
- ACR: http://suprem.sec.samsung.net/jira/browse/TWDAPI-225
=> Define tizen.Bundle interface.

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Button.htm
Added button example opening code.tizen.org example in new window
=> Add posibility to open button example

docs/application/web/api/5.5/device_api/mobile/tizen/content.html, docs/application/web/api/5.5/device_api/mobile/tizen/filesystem.html, docs/application/web/api/5.5/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/5.5/device_api/mobile/tizen/nfc.html, docs/application/web/api/5.5/device_api/mobile/tizen/notification.html, docs/application/web/api/5.5/device_api/tv/tizen/content.html, docs/application/web/api/5.5/device_api/tv/tizen/filesystem.html, docs/application/web/api/5.5/device_api/tv/tizen/tvchannel.html, docs/application/web/api/5.5/device_api/tv/tizen/tvwindow.html, docs/application/web/api/5.5/device_api/wearable/tizen/content.html, docs/application/web/api/5.5/device_api/wearable/tizen/filesystem.html, docs/application/web/api/5.5/device_api/wearable/tizen/humanactivitymonitor.html, docs/application/web/api/5.5/device_api/wearable/tizen/nfc.html, docs/application/web/api/5.5/device_api/wearable/tizen/notification.html
We have updated out autoformatting tool which detected some previously undetected issues which are fixed in this commit.
=> Formatting changes after updating autoformatting tool.

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ColoredListview.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_DropdownMenu.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Expandable.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_FloatingActions.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_GridView.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_IndexScrollBar.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Navigation.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_PageIndicator.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_PanelChanger.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Popup.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Progress.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Radio.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SearchInput.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SectionChanger.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Slider.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Tabs.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_TextEnveloper.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_TextInput.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ToggleSwitch.htm
Issue: https://github.com/Samsung/TAU/issues/199
Problem: No links to examples
Solution: Add links to examples on code.tizen.org
=> Mobile - 5.0 - Add links to examples

docs/application/dotnet/guides/multimedia/media-controller.md
Update guide for MediaController command
- TCSACR-176
=> [TCSACR-176] update guide for MediaController command

docs/application/native/guides/multimedia/media-controller.md
Update guides for the retrieving information
=> Update guides for the retrieving information

docs/application/native/guides/personal/phonenumber.md
Signed-off-by: jk.koo <jk.koo@samsung.com>
Add privilege to Prerequisites section
http://suprem.sec.samsung.net/jira/browse/ACR-1055
=> Add privilege to Prerequisites section

docs/application/tizen-studio/release-notes/3-3-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
Signed-off-by: Vivek Ellur <vivek.ellur@samsung.com>
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Release notes for Tizen studio 3.3 release

docs/application/tizen-studio/index.md, docs/application/tizen-studio/release-notes/3-3-release-notes.md
Update Tizen Studio 3.3 release information
=> Update Tizen Studio 3.3 information

docs/application/native/guides/data/data-storages.md
Signed-off-by: Yunmi Ha <yunmi.ha@samsung.com>
For instance,
- Add privilege guide in prerequisites section
For instance,
- N/A
For instance,
- N/A
=> [DataStorages] Add privilege guide in prerequisites section

docs/application/dotnet/guides/multimedia/thumbnail-images.md
Add sync thumbnail extract API
- TCSACR-250
=> [ThumbnailExtractor][TCSACR-250] Add sync thumbnail extract API

docs/application/dotnet/guides/multimedia/media-controller.md
Add description for new event API
- TCSACR-186
=> [MediaContent][TCSACR-186] Add description for new event API

docs/application/tizen-studio/web-tools/config-editor.md
Add the guide for launch_screen element to config-editor.md
=> Add the guide for launch_screen element to config-editor.md

docs/application/native/guides/alarm/alarms.md
Adds guide for Alarm Update API
- ACR: ACR-904
=> [ACR-904] Adds guide for Alarm Update API

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Button.htm
Reverts Samsung/tizen-docs#763
Request from cookie@samsung.com
=> Revert "Add posibility to open button example"

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ColoredListview.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_DropdownMenu.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Expandable.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_FloatingActions.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_GridView.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_IndexScrollBar.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Navigation.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_PageIndicator.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_PanelChanger.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Popup.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Progress.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Radio.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SearchInput.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SectionChanger.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Slider.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Tabs.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_TextEnveloper.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_TextInput.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ToggleSwitch.htm
Reverts Samsung/tizen-docs#768
Request from cookie@samsung.com
=> Revert "Mobile - 5.0 - Add links to examples"

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_button.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_checkbox.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circleprogressbar.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_datepicker.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_list.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_numberpicker.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_pageindicator.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_popup.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_processing.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_sectionchanger.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_selector.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_slider.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_snaplistview.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_timepicker.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_toggleswitch.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_virtuallist.htm
Reverts Samsung/tizen-docs#772
Request from cookie@samsung.com
=> Revert "Add links for wearable examples (5.0)"

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
- ACR-1132 : Add media codec feature
=> [ACR-1132] Add media codec feature

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/mobile/tizen/tizen.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/tv/tizen/tizen.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/tizen.html, docs/application/web/guides/multimedia/media-controller.md
http://suprem.sec.samsung.net/jira/browse/TWDAPI-208
Add web API equivalent of native media controller search API.
http://suprem.sec.samsung.net/jira/browse/TWDAPI-208
=> [mediacontroller] Add search API.

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html, docs/application/web/guides/multimedia/media-controller.md
http://suprem.sec.samsung.net/jira/browse/TWDAPI-226
+ fix display of attribute Bundle in constructor
=> [mediacontroller] add Bundle to sendCommand

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_popup.htm
[Issue] https://github.com/Samsung/TAU/issues/215
[Problem] Popup documentation doesn't contain ToC
[Solution] Added ToC
=> Add ToC to wearable popup documentation

docs/application/native/tutorials/details/native-removed-history.md
Adds newly removed functions and enums of DALi
=> Adds newly removed functions and enums of DALi

docs/application/native/guides/alarm/alarms.md
- Updates guide for Alarm API
- ACR: ACR-1440
=> [ACR-1440] Updates guide for Alarm API

docs/application/native/guides/notification/notifications.md
Signed-off-by: mk5004.lee <mk5004.lee@samsung.com>
Update privilege comment for indirect launch
none
none
=> Update privilege comment for indirect launch

docs/application/dotnet/guides/messaging/push-server.md, docs/application/tizen-studio/setup/prerequisites.md
=> Fix minor issues

docs/platform/porting/system.md
=> Add guide for crash framework

docs/application/web/api/5.0/ui_fw_api/Base/popup.htm
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/345
[Problem] Documentaiton is not clear about popup opening
[Solution] Update popup documentation regarding to argument
=> Update popup documentation

docs/application/native/api/mobile/4.0/group__CAPI__PACKAGE__INFO__MODULE.html, docs/application/native/api/mobile/4.0/group__CAPI__PACKAGE__MANAGER__MODULE.html, docs/application/native/api/mobile/5.0/group__CAPI__PACKAGE__MANAGER__MODULE.html, docs/application/native/api/wearable/4.0/group__CAPI__PACKAGE__INFO__MODULE.html, docs/application/native/api/wearable/4.0/group__CAPI__PACKAGE__MANAGER__MODULE.html, docs/application/native/api/wearable/5.0/group__CAPI__PACKAGE__MANAGER__MODULE.html
4.0 and 5.0 mobile/wearable Native API Reference files.
- Fix the wrong setting of privilege level, from platform level to public level.
ACR-1454
=> Update Native 4.0 and 5.0 API Reference

docs/application/dotnet/guides/nui/textlabel.md
[NUI] changes of TCSACR-214
remove deprecated APIs
document review
http://suprem.sec.samsung.net/jira/browse/TCSACR-214
=> [NUI] changes of TCSACR-214

docs/application/dotnet/guides/multimedia/raw-audio.md
Add new sample and channel type
- TCSACR-276
=> [AudioIO][TCSACR-276] Add new sample and channel type

docs/application/dotnet/tutorials/app-filtering.md, docs/application/native/tutorials/details/app-filtering.md, docs/application/web/tutorials/app-filtering.md
Add display 5.5 feature
- ACR: ACR-1426
=> Add display 5.5 feature

docs/application/dotnet/guides/multimedia/media-content.md
=> [MediaContent] Change inner link style

docs/application/tizen-studio-0/common-tools/dynamic-analyzer/overview.md, docs/application/tizen-studio/common-tools/dynamic-analyzer/overview.md
relates to https://github.com/Samsung/tizen-docs/pull/792 .
Signed-off-by: Dongkyun Son <dongkyun.s@samsung.com>
=> Dynamic analyzer does not support web applications

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html, docs/application/web/guides/multimedia/media-controller.md
Documentation and guide for new features and abilities of MediaController server has been added.
ACRs: TWDAPI-227, TWDAPI-229, TWDAPI-230, TWDAPI-231, TWDAPI-232, TWDAPI-233, TWDAPI-234
NativeACR: ACR-1428, ACR-1444
Signed-off-by: Rafal Walczyna <r.walczyna@samsung.com>
=> [web][mediacontroller] Added guide and docs for abilites and features

docs/application/native/guides/ui/dali/buttons.md
Change-Id: I3afadc9afaf800fdb1a6673f449ae83fe97235cf
Updates to md file after ACR.  Some removed API were being used in the guide.
ACR-1435
=> [DALI][ACR-1435] Remove deprecated API in Tizen 5.5

docs/application/web/guides/multimedia/media-controller.md, docs/application/web/guides/multimedia/overview.md
Information about TV support has been added.
Code examples indentation has been fixed.
Signed-off-by: Rafal Walczyna <r.walczyna@samsung.com>
=> [web][mediacontroller][guide] Fix in guides resulting from TV support

docs/application/tizen-studio/setup/prerequisites.md
Signed-off-by: Karthik Bhat <kv.bhat@samsung.com>
- Update the Tizen Studio prerequisites.
=> Update Tizen Studio PreRequisites.

docs/iot/iot-partners/nubison.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Update incorrect sentences in Nubison document

docs/application/native/guides/device/battery-monitor.md, docs/application/native/guides/device/overview.md, docs/application/toc_all.md
Add a new document for Battery Monitor Framework
For instance,
- ACR-1437
=> Add a new Guide for Battery Monitor

docs/application/dotnet/guides/multimedia/media-controller.md
Update media controller guide which already modified and merged in master branch.
The reason why it's merged only in master branch is that it's modified after releasing tizen 5.0 and creating tizen_5.5_prepare branch.
I'll update media controller guide for tcsacr-273 and 283 based on this latest modification to tizen_5.5_prepare branch.
=> [MediaController] Update document which already merged in master branch

docs/application/native/guides/multimedia/raw-audio.md
Update raw-audio doc for sample type / channel extension
ACR: http://suprem.sec.samsung.net/jira/browse/ACR-1434
=> [raw-audio][acr-1434] update audio-io guide for channel / format extension

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html, docs/application/web/guides/multimedia/media-controller.md
[ACR] http://suprem.sec.samsung.net/jira/browse/TWDAPI-209
+ HTML documentation updated with the description of the new feature.
+ Updated media controller guide.
+ HTML documentation updated with the description of the new feature.
+ Updated media controller guide.
- ACR: TWDAPI-209
=> [mediacontroller] Sending custom events from server to client.

docs/application/dotnet/guides/app-management/component-manager.md, docs/application/dotnet/guides/app-management/overview.md, docs/application/toc_all.md
Add a new guide for component manager
- ACR: TCSACR-261
=> [TCSACR-261] Add a new guide for component manager

docs/application/native/guides/multimedia/media-controller.md
Add new APIs for subtitles, 360 mode, display mode, display rotation
=> Apply ACR-1444

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/mobile/tizen/messaging.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html
This pull request contains changes mentioned in TWDAPI-240 and some fixes in documentation
=> Fixes and twdapi 240

docs/application/tizen-studio/native-tools/manifest-text-editor.md
Update Manifest Editor for component-based-application
=> Update Manifest Editor for Component-based application

docs/application/tizen-studio/web-tools/index.md, docs/application/tizen-studio/web-tools/running-testing.md, docs/application/tizen-studio/web-tools/web-simulator-features.md, docs/application/tizen-studio/web-tools/web-simulator.md, docs/application/toc_all.md
Added missed pages to the Application menu tree.
=> Add missed pages to Application menu tree

docs/application/native/tutorials/details/app-filtering.md
- ACR-1420 : audio offload feature
- Add media codec feature which was added in master but it is not included 5.5 branch.
=> [ACR-1420] Add audio offload feature

docs/application/native/guides/machine-learning/machine-learning-inference.md, docs/application/native/guides/machine-learning/overview.md
- remove the glib dependency
- fix typos
- fix the wrong examples
Signed-off-by: HyoungJoo Ahn <hello.ahn@samsung.com>
=> [Machine-learning][ACR-1382] document for machine-learning-inference

docs/application/tizen-studio/release-notes/3-5-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/tizen-studio/setup/prerequisites.md, docs/application/toc_all.md
Prerequisites and Release notes for Tizen Studio 3.5 release
=> Prerequisites and Release notes for Tizen Studio 3.5 release

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html
this commit fixes code examples in media controller module
=> [mediacontroller] fix code examples

docs/platform/release-notes/tizen-5-5-m2.md, docs/platform/toc_all.md
=> Tizen 5.5 M2 Release Note

docs/application/tizen-studio/setup/prerequisites.md
Update java prerequisites version.
=> Update java prerequisites version

docs/application/native/guides/device/settings.md
- SYSTEM_SETTINGS_KEY_ACCESSIBILITY_GRAYSCALE
- SYSTEM_SETTINGS_KEY_ACCESSIBILITY_NEGATIVE_COLOR
- SYSTEM_SETTINGS_KEY_ROTARY_EVENT_ENABLED
Signed-off-by: jinwang.an <jinwang.an@samsung.com>
=> Update system settings enum table.

docs/application/tizen-studio/setup/openjdk.md, docs/application/vscode-ext/index.md, docs/application/vstools-mac/overview.md, docs/application/vstools/install.md
=> Update guide to Open JDK 12

docs/application/native/guides/notification/notification-ex.md
Signed-off-by: mk5004.lee <mk5004.lee@samsung.com>
Fix typo in notification-ex.md
=> Fix typo in notification-ex.md

docs/iot/toc_all.md
TPL requested to change menu tree of IoT API reference.
=> Change TOC of IoT

docs/application/toc_all.md, docs/platform/reference/tizen-studio/environment.md, docs/platform/reference/tizen-studio/local-build.md, docs/platform/reference/tizen-studio/meta-package.md, docs/platform/reference/tizen-studio/overview.md
Fix broken links in platform/tizen-studio
=> Fix broken links in platform/tizen-studio

docs/application/web/api/5.5/device_api/tv/tizen/tvaudiocontrol.html
[ACR] http://suprem.sec.samsung.net/jira/browse/TWDAPI-243
=> [TVAudio] Added support for Dolby Digital Plus

docs/application/get-started/mobile.md, docs/application/get-started/tv.md, docs/application/get-started/wearable.md, docs/application/index.md, docs/application/toc_all.md
Change menu tree based on priority.
- Wearable, TV, and Mobile
- .Net App, Web App, Native App
=> Change the order of menu tree in terms of priority.

docs/platform/release-notes/tizen-1-0.md, docs/platform/release-notes/tizen-2-0.md, docs/platform/release-notes/tizen-2-1.md, docs/platform/release-notes/tizen-2-2-1.md, docs/platform/release-notes/tizen-2-2.md, docs/platform/release-notes/tizen-2-3-1.md, docs/platform/release-notes/tizen-2-3-2.md, docs/platform/release-notes/tizen-2-3.md, docs/platform/release-notes/tizen-2-4.md, docs/platform/release-notes/tizen-3-0-m2.md, docs/platform/release-notes/tizen-3-0-m3.md, docs/platform/release-notes/tizen-3-0-m4.md, docs/platform/release-notes/tizen-3-0-milestones.md, docs/platform/release-notes/tizen-4-0-m1.md, docs/platform/release-notes/tizen-4-0-m2.md, docs/platform/release-notes/tizen-4-0-m3.md, docs/platform/release-notes/tizen-5-0-m1.md, docs/platform/release-notes/tizen-5-0-m2.md, docs/platform/release-notes/tizen-5-5-m1.md, docs/platform/release-notes/tizen-5-5-m2.md
Added platform details to release notes.
=> Add platform details to release notes

docs/application/dotnet/tutorials/sec-privileges.md, docs/application/native/tutorials/details/sec-privileges.md
Update 5.5 privilege changes:
- Add: autofillmanager, d2d.datasharing, d2d.remotelaunch, securesysteminfo, voicecontrol.tts and windowsystem.admin
- Change: telephony (removed access permission to non-resettable secure device information such as IMEI)
=> Update privilege document according to the latest privilege info

docs/application/web/api/5.5/device_api/tv/tizen/systeminfo.html
[acr]
http://suprem.sec.samsung.net/jira/browse/TWDAPI-242
=> [systeminfo] add systemInfoPanel

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm, docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm
[Issue] https://github.com/Samsung/TAU/issues/480
=> Add missing Marque style option value

docs/application/web/api/3.0/device_api/tv/tizen/application.html, docs/application/web/api/4.0/device_api/tv/tizen/application.html, docs/application/web/api/5.0/device_api/tv/tizen/application.html, docs/application/web/api/5.5/device_api/tv/tizen/application.html
* added remark related to abuse of web API for launching applications (TV only) changes in files:
docs/application/web/api/3.0/device_api/tv/tizen/application.html
docs/application/web/api/4.0/device_api/tv/tizen/application.html
docs/application/web/api/5.0/device_api/tv/tizen/application.html
docs/application/web/api/5.5/device_api/tv/tizen/application.html
=> [All versions] Added remark for TV application API

docs/application/tizen-studio/setup/prerequisites.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Updating prerequisites for RT

docs/application/dotnet/samples/messaging/overview.md, docs/application/dotnet/samples/social/overview.md, docs/application/dotnet/samples/uix/overview.md
Removes "In progress" from the title of some apps and adds git repo address
=> Add git repo address for newly approved apps

docs/application/dotnet/api/overview.md, docs/application/dotnet/api/xamarin-forms-limitations.md
Added style for squared-button and squared-button-reverse in xamarin-forms-limitations.md.
=> Add style for squared-button

docs/application/web/api/4.0/device_api/wearable/tizen/account.html, docs/application/web/api/4.0/device_api/wearable/tizen/alarm.html, docs/application/web/api/4.0/device_api/wearable/tizen/application.html, docs/application/web/api/4.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/4.0/device_api/wearable/tizen/calendar.html, docs/application/web/api/4.0/device_api/wearable/tizen/contact.html, docs/application/web/api/4.0/device_api/wearable/tizen/cordova/file.html, docs/application/web/api/4.0/device_api/wearable/tizen/cordova/filetransfer.html, docs/application/web/api/4.0/device_api/wearable/tizen/cordova/media.html, docs/application/web/api/4.0/device_api/wearable/tizen/download.html, docs/application/web/api/4.0/device_api/wearable/tizen/exif.html, docs/application/web/api/4.0/device_api/wearable/tizen/iotcon.html, docs/application/web/api/4.0/device_api/wearable/tizen/nfc.html, docs/application/web/api/4.0/device_api/wearable/tizen/notification.html, docs/application/web/api/4.0/device_api/wearable/tizen/time.html, docs/application/web/api/4.0/device_api/wearable/tizen/tizen.html, docs/application/web/api/4.0/device_api/wearable/tizen/voicecontrol.html
This PR adds changes which were accidentally missed in PR #944 
4.0 wearable change style is now also added.
=> [4.0] Fixed 'contructor' sections missed in PR #944

docs/application/dotnet/get-started/overview.md, docs/application/native/get-started/overview.md, docs/application/vstools-mac/overview.md, docs/application/vstools/index.md, docs/application/web/get-started/overview.md
1. Change the order of creating applications in overview.
2. Fix typo
=> Change the order of creating applications in overview

docs/application/web/guides/w3c/perf-opt/performance-improvement.md
Add web frameworks guide for web application performance.
For instance,
- Add a sub-item to performance-improvement
=> [web][guide] Add web frameworks guide

docs/application/tizen-studio/common-tools/log-view.md, docs/application/tizen-studio/release-notes/3-6-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
Add Release Notes for Tizen Studio 3.6.
=> Release Notes for Tizen Studio 3.6 release

docs/application/dotnet/guides/connectivity/overview.md, docs/application/dotnet/guides/connectivity/stc.md, docs/application/toc_all.md
Added C# API usage guide
In case of ACR, put the link of ACR: 
http://suprem.sec.samsung.net/jira/browse/TCSACR-217
For instance,
- ACR: ACR-217
=>  C# API usage guide

docs/application/dotnet/guides/nui/animation-types.md, docs/application/dotnet/guides/nui/animation.md, docs/application/dotnet/guides/nui/media/bezier.svg, docs/application/dotnet/guides/nui/media/complexanimation.svg, docs/application/dotnet/guides/nui/media/easeout.svg, docs/application/dotnet/guides/nui/media/path.svg, docs/application/dotnet/guides/nui/media/properties.svg
- Fix examples that are not valid any more.
- Improve image resources
- Remove contents that are too deep in technically.
=> [NUI] Update Animation documents

docs/application/native/guides/multimedia/media-handle.md
Signed-off-by: Jeongmo Yang <jm80.yang@samsung.com>
- Add missed and new feature for ACR-1214 and ACR-1394
=> [Multimedia][media-handle] Update for ACR-1214 and ACR-1394

docs/platform/toc_all.md, docs/platform/what-is-tizen/overview.md, docs/platform/what-is-tizen/versions/tizen-5-0-m2.md, docs/platform/what-is-tizen/versions/tizen-5-5-m2.md
I update ToC for 
1) "add tizen5.0 for what is tizen"
https://github.com/Samsung/tizen-docs/pull/970 (will be merged)
and 
2) "add tizen5.5 for what is tizen" (merged)
=> update TOC for what is Tizen 5.0 & 5.5

docs/application/dotnet/get-started/nui/quickstart.md, docs/application/native/get-started/mobile/first-app.md, docs/application/native/get-started/wearable-watch/first-app-watch.md, docs/application/native/get-started/wearable-widget/first-app-widget.md, docs/application/native/get-started/wearable/first-app.md, docs/application/web/get-started/mobile/first-app.md, docs/application/web/get-started/tv/first-app.md, docs/application/web/get-started/tv/first-samsung-tv-app.md, docs/application/web/get-started/wearable-watch/first-app-watch.md, docs/application/web/get-started/wearable-widget/first-app-widget.md, docs/application/web/get-started/wearable/first-app.md
New Tizen custom markdowns were added so I changed the alert style as the new style.
- Reference: PR #989
=> Change alert style

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
Add Bluetooth features
- ACR-897, ACR-1105, ACR-1106, ACR-1107
=> Add features for Bluetooth APIs

docs/application/native/guides/location-sensors/device-sensors.md, docs/application/native/tutorials/feature/app-sensor-accelerator.md, docs/application/native/tutorials/feature/app-sensor-proximity.md
ACR : ACR-1481
Signed-off-by: Boram Bae <boram21.bae@samsung.com>
=> [ACR-1481] Update document according to latest sensor APIs

docs/application/web/api/6.0/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/6.0/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/6.0/device_api/wearable/tizen/mediacontroller.html, docs/application/web/guides/multimedia/media-controller.md
[ACR]
https://code.sec.samsung.net/jira/browse/TWDAPI-249
http://suprem.sec.samsung.net/jira/browse/TWDAPI-245
http://suprem.sec.samsung.net/jira/browse/TWDAPI-246
http://suprem.sec.samsung.net/jira/browse/TWDAPI-247
http://suprem.sec.samsung.net/jira/browse/TWDAPI-248
http://suprem.sec.samsung.net/jira/browse/TWDAPI-239
=> [6.0][mediacontroller] refactor module and add new methods for playlists

docs/application/native/tutorials/details/native-removed-history.md
=> Add new removed functions

docs/application/dotnet/guides/multimedia/audio.md
Update description for the previous added methods.
ACR: TCSACR-182
=> Update audio.md of dotnet API

docs/iot/api/overview.md, docs/iot/toc_all.md
Added overview page for IoT API Reference
=> Add overview page for IoT API Reference

docs/application/toc_all.md
=> Fix broken links

docs/application/native/guides/multimedia/camera.md
- ACR: ACR-1487
- Replace specific format list by enumeration and link.
Signed-off-by: Jeongmo Yang <jm80.yang@samsung.com>
=> [ACR-1487] Update camera guide for supported pixel format

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
Signed-off-by: Inki Dae <inki.dae@samsung.com>
- ACR: ACR-918
=> [ACR-918] Add CPU key features

docs/application/dotnet/guides/connectivity/bluetooth.md
Update Bluetooth guide
Signed-off-by: Wootak Jung <wootak.jung@samsung.com>
=> [Bluetooth][TCSACR-301] Update Bluetooth guide

docs/application/vscode-ext/dotnet.md, docs/application/vscode-ext/index.md, docs/application/vscode-ext/web.md
Hello @journey2w and @mijin85cho,
I have updated the files under Visual Studio Code Extension to reflect the following:
- All headings have been modified to sentence case
- All headings have been modified to verb form (wherever applicable)
- All Notes have been modified to reflect the latest tag
- All links have been checked 
Please find attached the excel sheet with the link and detailed modification.
[Tizen_Docs_Style_Update.xlsx](https://github.com/Samsung/tizen-docs/files/4265246/Tizen_Docs_Style_Update.xlsx)
Please let me know if this is what is expected, meanwhile, I will continue with other files.
=> Style Update: VS Code Ext

docs/platform/get-started/git-repo-structure.md
Added platform source URLs to improve usability
=> Add platform source URLs

docs/application/native/guides/security/security-tip.md
- Update native security-tip for communicating between applications
=> Update native security-tip for communicating between applications

docs/application/dotnet/guides/nui/nui-components/Button.md, docs/application/dotnet/guides/nui/nui-components/Loading.md, docs/application/dotnet/guides/nui/nui-components/Popup.md, docs/application/dotnet/guides/nui/nui-components/Progress.md, docs/application/dotnet/guides/nui/nui-components/Scrollbar.md, docs/application/dotnet/guides/nui/nui-components/Slider.md, docs/application/dotnet/guides/nui/nui-components/Switch.md, docs/application/dotnet/guides/nui/nui-components/Tab.md, docs/application/dotnet/guides/nui/nui-components/Toast.md
1. Add style related apis guide
- ACR: ACR-307
=> [NUI][ACR-307] Add style related apis guide

docs/application/dotnet/samples/system/overview.md
Add the http link of newly approved apps:
- Level
- Pedometer
- SquatCounter
=> Add new C# Sample of 2020 Mar

docs/application/web/api/6.0/device_api/tv/index.html, docs/application/web/api/6.0/device_api/tv/index.xml, docs/application/web/api/6.0/device_api/tv/tizen/bluetooth.html, docs/application/web/api/6.0/index.htm
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-253
=> [TV] Added bluetooth module

docs/application/native/guides/device/system.md
Signed-off-by: jinwang.an <jinwang.an@samsung.com>
- ACR: ACR-1407
=> Update input.rotating_bezel.virtual feature

docs/application/web/api/6.0/device_api/mobile/index.xml, docs/application/web/api/6.0/device_api/wearable/index.xml
* index.xml files were just copied from 5.5 - updated their content
=> [6.0] Updated index.xml files

docs/application/tizen-studio/setup/prerequisites.md
Update prerequisites for JDK requirement
=> Update prerequisites for JDK requirement

docs/application/tizen-studio/index.md
=> Update Tizen Studio index to 3.7

docs/application/tizen-studio/release-notes/3-7-release-notes.md, docs/application/tizen-studio/setup/prerequisites.md
Fix typos in Tizen Studio to prepare Tizen Studio 3.7 release
=> Fix Typos in Tizen Studio

docs/application/tizen-studio/setup/prerequisites.md
- Change plural to singular.
- Add Registered trademark symbol to Intel.
(Reference: https://www.intel.com/content/www/us/en/support/articles/000005486/processors.html)
=> Update minor changes

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
=> [ACR-1407] Rotating bezel virtual at app-filtering.md

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
Added description of new API feature (INM).
ACR: ACR-1250
=> [ACR-1250] Add a new feature for INM

docs/application/web/api/6.0/device_api/mobile/index.html, docs/application/web/api/6.0/device_api/mobile/index.xml, docs/application/web/api/6.0/device_api/mobile/tizen/bookmark.html, docs/application/web/guides/personal/bookmarks.md
Whole module deprecation for mobile profile.
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-257
* updated bookmark.html
* updated index.html
* updated index.xml
=> [6.0][WebAPI] Deprecation of Bookmark module

docs/application/dotnet/guides/alarm/alarms.md
- [Tizen.Applications.Alarm][TCSACR-309] update guide for create alarm
- ACR: TCSACR-309
=> [Tizen.Applications.Alarm][TCSACR-309] update guide for create alarm

docs/application/tizen-studio/release-notes/3-1-release-notes.md, docs/application/tizen-studio/release-notes/3-2-release-notes.md, docs/application/tizen-studio/release-notes/3-3-release-notes.md, docs/application/tizen-studio/release-notes/3-5-release-notes.md, docs/application/tizen-studio/release-notes/3-6-release-notes.md, docs/application/tizen-studio/release-notes/3-7-release-notes.md
Fixed MacOs to macOS in release notes (3.1 to 3.7)
=> Fixing typos in release notes

docs/application/native/guides/device/system.md, docs/application/native/guides/location-sensors/device-sensors.md, docs/application/native/tutorials/details/app-filtering.md
ACR : ACR-1531
Signed-off-by: Boram Bae <boram21.bae@samsung.com>
=> [ACR-1531] Update sensor guide with new feature

docs/application/web/api/6.0/device_api/tv/tizen/tvinfo.html
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-260
=> [tvinfo] Add CAPTION_STYLE_KEY to getCaptionOptions().

docs/application/native/guides/device/battery-monitor.md
For instance,
- Modify Documentation w.r.t. new APIs 
- Change API names and signatures
- Remove outdated information
For instance,
- ACR: ACR-1533
- LINK: https://code.sec.samsung.net/jira/browse/ACR-1533
=> [ACR-1533] Update Battery Monitor Guide

docs/platform/release-notes/tizen-2-4.md
Remove download old patches URL requested by Tizen Studio team.
=> Remove download old patches URL

docs/application/dotnet/guides/connectivity/webview.md
- Update Tizen.WebView guide
- ACR: TCSACR-316
=> [TCSACR-316] Update Tizen.WebView guide

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
Signed-off-by: sungrae jo <seongrae.jo@samsung.com>
=> Add description of voice control manager feature.

docs/application/dotnet/guides/location-sensors/device-sensors.md
Add guide for auto-rotation sensor.
Signed-off-by: MuHong Byun <mh.byun@samsung.com>
Update device-sensors.md ( Add autoration sensor)
API Changes
TCSACR : TCSACR-297(https://code.sec.samsung.net/jira/browse/TCSACR-297)
=> [Tizen.Sensor][TCSACR-297] guide for auto-rotation sensor

docs/platform/release-notes/tizen-6-0-m1.md, docs/platform/toc_all.md
tizen 6.0 m1 release note initial review request
=> Tizen 6.0 M1 Release Notes

docs/platform/release-notes/tizen-6-0-m1.md
- Remove a weird special character in the first line.
- Change DOS format to Linux format.
=> Add release details to Tizen 6.0 M1 Release Notes

docs/application/web/api/6.0/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/6.0/device_api/wearable/tizen/humanactivitymonitor.html
https://code.sec.samsung.net/jira/browse/TWDAPI-262
=> [6.0] Deprecate STRESS_MONITOR

docs/application/web/api/5.5/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/5.5/device_api/wearable/tizen/humanactivitymonitor.html
https://code.sec.samsung.net/jira/browse/TWDAPI-262
=> [5.5] Deprecate STRESS_MONITOR

docs/application/dotnet/guides/location-sensors/device-sensors.md
Add guide for following batched type sensor.
* Heart Rate Monitor Batch Sensor, Heart Rate Monitor LED Green Batch Sensor
Signed-off-by: MuHong Byun <mh.byun@samsung.com>
Update device-sensors.md
- TCSACR-313 ( https://code.sec.samsung.net/jira/browse/TCSACR-313 )
=> [Tizen.Sensor][TCSACR-313] guide for batched type sensor

docs/menu.yaml
GNB settings by YAML file
N/A
N/A
=> Add menu.yaml

docs/application/tizen-studio/native-tools/manifest-text-editor.md
Add description of dependency element at Manifest Text Editor page
N/A
N/A
=> Add description of dependency element at Manifest Text Editor page

docs/application/dotnet/guides/security/privilege.md
Signed-off-by: Yunjin Lee <yunjin-.lee@samsung.com>
Remove guide for removed method Tizen.Security.GetPrivacyPrivilegeStatus().
- ACR: TCSACR-320
=> [Tizen.Security][TCSACR-320] Remove guide for removed API

docs/application/dotnet/guides/nui/NUIsetup/animation-hello-world-tutorial.cs, docs/application/dotnet/guides/nui/nui-example-code/animation-hello-world-tutorial.cs
UIComponents are deprecated, replace with NUI.Components
=> [NUI] Replace NUI.UIComponents with NUI.Components

docs/application/web/api/6.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/6.0/device_api/tv/tizen/bluetooth.html, docs/application/web/api/6.0/device_api/wearable/tizen/bluetooth.html
* List of related ACRs:
https://code.sec.samsung.net/jira/browse/TWDAPI-255
https://code.sec.samsung.net/jira/browse/TWDAPI-259
https://code.sec.samsung.net/jira/browse/TWDAPI-256
https://code.sec.samsung.net/jira/browse/TWDAPI-258
* some fixes in existing code examples
* fixed some missing examples
As currently Bluetooth API is under a development of adding more features, guides for these 4 ACRs will be added later together with next ACRs.
=> [Bluetooth] Added content related to ACRs

docs/application/web/api/2.3.2/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/2.4/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/3.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/3.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/4.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/4.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/5.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/5.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/5.5/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/5.5/device_api/wearable/tizen/bluetooth.html
* fixed few code examples
* fixed/added few missing descriptions
* removed few descriptions related to deprecated features already
removed from API (e.g. turnOn/Off in 5.5)
* fixed wrong spaces inside html tags
=> [Bluetooth] Fixes in API reference

docs/application/get-started/mobile.md, docs/application/get-started/tv.md, docs/application/get-started/wearable.md
Updated content for:
- mobile.md 
- tv.md
- wearable.md
For images and design reference, see PR: #704
=> Updating Get Started files

docs/application/native/get-started/overview.md
Updated content for the overview.md file.
For images and design reference, see #708
=> Updating Native Overview file

docs/application/web/get-started/overview.md
Updated content for the overview.md file.
For images and design reference, see #710
=> Updating Web Overview file

docs/application/dotnet/get-started/overview.md
Updated content for the overview.md file.
For images and design reference, see #709
=> Updating .NET Overview file

docs/application/dotnet/samples/location/overview.md, docs/application/dotnet/samples/system/overview.md
Adds application download link
- GestureSensor
- UltraViolet
- Workout
=> Adds application download link

docs/application/native/guides/ui/dali/capture.md, docs/application/toc_all.md
Add new guide document for Dali::Capture
- Dali::Capture is newly added to the mobile profile.
- This document contain how to capture current scene.
- This document contain how to use the result of capture
- ACR: ACR-1552, ACR-1553
=> Add new guide document for Dali::Capture

docs/application/dotnet/guides/nui/text.md
I changed the sample code.
Added description of default value.
=> Updating text guide

docs/application/web/api/6.0/device_api/mobile/tizen/cordova/events.html, docs/application/web/api/6.0/device_api/mobile/tizen/cordova/networkInformation.html, docs/application/web/api/6.0/device_api/mobile/tizen/inputdevice.html, docs/application/web/api/6.0/device_api/mobile/tizen/iotcon.html, docs/application/web/api/6.0/device_api/mobile/tizen/nfc.html, docs/application/web/api/6.0/device_api/mobile/tizen/tizen.html, docs/application/web/api/6.0/device_api/tv/tizen/cordova/events.html, docs/application/web/api/6.0/device_api/tv/tizen/cordova/networkInformation.html, docs/application/web/api/6.0/device_api/tv/tizen/iotcon.html, docs/application/web/api/6.0/device_api/tv/tizen/tizen.html, docs/application/web/api/6.0/device_api/wearable/tizen/cordova/events.html, docs/application/web/api/6.0/device_api/wearable/tizen/cordova/networkInformation.html, docs/application/web/api/6.0/device_api/wearable/tizen/inputdevice.html, docs/application/web/api/6.0/device_api/wearable/tizen/iotcon.html, docs/application/web/api/6.0/device_api/wearable/tizen/nfc.html, docs/application/web/api/6.0/device_api/wearable/tizen/tizen.html
https://github.com/Samsung/tizen-docs/issues/1167
[Fixed issues]
- provide valid links
- added missing sections to cordova API reference
[Ignored issue]
- cordova/console.ewidl (link to deprecated page) was left on purpose. The
deprecated page is still a 'source' for this documentation
Issues outside web-device-api were not fixed.
=> [WebDeviceAPI] Fix for issues reported in issue #1167

docs/application/features/feature.md, docs/application/native/guides/device/system.md
Add missing description about ui_service.sticker feature
=> Add missing description about ui_service.sticker feature

docs/application/native/guides/device/system.md, docs/application/native/guides/location-sensors/device-sensors.md, docs/application/native/tutorials/details/app-filtering.md
`http://tizen.org/feature/sensor.heart_rate_monitor.batch` and
`http://tizen.org/feature/sensor.heart_rate_monitor.led_green.batch` were deleted requested by MCD.
They will be rollbacked someday.
- Related PR: #1083
Signed-off-by: Boram Bae <boram21.bae@samsung.com>
=> Revert some sensor guide for a while

docs/application/native/guides/text-input/multi-assistant.md, docs/application/native/guides/text-input/overview.md, docs/application/toc_all.md
- Add new document for developing voice assistant applications based on multi-assistant framework.
- ACR: ACR-1455
=> [ACR-1455] Add multi-assistant development guide

docs/application/native/guides/machine-learning/machine-learning-inference.md
- Newly add Custom Filter API section and its sample code
- Newly add an element-wise control function to manipulate its properties.
- https://code.sec.samsung.net/jira/browse/ACR-1571
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>
* Fix the omitted 3 comments that @nawab-samsung mentioned.
* Use **filter** instead of _filter_.
* Update the example code for the Tensor dimension (i.e. `dim`).
* Fix the omitted items
* Update the doc as @nawab-samsung  mentioned.
* First draft
=> [Machine-learning][ACR-1571] Add document for new Machine Learning API

docs/application/web/api/6.0/device_api/mobile/tizen/metadata.html, docs/application/web/api/6.0/device_api/tv/tizen/metadata.html, docs/application/web/api/6.0/device_api/wearable/tizen/metadata.html
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-265
=> [Metadata] Added missing error type

docs/application/web/api/3.0/device_api/tv/tizen/systeminfo.html, docs/application/web/api/4.0/device_api/tv/tizen/systeminfo.html, docs/application/web/api/5.0/device_api/tv/tizen/systeminfo.html, docs/application/web/api/5.5/device_api/tv/tizen/systeminfo.html
Documentation updated to match implementation.
Signed-off-by: Rafal Walczyna <r.walczyna@samsung.com>
=> [WebAPI][SystemInfo] Update docs for TV

docs/iot/guides/update-control-api.md
- Current update_get_property usage example is wrong (causing segmentation fault), so fixed it.
- No related bug
- Non ACR
=> Fix update control docs

docs/platform/release-notes/tizen-5-5-m3.md, docs/platform/toc_all.md
Initial version of Tizen 5.5 Public M3 Release Note
=> Tizen 5.5 Public M3 Release Note

docs/application/native/guides/device/battery-monitor.md
Tizen 5.5 M3 is released today, 
so I merge the tizen_5.5_m3_release branch into master branch to push to docs.tizen.org.
=> Merge Tizen 5.5 m3 prepare branch into master

docs/platform/release-notes/tizen-5-5-m1.md, docs/platform/release-notes/tizen-5-5-m3.md, docs/platform/release-notes/tizen-6-0-m1.md
- Added release details to Tizen 5.5 M3 Release Notes.
- Applied for the same style as other release notes.
- Changed DOS format to UNIX format.
=> Add release details to Tizen 5.5 M3 Release Notes

docs/application/dotnet/tutorials/sec-privileges.md, docs/application/native/tutorials/details/sec-privileges.md
- New privilege http://tizen.org/privilege/network.route was added for
Native and dotnet application by following ACRs:
- https://code.sec.samsung.net/jira/browse/ACR-1586
- https://code.sec.samsung.net/jira/browse/TCSACR-360
=> Add new privilege: network.route

docs/application/native/guides/app-management/tidl.md
- Add option messages
- "-b" option and "-t" option are added.
ACR: ACR-1587
TCSACR: TCSACR-362
=> [TIDL][ACR-1587/TCSACR-362] Add option messages

docs/application/tizen-studio/setup/prerequisites.md
Update the wrong working window version in Tizen Studio prerequisites page.
https://github.com/Samsung/tizen-docs/issues/1222
=> fix wrong version info

docs/application/dotnet/guides/machine-learning/pipeline.md
* Newly add Custom Filter API documentation.
* Newly add an element-wise control function documentation to manipulate its properties.
* TCSACR-365
* Fix the minor thing that @mijin85cho mentioned.
* Update the doc as @annie-samsung mentioned.
* First draft
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>
=> [Machine-learning][TCSACR-365] Add document for CustomFilter class and getter/setter of NodeInfo class

docs/menu.yaml
=> Remove IoT from GNB

docs/application/native/guides/multimedia/media-controller.md
[ACR-1561][capi-media-controller][Add]
Add new attributes for playback and result codes in media-controller guide
=> [ACR-1561] Add new playback state attributes and the result code attributes

docs/menu.yaml
Merge to live branch from master branch.
- https://github.com/Samsung/tizen-docs/pull/1240 (Remove IoT from GNB)
=> Synchronize two branches: master and live

docs/application/dotnet/guides/nui/tableview.md, docs/application/dotnet/guides/nui/text.md
- Fixed wrong variable types in TableView guide - example wouldn't build
- Changed PropertyValues in Text guide
- Issue #1229
=> [NUI] Text and TableView guides code examples fixes

docs/application/dotnet/guides/nui/flexcontainer.md, docs/application/dotnet/guides/nui/nui-components/Tab.md, docs/application/dotnet/guides/nui/nui-components/Toast.md, docs/application/dotnet/guides/nui/tableview.md, docs/application/dotnet/guides/nui/text.md
@Seoyeon2Kim mentioned in #1226 that I don't need to fix deprecated code, but I've done it before this message, so I decided to share deprecated code fix as well.
- Fixed FlexContainer example, now it will be displayed properly
- Fixed errors of Tab example and changed PointSize to smaller value
- Fixed Toast example, now it will be displayed properly
- Fixed errors of TableView example and add text to TextLabels - thanks that cells will be visible
- Fixed errors of Text examples
- Fixed TextField example, now placeholders and TextField will be displayed properly
- Issue #1226
=> NUI guides fix

docs/application/web/api/6.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/6.0/device_api/tv/tizen/bluetooth.html, docs/application/web/api/6.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/tutorials/app-filtering.md
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-270
=> [Bluetooth] Added missing description about needed feature

docs/application/web/api/2.3.2/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/2.4/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/2.4/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/3.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/3.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/4.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/4.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/5.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/5.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/5.5/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/5.5/device_api/wearable/tizen/bluetooth.html
* Bluetooth - fixed the described exception, previous type was invalid
* HAM - removed unnecessary remark
=> [Bluetooth][HAM] Fixed descriptions

docs/application/dotnet/tutorials/app-filtering.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
- ACR:  TSACR-298
=> [NUI][TCSACR-298] Add feature to support MultiWindow

docs/application/web/api/5.5/device_api/mobile/tizen/power.html, docs/application/web/api/5.5/device_api/wearable/tizen/power.html
Related native and C# changes:
https://review.tizen.org/gerrit/#/c/platform/core/api/device/+/245276/ (tizen5.5 native api)
https://review.tizen.org/gerrit/#/c/platform/core/api/device/+/245323/ (tizen6.0 native api)
https://github.com/Samsung/TizenFX/pull/2084 (tizen 5.5 C# api)
https://github.com/Samsung/TizenFX/pull/2085 (tizen 6.0 C# api)
=> [Power] Added remark about possibility of not supporting DIM state

docs/application/dotnet/guides/nui/layer.md
1. Fixed non compilable code example
2. Extended Depth parameter description
=> [NUI][Layer] Updated layers description.

docs/application/dotnet/guides/nui/text.md
Signed-off-by: Seoyeon Kim <seoyeon2.kim@samsung.com>
- Update NUI Text guide.
- To use TextField Input properties, some signals should be used together.
Added this into the guide.
- N/A
- N/A
=> [NUI] Update the guide of text Input properties

docs/application/dotnet/guides/nui/nui-components/Switch.md
Add EventHandler<SelectedChangedEventArgs> SelectedChanged event in
Switch class.
Deprecate Switch.SelectEventArgs class.
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [NUI][TCSACR-347] Add and deprecate Switch EventArgs classes

docs/application/dotnet/guides/nui/text.md
add description of how to use encoded characters and using encoded entities in MarkupText
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [NUI-Text] update to include text encoding

docs/application/native/guides/index.md, docs/application/native/guides/text-input/capi-ui-gesture.md, docs/application/native/guides/text-input/overview.md, docs/application/toc_all.md
Signed-off-by: sooyeon.kim <sooyeon.kim@samsung.com>
[ACR-1585][gesture] Add a new guide for Gesture
=> [ACR-1585][gesture] Add a new guide for Gesture

docs/application/dotnet/guides/nui/styling-controls-with-JSON.md
- Added StyleManager usage example,
=> [NUI][StyleManager] Added C# code example to existing docs.

docs/platform/release-notes/tizen-6-0-m2.md
Added release details to Tizen 6.0 M2 Release Notes
=> Add release details to Tizen 6.0 M2 Release Notes

docs/application/toc_all.md
Added 6.0 Native API Reference menus on LNB.
=> Add Native > API Reference > 6.0 on LNB

docs/application/tizen-studio/rt-ide/overview.md, docs/application/tizen-studio/setup/prerequisites.md
- Update Tizen Studio 4.0 support version.
- Tizen RT IDE will be deprecated from Tizen Studio 4.1.
So a note to inform is added.
=> Update Tizen Studio 4.0 Information (Prerequisites, RT IDE)

docs/application/vstools-mac/overview.md
The version needs to be changed from 8.2 to 8.6 as suggested by @manishtr
=> change the version from (8.2 to 8.6)

docs/application/tizen-studio/setup/prerequisites.md
Changed ugly layout of the Emulator Requirements table.
=> Change ugly table layout

docs/platform/what-is-tizen/overview.md, docs/platform/what-is-tizen/profiles/wearable.md
Fixed updated contents and wrong model name.
=> Change outdated contents and wrong model name

docs/application/tizen-studio/index.md, docs/application/tizen-studio/native-tools/edc-editor.md, docs/application/tizen-studio/native-tools/ui-builder/ui-builder.md, docs/application/tizen-studio/setup/prerequisites.md
Related with Tizen Studio 4.0 release : 
- Remove welcome message including version information in Tizen Studio index page
- Add deprecated notes to UI Builder and EDC Editor.
- Update supported version information for driver
=> Update Tizen Studio's version info and deprecated pages

docs/application/vstools-mac/overview.md
With @sangwook96-lee's request, 
the supported version for VS for mac for tizen 1.3 is updated.
=> Update support version of VS for mac for tizen 1.3

docs/platform/what-is-tizen/overview.md
Added IoT Profile to platform overview.
=> Add IoT Profile to platform overview

docs/application/web/api/3.0/device_api/mobile/tizen/cordova/console.html, docs/application/web/api/3.0/device_api/mobile/tizen/cordova/globalization.html, docs/application/web/api/3.0/device_api/tv/tizen/cordova/console.html, docs/application/web/api/3.0/device_api/tv/tizen/cordova/globalization.html, docs/application/web/api/3.0/device_api/wearable/tizen/cordova/console.html, docs/application/web/api/3.0/device_api/wearable/tizen/cordova/globalization.html, docs/application/web/api/4.0/device_api/mobile/tizen/cordova/console.html, docs/application/web/api/4.0/device_api/mobile/tizen/cordova/globalization.html, docs/application/web/api/4.0/device_api/tv/tizen/cordova/console.html, docs/application/web/api/4.0/device_api/tv/tizen/cordova/globalization.html, docs/application/web/api/4.0/device_api/wearable/tizen/cordova/console.html, docs/application/web/api/4.0/device_api/wearable/tizen/cordova/globalization.html, docs/application/web/api/5.0/device_api/mobile/tizen/cordova/console.html, docs/application/web/api/5.0/device_api/mobile/tizen/cordova/globalization.html, docs/application/web/api/5.0/device_api/tv/tizen/cordova/console.html, docs/application/web/api/5.0/device_api/tv/tizen/cordova/globalization.html, docs/application/web/api/5.0/device_api/wearable/tizen/cordova/console.html, docs/application/web/api/5.0/device_api/wearable/tizen/cordova/globalization.html, docs/application/web/api/5.5/device_api/mobile/tizen/cordova/console.html, docs/application/web/api/5.5/device_api/mobile/tizen/cordova/globalization.html, docs/application/web/api/5.5/device_api/tv/tizen/cordova/console.html, docs/application/web/api/5.5/device_api/tv/tizen/cordova/globalization.html, docs/application/web/api/5.5/device_api/wearable/tizen/cordova/console.html, docs/application/web/api/5.5/device_api/wearable/tizen/cordova/globalization.html, docs/application/web/api/6.0/device_api/mobile/tizen/cordova/console.html, docs/application/web/api/6.0/device_api/mobile/tizen/cordova/globalization.html, docs/application/web/api/6.0/device_api/tv/tizen/cordova/console.html, docs/application/web/api/6.0/device_api/tv/tizen/cordova/globalization.html, docs/application/web/api/6.0/device_api/wearable/tizen/cordova/console.html, docs/application/web/api/6.0/device_api/wearable/tizen/cordova/globalization.html
Fixed beginning of a paragraph to capital letter in Cordova API.
=> [Cordova] Fix to capital letter

docs/platform/what-is-tizen/overview.md
Add update to https://github.com/Samsung/tizen-docs/pull/1322 : "Add IoT Profile to platform overview"
- Issue #1326
=> Fix number of profiles in overview

docs/application/dotnet/guides/nui/nui-components/Button.md, docs/application/dotnet/guides/nui/nui-components/Loading.md, docs/application/dotnet/guides/nui/nui-components/Popup.md, docs/application/dotnet/guides/nui/nui-components/Progress.md, docs/application/dotnet/guides/nui/nui-components/Slider.md, docs/application/dotnet/guides/nui/nui-components/Switch.md, docs/application/dotnet/guides/nui/nui-components/Tab.md, docs/application/dotnet/guides/nui/nui-components/Toast.md
Added sections about namespace and, if deprected, deprected note to all pages in guides/nui/nui-components.
Changes allow easier use and understand by third party developers.
=> Guides/NUI/Components: Added namespace info and deprected note

docs/application/native/guides/app-management/overview.md, docs/application/native/guides/app-management/widget-service.md, docs/application/toc_all.md
Signed-off-by: SukHyung, Kang <shine.kang@samsung.com>
[ACR-1541] Add widget service guide
=> [ACR-1541] Add widget service guide

docs/application/dotnet/index.md
NUI is the main GUI feature provided by TizenFX. It is a big part of TizenFX and I think it should be mentioned in overview page 
to indicate possbility to use it as a main GUI framework for 3rd party developers as soon as possible (in the main page).
=> [dotnet] Add NUI in TizenFX section

docs/application/tizen-studio/setup/openjdk.md
executing provided command causes "zsh: bad assignment"
- Fix broken command for mac
=> Fix command for mac in openjdk.md

docs/application/dotnet/guides/nui/resources.md
Added two common use cases for handle image resources.
=> [dotnet][nui][resources] Updated resources docs

docs/platform/developing/flashing-rpi.md
PR #1354 merged the old commits so some commits were already applied on the master branch.
I couldn't do rebase and merge on #1362 on the Web because its base was PR #1354.
I changed the HEAD of master branch to the latest commit after removing all commit on PR #1354.
I might rebase and merge this PR after reviewers approve this.
- Reference: PR #1354
=> Cherrypick PR1354

docs/application/tizen-studio/rt-ide/get-started/create.md, docs/application/tizen-studio/rt-ide/get-started/debug.md, docs/application/tizen-studio/rt-ide/get-started/flash.md, docs/application/tizen-studio/rt-ide/get-started/install.md, docs/application/tizen-studio/rt-ide/get-started/overview.md, docs/application/tizen-studio/rt-ide/get-started/terminal.md, docs/application/tizen-studio/rt-ide/overview.md, docs/application/toc_all.md
Deprecate RT IDE documentation as per the conclusion from the discussion.
=> Deprecate RT IDE content as per suggestions

docs/application/tizen-studio/release-notes/4-1-release-notes.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Update Deprecated info

docs/application/dotnet/guides/nui/nui-components/Notification.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [NUI] Guide for Notification enhancement

docs/application/dotnet/guides/nui/view.md
-Updated NUI View guide to be more readable and to better explain basic concepts (especially relationship between ParentOrigin and PivotPoint)
=> [NUI] View Guide

docs/application/dotnet/guides/nui/window.md
=> [NUI][Window] Fix NUI Window guide

docs/application/native/guides/app-management/app-controls.md
- Add a missing double quotation mark
=> Add a missing double quotation mark

docs/application/native/guides/device/system.md, docs/application/native/guides/location-sensors/device-sensors.md, docs/application/native/tutorials/details/app-filtering.md
* This reverts commit d3c72a20a9e0385e5508e838f9ec5b216577fc56.
=> Revise sensor guide for Tizen Studio 4.1

docs/application/dotnet/guides/app-management/data-control.md
Added some changes that I think make guide more usable and useful.
- Mainly, I added working example of `tizen-manifest.xml`, previous had missing fields and was unusable if user didn't know how to fill them
- Rephrased some things
=> [.NET] Data Control guide tweaks

docs/application/native/guides/app-management/app-controls.md
Add a missing double quotation mark (#1394)
This PR was raised for tizen_6.0_prepare branch, and I merged it by mistake, hence cherry picking and merging to master branch.
=> Adding the file from PR #1394 to master branch

docs/application/vscode-ext/index.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Update Prerequisites VSCode EXT

docs/application/web/api/6.5/device_api/tv/tizen/tvinfo.html
ACR: https://code.sec.samsung.net/jira/browse/TWDAPI-272
=> [6.5] [TVInfo] Adding caption translucent types

docs/application/dotnet/guides/nui/styling-controls-with-xaml.md, docs/application/toc_all.md
Added Xaml Theme and Theme manager docs. Xaml theme manager is a new method introduced in Tizen 6.5 to implement NUI control style.
=> [NUI] Introduce XAML themes description.

docs/application/web/api/6.5/device_api/mobile/tizen/metadata.html, docs/application/web/api/6.5/device_api/tv/tizen/metadata.html, docs/application/web/api/6.5/device_api/wearable/tizen/metadata.html, docs/application/web/guides/multimedia/metadata.md
[6.5] [Metadata] Getting complex-type metadata - adding API reference
[6.5] [Metadata] Getting complex-type metadata - adding guide
ACR: https://code.sec.samsung.net/jira/browse/TWDAPI-271
=> [6.5] [Metadata] Getting complex-type metadata

docs/application/web/api/6.5/device_api/mobile/tizen/metadata.html, docs/application/web/api/6.5/device_api/tv/tizen/metadata.html, docs/application/web/api/6.5/device_api/wearable/tizen/metadata.html
Fixed type of timestamp member of MetadataSyncLyrics
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-271
=> [6.5] [Metadata] Fixed type of timestamp

docs/application/dotnet/guides/security/tee-client.md, docs/application/web/guides/security/tee-client.md
Mark all TEEC APIs as deprecated since Tizen 6.5
TCSACR-405 TWDAPI-275
=> [TCSACR-405/TWDAPI-275] Mark all TEEC APIs as deprecated since Tizen 6.5

docs/application/index.md
VS for mac and VS code image and description are exchanged.
Signed-off-by: Kwang Son <k.son@samsung.com>
=> Fix wrong image and description

docs/application/dotnet/samples/content/overview.md, docs/application/dotnet/samples/ui/overview.md
Added one more folder depth for NUI Samples - /NUI/ was added to previous link.
=> Update the github link of NUI samples

docs/application/native/guides/machine-learning/machine-learning-inference.md
- Add a description for tensor_if element and usage example.
- https://code.sec.samsung.net/jira/browse/ACR-1612
Signed-off-by: Gichan Jang <gichan2.jang@samsung.com>
=> [Machine-learning][ACR-1612] Add tensor_if description

docs/application/dotnet/samples/account/overview.md, docs/application/dotnet/samples/appfw/overview.md, docs/application/dotnet/samples/content/overview.md, docs/application/dotnet/samples/context/overview.md, docs/application/dotnet/samples/general/overview.md, docs/application/dotnet/samples/location/overview.md, docs/application/dotnet/samples/machinelearning/overview.md, docs/application/dotnet/samples/messaging/overview.md, docs/application/dotnet/samples/multimedia/overview.md, docs/application/dotnet/samples/network/overview.md, docs/application/dotnet/samples/security/overview.md, docs/application/dotnet/samples/social/overview.md, docs/application/dotnet/samples/system/overview.md, docs/application/dotnet/samples/telephony/overview.md, docs/application/dotnet/samples/ui/overview.md, docs/application/dotnet/samples/uix/overview.md, docs/application/dotnet/samples/watch/overview.md
Quick fix for latest repository path.
AS-IS
/tree/master/Mobile/Apps
/tree/master/Wearable/Apps
/tree/master/TV/Apps
TO-BE
/tree/master/Mobile/**Xamarin.Forms**/Apps
/tree/master/Wearable/**Xamarin.Forms**/Apps
/tree/master/TV/**Xamarin.Forms**/Apps
=> Update the repository link of xamarin forms apps

docs/application/native/guides/connectivity/nsd.md
Fix wrong API names and errors.
=> [NSD] Fix wrong API names in Network Service Discovery Guides

docs/application/dotnet/guides/app-management/component-port.md, docs/application/dotnet/guides/app-management/overview.md, docs/application/toc_all.md
Adds:
- component-port.md
- Add a new guide for ComponentPort
- ACR: TCSACR-406
=> [ComponentPort][TCSACR-406] Add a guide for ComponentPort

docs/application/dotnet/guides/nui/nui-components/ScrollableBase.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [NUI] Guide for ScrollableBase enhancement

docs/application/dotnet/guides/nui/animation.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [6.5][NUI] Fix wrong code in NUI Animation docs.

docs/application/dotnet/guides/nui/animation.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [NUI] Fix wrong code in NUI Animation docs. (#1440)

docs/application/dotnet/samples/system/overview.md
Updated github repo, instead of using "In progress"
=> Add new link for C# sample - Sensor

docs/platform/release-notes/tizen-6-5-m1.md, docs/platform/toc_all.md
Tizen 6.5 Public M1 Release Note (initial)
=> Tizen 6.5 Public M1 Release Note

docs/application/native/tutorials/details/native-removed-history.md
All video util functions are removed.
=> Add new removed functions to list

docs/platform/release-notes/tizen-6-5-m1.md
=> Tizen 6.5 m1 release notes

docs/platform/release-notes/tizen-6-0-m1.md, docs/platform/release-notes/tizen-6-5-m1.md
- Added release details.
- Converted text file format.
=> Add release details to Tizen 6.5 Release Notes

docs/application/dotnet/guides/nui/webview.md, docs/application/toc_all.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [6.5][NUI] Add guide of NUI WebView

docs/application/dotnet/samples/location/overview.md, docs/application/dotnet/samples/watch/overview.md
(M) => (T)
Added missing path : /Xamarin.Forms/
=> Fix wrong profile information for TV Maps app

docs/application/dotnet/guides/nui/ui-components.md
As a new content `WebView` is added, overview page also need to be updated.
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [6.5][NUI] Update component overview page

docs/application/native/guides/multimedia/image-edit.md
This PR is #1399 for master branch. Please review this PR.
- ACR: ACR-1595
I missed new guide of encoding animation APIs.
So I updated the guide of encoding animation, please review this new guide.
=> [ACR-1595] Add animation encoding APIs for GIF and WEBP

docs/application/tizen-studio/release-notes/4-1-1-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
[Tizen Studio] 4.1.1 release notes
=> [Tizen Studio] 4.1.1 release notes

docs/application/web/api/6.5/device_api/mobile/tizen/ml.html, docs/application/web/api/6.5/device_api/mobile/tizen/ml_single.html, docs/application/web/api/6.5/device_api/tv/tizen/ml.html, docs/application/web/api/6.5/device_api/tv/tizen/ml_single.html, docs/application/web/api/6.5/device_api/wearable/tizen/ml.html, docs/application/web/api/6.5/device_api/wearable/tizen/ml_single.html, docs/application/web/guides/machine-learning/single.md
New enum values and asynchronous invoke introduced.
[ACR] TWDAPI-277
[ACR] TWDAPI-278
Signed-off-by: Rafal Walczyna <r.walczyna@samsung.com>
=> [6.5][ML] Update MachineLearning API documentation

docs/application/dotnet/guides/nui/view.md
- Fix broken TizenFX links (2 links) reported in  issue #1488
=> NUI View guide (.NET) - TizenFX links fixed.

docs/application/native/api/iot-headed/5.5/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html, docs/application/native/api/iot-headed/6.0/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html, docs/application/native/api/iot-headless/5.5/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html, docs/application/native/api/iot-headless/6.0/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html, docs/application/native/api/mobile/5.5/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html, docs/application/native/api/mobile/6.0/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html, docs/application/native/api/wearable/5.5/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html, docs/application/native/api/wearable/6.0/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html
Added some description using remarks TAG.
=> Add additional comments for better description of battery property

docs/application/web/api/6.5/device_api/mobile/tizen/ml.html, docs/application/web/api/6.5/device_api/tv/tizen/ml.html, docs/application/web/api/6.5/device_api/wearable/tizen/ml.html
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-280
=> [ML] Renamed a SRNPU with TRIX_ENGINE

docs/application/dotnet/guides/nui/window.md
* Update window.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [6.5][NUI][ACR-436] Update document for Window (#3416)

docs/application/native/guides/app-management/tidl.md
Signed-off-by: ChangGyu Choi <uppletaste@gmail.com>
- Update TIDL document for version 1.5.0
- N/A
- Non ACR
=> [TIDL] Update TIDL docs

docs/application/web/api/6.5/device_api/mobile/tizen/se.html, docs/application/web/api/6.5/device_api/wearable/tizen/se.html
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-281
=> [6.5] Secure element extension

docs/application/tizen-studio/native-tools/rpk-package.md, docs/application/toc_all.md
=> Adding PRK Package Information

docs/application/dotnet/guides/app-management/overview.md, docs/application/dotnet/guides/app-management/widget-management.md, docs/application/dotnet/guides/index.md, docs/application/toc_all.md
Changes:
- Title was changed because widget-control suggest something that controll
widget, but widget-control is responsible for widget applications
managent like viewing installed widgets list, removing widget etc.
- Some code snippets was fixed.
=> [6.5][NET] Changed widget-control to widget-management.

docs/application/native/api/iot-headless/6.5/group__CAPI__MEDIA__FRAMEWORK.html
- added Audio I/O and Wav Player links to overview page
=> Update Iot Headless 6.5 Multimedia category

docs/application/native/tutorials/details/sec-privileges.md
Update privilege docs for Tizen 6.5 newly added privileges.
For instance,
- ACR: ACR-1610, ACR-1631, ACR-1626
=> Update 6.5 issued privileges

docs/application/dotnet/guides/user-interface/nui/window.md
The WindowType link is broken.
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Fix the broken link

docs/application/native/guides/multimedia/media-content.md
- Add description for e-book format support 
- ACR: ACR-1635, ACR-1643
=> Add description for e-book format support

docs/application/native/tutorials/details/app-filtering.md
[TCSACR-399] Add vision inference feature
Signed-off-by: Kwang Son <k.son@samsung.com>
=> [TCSACR-399] Add vision inference feature

docs/application/dotnet/guides/multimedia/media-vision.md, docs/application/dotnet/guides/multimedia/pose-detection.md, docs/application/toc_all.md
Add vision pose detection doc
Signed-off-by: Kwang Son <k.son@samsung.com>
=> [TCSACR-399] Add vision pose detection doc

docs/application/tizen-studio/release-notes/4-5-1-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
4.5.1 Tizen Studio Release Notes
=> [Tizen Studio] 4.5.1 Release Notes

docs/application/vstools/install.md
=> [VSTOOLS] Update Perquisites for VS2022

docs/application/tizen-studio/release-notes/4-5-1-release-notes.md, docs/application/toc_all.md
=> Update release date for Tizen Studio

docs/application/native/guides/app-management/tidl.md
Signed-off-by: Changgyu Choi <changyu.choi@samsung.com>
Fix merge conflict TIDL document file.
N/A
N/A
=>  [TIDL] Fix merge conflict TIDL document file.

docs/application/dotnet/guides/uix/tts.md
Add description for new API `Repeat()`
- ACR: TCSACR-477
=> [tts][TCSACR-477] Add guide for Repeat()

docs/application/native/api/iot-headed/5.0/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/iot-headed/5.5/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/iot-headed/6.0/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/iot-headed/6.5/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/mobile/5.0/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/mobile/5.5/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/mobile/6.0/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/mobile/6.5/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/wearable/5.0/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/wearable/5.5/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/wearable/6.0/group__CAPI__UIX__TTS__MODULE.html, docs/application/native/api/wearable/6.5/group__CAPI__UIX__TTS__MODULE.html
* Changed the description of tts_repeat function.
* Target: 5.0 / 5.5 / 6.0 / 6.5 Native API Reference
* ACR-1680: https://code.sec.samsung.net/jira/browse/ACR-1680
=> Update the description of tts_repeat function

docs/application/dotnet/get-started/application-filtering.md, docs/application/dotnet/guides/sensors/device-sensors.md, docs/application/native/guides/location-sensors/device-sensors.md, docs/application/native/tutorials/details/app-filtering.md
ACR-1655 : https://code.sec.samsung.net/jira/browse/ACR-1655
Add descripton and features of new sensors 
- SENSOR_ORIENTATION : orientation sensor based on rotation_vector
- SENSOR_GYROSCOPE_ORIENTATION : orientation sensor based on gyroscope_rotation_vector
- SENSOR_GEOMAGNETIC_ORIENTATION: orientation sensor based on geomagnetic_rotation_vector
=> [ACR-1655] Add descripton and features of new sensors

docs/platform/what-is-tizen/overview.md
=> Add the latest versions

docs/application/native/tutorials/details/native-removed-history.md
Native Module : UI - UI View Manager will be removed since 7.0.
To notice it, I am going to update this page
=> Adds newly removed module of Native API

docs/application/tizen-studio/tizen-core/tizen-core-cli.md
Signed-off-by: Vivek Ellur/Things Platform /SRI-Bangalore/Staff Engineer/Samsung Electronics <vivek.ellur@samsung.com>
- The documentation has been updated according to the latest Tizen-core commands.
=> [Tizen Studio] Update Tizen-Core documentation

docs/platform/developing/flashing-rpi.md
- Update the binary image names for RPI
=> Update the binary image names

docs/application/vscode-ext/index.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Update supported macOS versions

docs/platform/what-is-tizen/overview.md
This PR updates the overview page for machine learning (NNStreamer & NNTrainer)
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>
* Fix the typo: `NTrainer` -> **N**NTrainer
* Put a period at the end of a sentence
* Rebase the master branch
* Remove duplicated title `AI and Machine Learning`
* First Draft
=> [ML] Update the overview page for machine learning (NNStreamer & NNTrainer)

docs/platform/what-is-tizen/profiles/iot.md
- Fix broken links of iot api set
- Add links for developing applications and createing images sections
=> update what is tizen iot

docs/application/web/api/7.0/device_api/mobile/tizen/notification.html, docs/application/web/api/7.0/device_api/wearable/tizen/notification.html, docs/application/web/guides/notification/notification.md
Add documentation for active notifications API:
- add new type of notifications to the guide
- edit mobile and wearable HTMLs
- ACR: TWDAPI-284
=> [7.0][Web API] Add documentation for active notifications API

docs/application/web/api/7.0/device_api/mobile/tizen/notification.html, docs/application/web/api/7.0/device_api/wearable/tizen/notification.html
- fix spelling mistakes (missing articles, missing commas, etc.)
N/A
N/A
=> [7.0][Web API] Fix spelling mistakes in notifications API 

docs/application/dotnet/guides/user-interface/nui/text.md
Document the new tags and attributes in Markup.
These tags and attributes have been added to DALi.
They are explained under current Markup documentation  "Use markup styling to style TextLabel".
For instance,
- Issue #1618
=> [NUI] Document the new tags and attributes in Markup

docs/platform/developing/creating.md
- Update the Tizen 6.5 M2 URLs
=> Update the latest URLs

docs/application/native/tutorials/details/native-removed-history.md
Since 7.0, DALi module will be removed
=> Added newly removed module - DALi

docs/application/native/guides/machine-learning/machine-learning-training.md
Reverts Samsung/tizen-docs#1629
This PR has to be merged to `tizen_7.0_prepare` branch.
=> Revert "[machine-learning-training] Add sample code for get layer and descrip…"

docs/application/native/guides/machine-learning/machine-learning-inference.md, docs/application/native/guides/machine-learning/machine-learning-service.md, docs/application/native/guides/machine-learning/machine-learning-training.md, docs/application/native/guides/machine-learning/overview.md, docs/application/toc_all.md
Add machine learning service API guide documentation.
- ACR: ACR-1691
Signed-off-by: gichan <gichan2.jang@samsung.com>
=> [7.0][Machine-learning][ACR-1691] Add ml-service documentation

docs/platform/release-notes/tizen-7-0-m1.md, docs/platform/toc_all.md
Tizen 7.0 Public M1 Release Note
=> Tizen 7.0 Public M1 Release Note

docs/platform/release-notes/tizen-6-5-m1.md, docs/platform/release-notes/tizen-7-0-m1.md
Added the Release Details section to the Tizen 7.0 M1 Public Release Note.
Reference: #1631
=> Adding Release Details to Tizen 7.0 M1 Public Release Note

docs/application/dotnet/guides/multimedia/camera.md
Add description for CameraPixelFormat Vp8, Vp9 and missed Mjpeg.
- TCSACR-427
=> [TCSACR-427] Update guide for CameraPixelFormat

docs/application/dotnet/guides/multimedia/media-content.md
Update MediaContent guideline for BookInfo class
-TCSACR-439
=> [TCSACR-439] Update guide for MediaContent BookInfo

docs/application/web/guides/connectivity/download.md
- Deleted the extra space in Content Downloads guide which give the privilege to add to the config.xml. Just a simple copy-paste would break the build.
=> Fixed privilege for Content Downloads

docs/application/toc_all.md, docs/application/web/api/7.0/device_api/mobile/index.html, docs/application/web/api/7.0/device_api/mobile/index.xml, docs/application/web/api/7.0/device_api/mobile/tizen/ml.html, docs/application/web/api/7.0/device_api/mobile/tizen/ml_trainer.html, docs/application/web/api/7.0/device_api/tv/index.html, docs/application/web/api/7.0/device_api/tv/index.xml, docs/application/web/api/7.0/device_api/tv/tizen/ml.html, docs/application/web/api/7.0/device_api/tv/tizen/ml_trainer.html, docs/application/web/api/7.0/device_api/wearable/index.html, docs/application/web/api/7.0/device_api/wearable/index.xml, docs/application/web/api/7.0/device_api/wearable/tizen/ml.html, docs/application/web/api/7.0/device_api/wearable/tizen/ml_trainer.html, docs/application/web/api/toc.xml, docs/application/web/guides/machine-learning/overview.md, docs/application/web/guides/machine-learning/trainer.md
Add documentation and guide for ML Trainer API:
- add guide for ML Trainer
- add docs for ML Trainer for mobile, tv and wearable
- update index.html to show new API for mobile, tv and wearable
N/A
- ACR: TWDAPI-285
=> [7.0][Web API] Add documentation and guide for ML Trainer API

docs/application/web/api/7.0/device_api/tv/tizen/systeminfo.html
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-283
=> [WebAPI][7.0][Systeminfo] Adding editName property to VideoSourceInfo

docs/application/native/guides/multimedia/overview.md, docs/application/native/guides/multimedia/webrtc.md, docs/application/toc_all.md
=> [ACR-1637] Add webrtc doc

docs/application/web/guides/data/file-system.md
This PR was created to implement the changes that was suggested in #1584 but could not be implemented by the author.
Signed off by: omar.saeed@samsung.com
=> Update file-system.md (PR#1584 fixes)

docs/application/dotnet/get-started/hybrid-application.md
This PR was created to implement the changes that was suggested in https://github.com/Samsung/tizen-docs/pull/1648 but could not be implemented by the author.
=> Update hybrid-application.md (PR#1648 fixes)

docs/application/native/guides/multimedia/overview.md
Signed-off-by: Sangchul Lee <sc11.lee@samsung.com>
=> Revise docs/application/native/guides/multimedia/overview.md

docs/application/dotnet/learn-about-dotnet.md
This PR was created to implement the changes that was suggested in https://github.com/Samsung/tizen-docs/pull/1587 but could not be implemented by the author.
=> Update learn-about-dotnet.md (PR#1587 fixes)

docs/application/vscode-ext/index.md
This PR was created to implement changes that could not be implemented in PR:
- #1621 
Signed off by:
safir.zawad@samsung.com
=> Updated vscode-ext/index.md (PR#1621 Fixes)

docs/platform/developing/flashing-rpi.md
This PR was created to implement changes that could not be implemented in PR:
- #1613 
Signed off by: safir.zawad@samsung.com
=> Update platform/flashing-rpi.md (PR#1613 Fixes)

docs/platform/developing/creating.md
This PR was created to implement changes that could not be implemented in PR:
- #1624
Signed off by: safir.zawad@samsung.com
=> Update creating.md (PR#1624 Fixes)

docs/application/web/api/6.0/ui_fw_api/Wearable_UIComponents/wearable_checkbox.htm, docs/application/web/api/6.5/ui_fw_api/Wearable_UIComponents/wearable_checkbox.htm
Signed-off-by: singa2000 <cookie@samsung.com>
Remove the Use Sample in the wearable checkbox
Remove the Use Sample in the wearable checkbox
=> [Fix]Remove the Use example in TAU wearable checkbox

docs/application/web/api/7.0/device_api/mobile/tizen/account.html, docs/application/web/api/7.0/device_api/mobile/tizen/ml.html, docs/application/web/api/7.0/device_api/tv/tizen/account.html, docs/application/web/api/7.0/device_api/tv/tizen/ml.html, docs/application/web/api/7.0/device_api/wearable/tizen/account.html, docs/application/web/api/7.0/device_api/wearable/tizen/ml.html
* Apply fix requested here - https://github.com/Samsung/tizen-docs/pull/1656#pullrequestreview-1056756046
* Apply missed auto formatting in example
Related change applied for older API versions - https://github.com/Samsung/tizen-docs/pull/1667
=> [Web API] Apply language changes from several reviews

docs/application/dotnet/get-started/first-app.md, docs/application/dotnet/guides/app-management/application-launcher.md, docs/application/dotnet/guides/app-management/application-preference.md, docs/application/dotnet/guides/app-management/widget-viewer.md, docs/application/dotnet/guides/user-interface/nui/linear-layout.md, docs/application/dotnet/guides/user-interface/nui/nui-components/Tab.md
This PR was created to implement the changes that were suggested in https://github.com/Samsung/tizen-docs/pull/1633 but could not be implemented by the author.
=> Updated files (PR#1633 fixes)

README.md
Updated README.md file.
This PR has been created to accommodate the changes suggested on #1649.
=> Update README.md (PR#1649 fixes)

docs/application/web/guides/connectivity/download.md
This PR has been created to accomodate the changes of #1650.
=> Update download.md (PR#1650 fixes)

docs/application/native/guides/multimedia/webrtc.md
ACR: ACR-1648, ACR-1677, ACR-1678
=> Update webrtc doc

docs/application/dotnet/guides/uix/tts.md
Add guide for new APIs about service state
- ACR: TCSACR-497
=> [tts][TCSACR-497] Add guide for new APIs about service state

docs/application/native/guides/text-input/tts.md
Add guide for new APIs about service state
- ACR: ACR-1716
=> [tts][ACR-1716] Add guide for new APIs about service state

docs/platform/compliance/compliance-program.md, docs/platform/compliance/compliance-test.md, docs/platform/release-notes/tizen-2-0.md, docs/platform/release-notes/tizen-2-1.md, docs/platform/release-notes/tizen-2-2-1.md, docs/platform/release-notes/tizen-2-2.md, docs/platform/release-notes/tizen-2-3-1.md, docs/platform/release-notes/tizen-2-3-2.md, docs/platform/release-notes/tizen-2-3.md, docs/platform/release-notes/tizen-2-4.md, docs/platform/release-notes/tizen-3-0-m2.md, docs/platform/release-notes/tizen-3-0-m3.md, docs/platform/release-notes/tizen-3-0-m4.md, docs/platform/release-notes/tizen-3-0-milestones.md, docs/platform/release-notes/tizen-4-0-m1.md, docs/platform/release-notes/tizen-4-0-m2.md, docs/platform/release-notes/tizen-4-0-m3.md, docs/platform/release-notes/tizen-5-0-m1.md, docs/platform/release-notes/tizen-5-0-m2.md, docs/platform/release-notes/tizen-5-5-m1.md, docs/platform/release-notes/tizen-5-5-m2.md, docs/platform/release-notes/tizen-5-5-m3.md, docs/platform/release-notes/tizen-6-0-m1.md, docs/platform/release-notes/tizen-6-0-m2.md, docs/platform/release-notes/tizen-6-5-m1.md, docs/platform/release-notes/tizen-6-5-m2.md, docs/platform/release-notes/tizen-7-0-m1.md
This PR fixes the following files under Release Notes & Compliance:
- https://docs.tizen.org/platform/release-notes/tizen-7-0-m1/
- https://docs.tizen.org/platform/release-notes/tizen-6-5-m2/
- https://docs.tizen.org/platform/release-notes/tizen-6-5-m1/
- https://docs.tizen.org/platform/release-notes/tizen-6-0-m2/
- https://docs.tizen.org/platform/release-notes/tizen-5-5-m3/
- https://docs.tizen.org/platform/release-notes/tizen-6-0-m1/
- https://docs.tizen.org/platform/release-notes/tizen-5-5-m2/
- https://docs.tizen.org/platform/release-notes/tizen-5-5-m1/
- https://docs.tizen.org/platform/release-notes/tizen-5-0-m2/
- https://docs.tizen.org/platform/release-notes/tizen-4-0-m3/
- https://docs.tizen.org/platform/release-notes/tizen-5-0-m1/
- …
=> Update release notes & compliance

docs/application/index.md, docs/application/profiles/index.md, docs/application/profiles/iot.md, docs/application/profiles/mobile.md, docs/application/profiles/tv.md, docs/application/profiles/wearable.md
This is the first PR in the process of updating the .NET applications section of Tizen Docs site.
Signed off by: omar.saeed@samsung.com
=> Get started & Tizen profiles update

docs/application/native/guides/machine-learning/machine-learning-training.md
[7.0][native][Machine-learning][ACR-1721] Add new layer description
- Add attention, mol attention, multi head attention, layer normalization
and positional encoding layer description
Signed-off-by: hyunil park <hyunil46.park@samsung.com>
=> [7.0][native][Machine-learning][ACR-1721] Add new layer description

docs/application/native/guides/machine-learning/machine-learning-service.md, docs/application/native/guides/machine-learning/overview.md
- Update the guide documentation of Machine Learning Service API
- ACR: ACR-1722, ACR-1723
Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>
=> [Machine-learning][ACR-1722][ACR-1723] Update ml-service documentation

docs/application/native/guides/multimedia/image-classification.md, docs/application/native/guides/multimedia/pose-detection.md
Signed-off-by: Tae-Young Chung <ty83.chung@samsung.com>
Update guides according to changes acr-1658
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [capi-media-vision][ACR-1658] Update guides

docs/application/native/guides/multimedia/image-edit.md
=> [ACR-1623] Add the HEIF description

docs/application/native/guides/device/overview.md, docs/application/native/guides/device/resource-monitor.md, docs/application/toc_all.md
=> [capi-system-resource-monitor][ACR-1719] Add the new guide for resource monitor

docs/application/tizen-studio/tizen-core/tizen-core-cli.md
Signed-off-by: Adhavan M/Advance–Software Development Tool /SRI-Bangalore/Engineer/Samsung Electronics <adhavan.m@samsung.com>
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Add rpk guide in tizen-core documentation

docs/application/native/guides/multimedia/image-edit.md
=> [ACR-1695] Add the JPEG-XL description

docs/application/native/guides/multimedia/face-recognition.md, docs/application/native/guides/multimedia/media-vision.md, docs/application/toc_all.md
Signed-off-by: Inki Dae <inki.dae@samsung.com>
Add deep learning based face recognition API guide for Mediavision.
ACR: ACR-1700
=> [capi-media-vision][ACR-1700] Add face recognition API guide

docs/application/dotnet/guides/webview/overview.md, docs/application/dotnet/guides/webview/webview.md
- Deprecate WebView class
- ACR: ACR-515
=> [ACR-515] Deprecate WebView class

docs/platform/release-notes/tizen-7-0-m2.md, docs/platform/toc_all.md
Tizen 7.0 Public M2 Release Note
=> Tizen 7.0 Public M2 Release Note

docs/platform/release-notes/tizen-6-5-m2.md, docs/platform/release-notes/tizen-7-0-m1.md, docs/platform/release-notes/tizen-7-0-m2.md
Adding the release details to the Tizen 7.0 M2 Public Release Note (#1694)
=> Adding Release Details to Tizen 7.0 M2 Public Release Note

docs/application/tizen-studio/release-notes/5-0-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
Signed-off-by: Vivek Ellur/Advance–Software Development Tool /SRI-Bangalore/Staff Engineer/Samsung Electronics <vivek.ellur@samsung.com>
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Tizen-Studio 5.0 public release note

docs/application/native/guides/multimedia/media-vision.md, docs/application/native/guides/multimedia/roi-tracker.md, docs/application/toc_all.md
New API set 'ROI Tracker' is added.
- https://code.sec.samsung.net/jira/browse/ACR-1701
=> [capi-media-vision][ACR-1701] Add ROI tracker CAPI for MediaVision

docs/application/native/guides/location-sensors/overview.md, docs/application/native/guides/location-sensors/user-awareness.md, docs/application/toc_all.md
Update user-awarenees guide
ACR: ACR-1616
=> [capi-network-ua][ACR-1616] Update guides

docs/application/dotnet/get-started/api-privileges.md, docs/application/dotnet/get-started/application-filtering.md, docs/application/dotnet/get-started/certificates/creating-certificates.md, docs/application/dotnet/get-started/certificates/index.md, docs/application/dotnet/get-started/certificates/managing-certificate-profile.md, docs/application/dotnet/get-started/first-app.md, docs/application/dotnet/get-started/index.md, docs/application/dotnet/get-started/wearable-connection/index.md, docs/application/dotnet/index.md, docs/application/dotnet/learn-about-dotnet.md
This is the second PR in the process of updating the .NET applications section of Tizen Docs site.
=> .NET application update (Overview, Learn about .NET & Get Started)

docs/application/dotnet/guides/account/account.md, docs/application/dotnet/guides/account/app-history.md, docs/application/dotnet/guides/account/authentication.md, docs/application/dotnet/guides/account/data-sync.md, docs/application/dotnet/guides/account/fido.md, docs/application/dotnet/guides/account/oauth.md, docs/application/dotnet/guides/account/overview.md, docs/application/dotnet/guides/alarm/alarms.md, docs/application/dotnet/guides/alarm/overview.md, docs/application/dotnet/guides/index.md
This is the third PR in the process of updating the .NET applications section of Tizen Docs site.
=> .NET application update (Account, Authentication & Authorization & Alarms)

docs/application/dotnet/guides/applications/overview.md, docs/application/dotnet/guides/applications/service_application.md, docs/application/dotnet/guides/applications/uiapplication/application_lifecycle.md, docs/application/dotnet/guides/applications/uiapplication/component-based-app.md, docs/application/dotnet/guides/applications/uiapplication/overview.md, docs/application/dotnet/guides/applications/uiapplication/ui-app.md, docs/application/dotnet/guides/applications/uiapplication/watch-app.md, docs/application/dotnet/guides/applications/uiapplication/widget-app.md, docs/application/dotnet/guides/exchange-data-between-apps/app-controls.md, docs/application/dotnet/guides/exchange-data-between-apps/data-control.md, docs/application/dotnet/guides/exchange-data-between-apps/event.md, docs/application/dotnet/guides/exchange-data-between-apps/message-port.md, docs/application/dotnet/guides/exchange-data-between-apps/overview.md, docs/application/toc_all.md
This is the fourth PR in the process of updating the .NET applications section of Tizen Docs site.
=> .NET application update (Applications, UI Application & Exchange Data Between Applications)

docs/platform/what-is-tizen/overview.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Add tizen 7.0 link

docs/application/dotnet/guides/applications/uiapplication/component-based-app.md, docs/application/dotnet/guides/connectivity/bluetooth.md, docs/application/dotnet/guides/connectivity/connection.md, docs/application/dotnet/guides/connectivity/iotcon.md, docs/application/dotnet/guides/connectivity/nfc.md, docs/application/dotnet/guides/connectivity/nsd.md, docs/application/dotnet/guides/connectivity/overview.md, docs/application/dotnet/guides/connectivity/smartcard.md, docs/application/dotnet/guides/connectivity/stc.md, docs/application/dotnet/guides/connectivity/wifi-direct.md, docs/application/dotnet/guides/connectivity/wifi.md
This is the sixth PR in the process of updating the .NET applications section of Tizen Docs site.
This PR includes the fix of the following topics:
1. UI Application **[File count: 1]**
2. Connectivity and Wireless **[File count: 10]**
List of files on which changes were made:
- /application/dotnet/guides/applications/uiapplication/component-based-app/
- /application/dotnet/guides/connectivity/overview/
- /application/dotnet/guides/connectivity/connection/
- /application/dotnet/guides/connectivity/nsd/
- /application/dotnet/guides/connectivity/wifi/
- /application/dotnet/guides/connectivity/wifi-direct/
- /application/dotnet/guides/connectivity/bluetooth/
- /application/dotnet/guides/connectivity/nfc/
- /application/dotnet/guides/connectivity/smartcard/
- …
=> .NET application site fix (Part - 6)

docs/platform/reference/gbs/gbs.conf.md
Changes made on this PR are based on https://github.com/Samsung/tizen-docs/pull/1682#pullrequestreview-1096931268
=> Update gbs.conf.md (PR #1682 fixes)

docs/application/native/guides/multimedia/image-edit.md
This PR has been created to incorporate changes in _**image-edit.md**_ file which was part of https://github.com/Samsung/tizen-docs/pull/1692
=> Update image-edit.md (PR #1692 fixes)

docs/application/native/tutorials/details/native-removed-history.md
Add newly removed functions from Multimedia and Content
- Content
- Multimedai - thumbnail
=> Add newly removed functions from Multimedia and Content

docs/application/dotnet/guides/multimedia/overview.md, docs/application/dotnet/guides/multimedia/webrtc.md, docs/application/toc_all.md
Add WebRTC dotnet guide
- ACR: TCSACR-430/479/480/488/491/501/502/506/510
=> [WebRTC][TCSACR-430] Add WebRTC dotnet guide

docs/application/dotnet/guides/index.md, docs/application/dotnet/guides/multimedia/overview.md, docs/application/toc_all.md
Change multimedia dotnet category name
=> [Multimedia] Change multimedia dotnet category name

docs/application/dotnet/guides/multimedia/thumbnail-images.md
Remove dotnet guide for deprecated ExtractAsync method
- TCSACR-511
=> [ThumbnailExtractor][TCSACR-511] Remove dotnet guide for deprecated ExtractAsync method

docs/application/native/tutorials/details/app-filtering.md
the file (**docs/application/native/tutorials/details/app-filtering.md**) in this PR was part of #1691 which only had the changed part(s) reviewed. Hence opening this after a complete review of the file.
=> update app-filtering (PR #1691 fixes)

docs/application/tizen-studio/tizen-core/tizen-core-cli.md
Opened this PR to incorporate changes in the file (_docs/application/tizen-studio/tizen-core/tizen-core-cli.md_) from #1702
=> Update tizen-core-cli.md (PR #1702 fixes)

docs/application/dotnet/guides/multimedia/face-recognition.md, docs/application/dotnet/guides/multimedia/media-vision.md, docs/application/toc_all.md
Add new dotnet guide for DeepLearningFaceRecognizer
- ACR: TCSACR-504
=> [MediaVision][TCSACR-504] Add new dotnet guide for DeepLearningFaceRecognizer

docs/application/dotnet/guides/multimedia/camera.md
Add dotnet guide for CameraDeviceManager
- ACR: TCSACR-498
=> [Camera][TCSACR-498] Add dotnet guide for CameraDeviceManager

docs/application/dotnet/guides/multimedia/media-vision.md, docs/application/dotnet/guides/multimedia/roi-tracker.md, docs/application/toc_all.md
Add dotnet guide of RoiTracker
- ACR : TCSACR-505
=> [MediaVision][TCSACR-505] Add dotnet guide of RoiTracker

docs/application/dotnet/guides/multimedia/media-content.md, docs/application/dotnet/guides/multimedia/metadata.md, docs/application/dotnet/guides/multimedia/overview.md, docs/application/dotnet/guides/multimedia/thumbnail-images.md
This is the ninth PR in updating the .NET applications section of the Tizen Docs site.
This PR includes the fix of the following topic:
Multimedia [File count: 4]
=> .NET application site fix (Part - 9)

docs/application/dotnet/guides/app-management/package-manager.md
Signed-off-by: Changgyu Choi <changyu.choi@samsung.com>
Adds:
- PackageManager.ClearUserData();
- ACR: TCSACR-522
=> [7.5][PackageManager] Add a docs about ClearUserData API

docs/application/dotnet/guides/multimedia/audio.md, docs/application/dotnet/guides/multimedia/media-controller.md, docs/application/dotnet/guides/multimedia/media-playback.md, docs/application/dotnet/guides/multimedia/media-recording.md, docs/application/dotnet/guides/multimedia/raw-audio.md
This is the eleventh PR in updating the .NET applications section of the Tizen Docs site.
This PR includes the fix of the following files:
- /application/dotnet/guides/multimedia/audio.md
- /application/dotnet/guides/multimedia/media-playback.md
- /application/dotnet/guides/multimedia/media-recording.md
- /application/dotnet/guides/multimedia/raw-audio.md
- /application/dotnet/guides/multimedia/media-controller.md
=> .NET application site fix (Part - 11)

docs/application/dotnet/guides/multimedia/thumbnail-images.md, docs/platform/release-notes/tizen-7-0-m2.md
Opened this PR to reflect the link change for Tizen 7.0 Public M2.
Signed off by: omar.saeed@samsung.com
=> Sync master to live

docs/application/web/api/7.5/device_api/mobile/tizen/sound.html, docs/application/web/api/7.5/device_api/wearable/tizen/sound.html, docs/application/web/guides/multimedia/audio.md
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-288
=> [Sound] Deprecate activate concept and add running concept

docs/application/tizen-studio/release-notes/5-1-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Add Tizen studio 5.1 release notes

docs/application/vstools/Tizen/nuigadget-rpk.md, docs/application/vstools/tools/dotnet-hotreload.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Add prerequisites for NUIGadget and hotreload feature in VS

docs/platform/developing/creating-tic.md
For instance,
- Fix broken links of [creating-tic](https://github.com/Samsung/tizen-docs/blob/master/docs/platform/developing/creating-tic.md)
=> fix the broken link for TIC

docs/application/native/guides/multimedia/camera.md
=> [ACR-1754] Update camera guide for new settings

docs/application/dotnet/guides/nlp/nlp.md, docs/application/dotnet/guides/nlp/overview.md, docs/application/dotnet/guides/notification/attach-panel.md, docs/application/dotnet/guides/notification/noti.md, docs/application/dotnet/guides/notification/overview.md
This PR includes the fix of the following files which is part of the .NET applications section of the Tizen Docs site:
File count: 5
/application/dotnet/guides/nlp/overview.md
/application/dotnet/guides/nlp/nlp.md
/application/dotnet/guides/notification/overview.md
/application/dotnet/guides/notification/noti.md
/application/dotnet/guides/notification/attach-panel.md
=> .NET application site fix (Part - 14)

docs/application/dotnet/guides/security/privilege.md
- ACR: [TCSACR-524](https://code.sec.samsung.net/jira/browse/TCSACR-524)
=> [TCSACR-524] Deprecate  GetPrivacyDisplayName()

docs/application/dotnet/index.md, docs/application/native/get-started/iot/first-app.md, docs/application/profiles/iot.md
- Fix broken links after Tizen School domain change.
=> update Tizen School links

docs/application/native/guides/multimedia/image-barcode.md
Fix docs, related with
https://github.com/Samsung/tizen-docs/pull/1788
=> Fix typo and add missing constrain

docs/application/native/guides/machine-learning/machine-learning-inference.md
- Add the guide documentation of Machine Learning Inference API
- ACR: ACR-1755
=> [Machine-learning][ACR-1755] Add guide for new api

docs/application/native/guides/machine-learning/machine-learning-service.md
- Update the guide documentation of Machine Learning Service API for model
- ACR: ACR-1748
=> [Machine-learning][ACR-1748] Update ml-service documentation

docs/application/native/guides/security/dpm.md
Deprecate Device Policy Manager APIs 
- ACR: ACR-1762 (https://code.sec.samsung.net/jira/browse/ACR-1762)
=> [ACR-1762] Deprecate Device Policy Manager APIs

docs/application/dotnet/guides/multimedia/image-barcode.md
Design QR required Invisible setting.
related,
https://github.com/Samsung/tizen-docs/pull/1812
fix documentation.
=> Fix wrong visibility setting

docs/application/native/tutorials/details/native-removed-history.md
Added a newly removed enum and a defintion to pre-notice table.
Refer to ACR-1765
=> Add newly removed enum and definition

docs/application/dotnet/guides/nlp/nlp.md
- Change deprecated NLP API version
N/A
- ACR: TCSACR-528
=> [TCSACR-528] Change deprecated NLP API version

docs/application/dotnet/get-started/api-privileges.md, docs/application/dotnet/guides/app-management/package-manager.md, docs/application/dotnet/guides/multimedia/image-barcode.md, docs/application/dotnet/guides/nlp/nlp.md, docs/application/dotnet/guides/security/privacy-related-permissions.md, docs/application/native/guides/machine-learning/machine-learning-service.md, docs/application/native/guides/multimedia/image-barcode.md, docs/application/native/guides/security/dpm.md, docs/application/native/guides/security/privacy-related-permissions.md, docs/application/native/tutorials/details/sec-privileges.md, docs/application/web/guides/security/privacy-related-permissions.md, docs/application/web/tutorials/sec-privileges.md
This PR has been created to update files where an instance of **Tizen 7.5** exists.
Reference: https://github.com/Samsung/tizen-docs/pull/1820#issue-1711121938
=> Update instances of all Tizen 7.5 to Tizen 8.0

docs/application/native/guides/machine-learning/machine-learning-training.md
Update Machine-Learning_training.md file
- Add Identity Layer
- Add Learning Rate Scheduler & Usage
- Remove property from optimizer
=> [ML_TRAIN] Update machine-learning-training.md

docs/application/dotnet/guides/security/dpm.md
Deprecate Device Policy Manager APIs
* ACR: TCSACR-539 (https://code.sec.samsung.net/jira/browse/TCSACR-539)
=> [TCSACR-539] Deprecate Device Policy Manager APIs

docs/platform/release-notes/tizen-8-0-m1.md, docs/platform/toc_all.md
add tizen-8-0-m1.md for public release
=> add tizen-8-0-m1.md release note for public release 

docs/application/web/api/8.0/device_api/mobile/tizen/systeminfo.html, docs/application/web/api/8.0/device_api/tv/tizen/systeminfo.html, docs/application/web/api/8.0/device_api/wearable/tizen/systeminfo.html
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-291
For M2 release.
=> [8.0] [Systeminfo] Add uptime feature

docs/application/dotnet/guides/pims/calendar.md, docs/application/dotnet/guides/pims/contacts.md, docs/application/dotnet/guides/sensors/device-sensors.md
This PR includes the fix of the following files which is part of the .NET applications section of the Tizen Docs site:
File count: 3
/application/dotnet/guides/pims/calendar.md
/application/dotnet/guides/pims/contacts.md
/application/dotnet/guides/sensors/device-sensors.md
=> .NET application site fix (Part - 15)

docs/application/native/guides/security/csr.md
Deprecate CSR APIs
ACR: [ACR-1763](https://code.sec.samsung.net/jira/browse/ACR-1763)
=> [ACR-1763] Deprecate CSR APIs

docs/application/native/guides/multimedia/image-classification.md
Add description about timestamp data API for mv_source_h
- [ACR-1759](https://code.sec.samsung.net/jira/browse/ACR-1759)
=> [ACR-1759] Add mv_source_h timestamp API doc

docs/application/dotnet/guides/system/attached-devices.md, docs/application/dotnet/guides/system/feedback.md, docs/application/dotnet/guides/system/overview.md, docs/application/dotnet/guides/system/settings.md, docs/application/dotnet/guides/system/system.md
This PR includes the fix of the following files which is part of the System section under .NET application guides section of the Tizen Docs site:
File count: 5
- /application/dotnet/guides/system/overview.md
- /application/dotnet/guides/system/attached-devices.md
- /application/dotnet/guides/system/system.md
- /application/dotnet/guides/system/settings.md
- /application/dotnet/guides/system/feedback.md
=> .NET application site fix (Part - 17)

docs/application/native/guides/text-input/tts.md
- Add extra descriptions for TTS modes
=> [tts][Non-ACR] Add extra descriptions for TTS modes

docs/application/native/guides/text-input/stt.md
Add description for audio streaming functions
- ACR: ACR-1782
=> [stt][ACR-1782] Add description for audio streaming functions

docs/application/native/guides/multimedia/media-playback.md
Add guide about video codec api which is added by ACR-1774.
ACR : https://code.sec.samsung.net/jira/browse/ACR-1774
=> [Player][ACR-1774] Add codec api

docs/application/native/guides/text-input/stt.md
Add description for audio ID.
- ACR: ACR-1785
=> [stt][ACR-1785] Add description for audio ID

docs/application/native/guides/multimedia/camera.md
=> [ACR-1768] Add new attribute(focus level) for camera setting

docs/application/native/guides/text-input/tts.md
- Add TTS synthesized PCM callback
- ACR: ACR-1779
=> [tts][ACR-1779] Add TTS synthesized PCM callback

docs/application/native/guides/multimedia/sound-manager.md
- Add the guide for effect method APIs
- ACR: ACR-1781
=> [sound-manager][ACR-1781] Add the guide for effect method APIs

docs/application/native/guides/machine-learning/machine-learning-service.md
- Update the document for ML service APIs.
- Match the API usage with recent signature change in ml-service-model APIs
- Add document for newly added APIs: ml_service_resource_*
- ACR: ACR-1784
=> [Machine-Learning][ACR-1784] Update ml-service documentation 

docs/platform/developing/setting-up.md
- Update the snapshot URL in the gbs.conf template to the new URL.
- remove usless buildconf
=> update snapshot url in gbs.conf template

docs/application/dotnet/guides/maps/maps.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [TCSACR-533] Maps deprecation message

docs/application/dotnet/guides/uix/tts.md
Add TTS SynthesizedPCM and PlayingMode guide
- ACR: TCSACR-553
=> [tts][TCSACR-553] Add TTS SynthesizedPCM and PlayingMode guide

docs/platform/reference/set-up-docker.md, docs/platform/reference/tic-faq.md
- fix broken link for the TIC docker-compose file
- add a new faq item for TIC
- update the set-up-docker for configuring proxy information
=> Update docs related to TIC

docs/application/native/guides/app-management/tidl.md
From Tizen 8.0, the following features are supported:
- Enum Type
- Import Another TIDL File
- Method Privilege
- Map and Set Container Type
- Marshalling Type Info
- Struct Inheritance
- Remote Exception
- Local Execution Mode
- Private Sharing (without -b option)
=> Update TIDL document for protocol version 2.

docs/application/native/guides/messaging/email.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [ACR-1794] Email deprecation message

docs/application/native/guides/location-sensors/geofences.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [ACR-1796] geofence deprecation message

docs/application/native/guides/text-input/capi-ui-gesture.md
=> [Gesture][ACR-1786] Deprecated Gesture APIs

docs/application/web/api/8.0/device_api/mobile/index.html, docs/application/web/api/8.0/device_api/mobile/tizen/messaging.html
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-292
=> [Messaging] Whole module deprecated

docs/application/dotnet/guides/messaging/email.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [TCSACR-558] email deprecation message

docs/application/dotnet/guides/location/geofences.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [TCSACR-559] geofence deprecation message

docs/application/native/guides/connectivity/bluetooth.md
=> Update Bluetooth guide

docs/application/web/api/8.0/device_api/tv/tizen/tvwindow.html
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-293
=> [TVWindow] Added source rotation feature

docs/application/tizen-studio/release-notes/5-5-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Add release notes for Tizen Studio 5.5 release

docs/platform/toc_all.md, docs/platform/what-is-tizen/overview.md
I updated the document 
1. add 8.0 
2. change toc file
Thanks
=> Update version and toc file

docs/application/native/tutorials/details/app-filtering.md
ACR1720 new api vision 3d (depth, pointcloud)
=> Add new features for vision 3d

docs/application/native/guides/connectivity/nsd.md
For instance,
- Add guides for dnssd_browse_service() and dnssd_resolve_service()
For instance,
- ACR: https://jira.sec.samsung.net/browse/ACR-1718
=> [NSD][ACR-1718] Update nsd.md

docs/application/dotnet/guides/multimedia/camera.md
Add new APIs for manual focus level
- ACR: TCSACR-545
=> [Camera][TCSACR-545] Add new APIs for manual focus level

docs/application/native/guides/text-input/voice-control-engine.md
- ACR: ACR-1714
- Add TIDL privileges in VCE prerequisites
- https://jira.sec.samsung.net/browse/ACR-1714
=> [ACR-1714][voice-control] Add TIDL privileges in VCE prerequisites

docs/application/native/api/common/8.0/group__CAPI__MEDIA__VISION__COMMON__MODULE.html, docs/application/native/api/common/8.0/group__CAPI__MEDIA__VISION__FACE__RECOGNITION__MODULE.html, docs/application/native/api/common/8.0/group__CAPI__WEB__DOWNLOAD__MODULE.html, docs/application/native/api/common/8.0/group__TIZEN__WS__SHELL__MODULE.html, docs/application/native/api/common/8.0/search-config.php, docs/application/native/api/iot-headed/7.0/group__CAPI__MEDIA__VISION__COMMON__MODULE.html, docs/application/native/api/iot-headed/7.0/group__CAPI__MEDIA__VISION__FACE__RECOGNITION__MODULE.html, docs/application/native/api/iot-headed/7.0/search-config.php, docs/application/native/api/mobile/7.0/group__CAPI__MEDIA__VISION__COMMON__MODULE.html, docs/application/native/api/mobile/7.0/group__CAPI__MEDIA__VISION__FACE__RECOGNITION__MODULE.html, docs/application/native/api/mobile/7.0/search-config.php, docs/application/native/api/wearable/7.0/group__CAPI__MEDIA__VISION__COMMON__MODULE.html, docs/application/native/api/wearable/7.0/group__CAPI__MEDIA__VISION__FACE__RECOGNITION__MODULE.html, docs/application/native/api/wearable/7.0/search-config.php
- Feature requirements has been changed by DA divsion request
- Update 7.0 Mobile / Wearable / Headed API Reference
- Update 8.0 Common API Reference
No need to check the content of Native API Reference. It was reviewed and checked by ACR/API Part.
=> Updated 7.0 mobile/wearable/iot-headed and 8.0 for media vision feature

docs/application/native/guides/multimedia/metadata.md
- ACR: [ACR-1810](https://jira.sec.samsung.net/browse/ACR-1810)
=> [ACR-1810] Deprecate all APIs

docs/application/native/guides/multimedia/media-content.md
ACR: [ACR-1811](https://jira.sec.samsung.net/browse/ACR-1811)
=> [ACR-1811] Deprecate underutilized fields

docs/application/dotnet/guides/multimedia/metadata.md
Deprecate MetadataEditor module
- ACR: TCSACR-569
=> [TCSACR-569] Deprecate MetadataEditor module

docs/application/native/api/common/8.0/group__CAPI__BASE__UTILS__I18N__UCALENDAR__MODULE.html, docs/application/native/api/common/8.0/group__CAPI__MEDIA__IMAGE__UTIL__TRANSFORM__MODULE.html, docs/application/native/api/common/8.0/search-config.php
- Added new image util function
- Added minor doc enhancement
=> Update 8.0 Common Native API Reference for Image Util

docs/application/index.md
remove 'OBS' because of change build system
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Update index.md for removing OBS

docs/application/web/api/index.md
Add missing link to 8.0 docs in index file.
=> Added link to 8.0 docs

docs/application/native/tutorials/details/native-removed-history.md
Added newly removed modules and functions since 8.0
=> Update removed modules and functions

docs/application/dotnet/api/overview.md
Remove Xamarin.Forms and Tizen.Wearable.CircularUI from .NET API Overview
=> Remove items from .NET API Overview

docs/application/native/guides/app-management/common-appcontrols.md, docs/application/web/guides/app-management/common-appcontrols.md
- Updated sentences related with profile, because profile concept is not available since 8.0
=> Update Common Application Controls page to remove profile concept

docs/application/web/api/8.0/device_api/tv/tizen/tvwindow.html
Some minor fixes to API documentation for ACR:
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-293
=> [WebAPI] TVWindow - minor fixes

docs/application/native/guides/multimedia/media-content.md
- ACR: [ACR-1820](https://jira.sec.samsung.net/browse/ACR-1820)
=> [ACR-1820] Deprecate low usability fields

docs/application/native/api/common/8.0/group__CAPI__SYSTEM__SYSTEM__SETTINGS__MODULE.html, docs/application/native/api/common/8.0/group__CAPI__UIX__INPUTMETHOD__MODULE.html, docs/application/native/api/common/8.0/group__OPENSRC__JSONGLIB__FRAMEWORK.html, docs/application/native/api/common/8.0/search-config.php
Fixed broken link of json glib
Added missing version of some input method
Updated feature information of system settings
* No need to review details of 8.0 Native API Reference. reviewed by API part.
=> Update 8.0 Native API Ref to fix minor issues

docs/application/web/api/9.0/device_api/mobile/tizen/content.html, docs/application/web/api/9.0/device_api/tv/tizen/content.html, docs/application/web/api/9.0/device_api/wearable/tizen/content.html
Native members were deprecated, thus deprecate also on web side.
[ACR] https://jira.sec.samsung.net/browse/TWDAPI-294
=> [9.0][content][Deprecation] Deprecate members not used frequently

docs/application/native/guides/multimedia/media-content.md
- ACR: [ACR-1838](https://jira.sec.samsung.net/browse/ACR-1838)
=> [Acr-1838] Deprecate all bookmark and playlist funtions

docs/application/web/api/9.0/device_api/tv/tizen/tvwindow.html
PR #1942 accidentally removed documentation related to: [ACR] https://jira.sec.samsung.net/browse/TWDAPI-293 instead it should fix some minor typos as it was in PR #1935
This PR re-adds the content for TWDAPI-293.
=> Fix error while adding TWDAPI-293 on 9.0 branch

docs/application/tizen-studio/release-notes/5-6-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Add release notes for 5.6 release

docs/application/web/api/9.0/device_api/mobile/tizen/content.html, docs/application/web/api/9.0/device_api/tv/tizen/content.html, docs/application/web/api/9.0/device_api/wearable/tizen/content.html
[ACR] https://jira.sec.samsung.net/browse/TWDAPI-295
=> [Content] Deprecate Playlist

docs/application/vscode-ext/Tizen/web_app.md, docs/application/vstools/Tizen/web.md, docs/application/web/get-started/wearable-watch/first-app-watch.md, docs/application/web/get-started/wearable/first-app.md, docs/application/web/index.md
File count 5:
/application/web/index.md
/application/vscode-ext/Tizen/web_app.md
/application/vstools/Tizen/web.md
/application/web/get-started/wearable/first-app.md
/application/web/get-started/wearable-watch/first-app-watch.md
=> Web application site fix (Part - 01)

docs/application/web/api/8.0/device_api/tv/tizen/tvwindow.html
Fixed formatting to follow API reference style.
=> [Webapi] Fixed formatting of code example

docs/application/web/tutorials/app-filtering.md, docs/application/web/tutorials/event-handling.md, docs/application/web/tutorials/old-versioned-sec-privileges.md, docs/application/web/tutorials/sec-privileges.md, docs/application/web/tutorials/sign-certificate.md, docs/application/web/tutorials/web-runtime.md
File count: 6
/application/web/tutorials/app-filtering.md
/application/web/tutorials/sec-privileges.md
/application/web/tutorials/old-versioned-sec-privileges.md
/application/web/tutorials/web-runtime.md
/application/web/tutorials/event-handling.md
/application/web/tutorials/sign-certificate.md
=> Web application site fix (Part - 04)

docs/application/native/guides/machine-learning/machine-learning-service.md
Add docs for ml-service API.
- ACR: ACR-1830
=> [ACR-1830] Add docs for ml-service API

docs/application/dotnet/get-started/application-filtering.md, docs/application/features/feature.md, docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
1) platform.core.abi
2) platform.core.cpu.arch.riscv32
3) platform.core.cpu.arch.riscv64
- ACR: ACR-1814 (new feature key)
=> ACR-1814: Add a new feature key for ABI info

docs/application/tizen-studio/native-tools/project-conversion.md
Modify project convert guide to describe the cli project structure and add example.
For instance,
-  ...
N/A
N/A
=> Modify native project covert guide

docs/application/web/guides/cordova/dialogs.md, docs/application/web/guides/cordova/filetransfer.md, docs/application/web/guides/cordova/globalization.md, docs/application/web/guides/cordova/media.md, docs/application/web/guides/cordova/network-information.md, docs/application/web/guides/tau/tau.md
File count: 6
/application/web/guides/cordova/filetransfer.md
/application/web/guides/cordova/globalization.md
/application/web/guides/cordova/media.md
/application/web/guides/cordova/network-information.md
/application/web/guides/cordova/dialogs.md
/application/web/guides/tau/tau.md
=> Web application site fix (Part - 09)

docs/application/web/guides/tau/download-tau.md, docs/application/web/guides/tau/event-handling.md, docs/application/web/guides/tau/helloworld.md, docs/application/web/guides/tau/managing-page.md, docs/application/web/guides/tau/notepad.md, docs/application/web/guides/tau/ui-component.md
File count: 6
/application/web/guides/tau/download-tau.md
/application/web/guides/tau/helloworld.md
/application/web/guides/tau/managing-page.md
/application/web/guides/tau/event-handling.md
/application/web/guides/tau/ui-component.md
/application/web/guides/tau/notepad.md
=> Web application site fix (Part - 10)

docs/application/web/guides/tau/circle-progressbar.md, docs/application/web/guides/tau/header.md, docs/application/web/guides/tau/helper.md, docs/application/web/guides/tau/list.md, docs/application/web/guides/tau/processing.md, docs/application/web/guides/tau/tau-rotary.md
File count: 6
/application/web/guides/tau/tau-rotary.md
/application/web/guides/tau/helper.md
/application/web/guides/tau/list.md
/application/web/guides/tau/header.md
/application/web/guides/tau/circle-progressbar.md
/application/web/guides/tau/processing.md
=> Web application site fix (Part - 11)

docs/application/web/guides/tau/accessibility.md, docs/application/web/guides/tau/footerbutton.md, docs/application/web/guides/tau/indexscrollbar.md, docs/application/web/guides/tau/moreoptions.md, docs/application/web/guides/tau/popup.md, docs/application/web/guides/tau/thumbnail.md
File count: 6
/application/web/guides/tau/footerbutton.md
/application/web/guides/tau/thumbnail.md
/application/web/guides/tau/popup.md
/application/web/guides/tau/indexscrollbar.md
/application/web/guides/tau/moreoptions.md
/application/web/guides/tau/accessibility.md
=> Web application site fix (Part - 12)

docs/application/web/guides/localization/localization.md, docs/application/web/guides/notification/notification.md, docs/application/web/guides/tau/animation.md, docs/application/web/guides/tau/creating-animation.md, docs/application/web/guides/tau/globalization.md, docs/application/web/guides/tau/tau-porting.md
File count: 6
/application/web/guides/tau/globalization.md
/application/web/guides/tau/animation.md
/application/web/guides/tau/creating-animation.md
/application/web/guides/tau/tau-porting.md
/application/web/guides/localization/localization.md
/application/web/guides/notification/notification.md
=> Web application site fix (Part - 13)

docs/iot/guides/update-control-api.md
- Enhanced documentation to reflect the changes in ACR-1844
- Reworded parts of the documentation to include the differences between synchronous and asynchronous upgrades
- Added a working example of a simple stand-alone program utilizing the new features to illustrate their use
- Added Error Codes subsection listing possible API error codes and their meanings
- ACR: ACR-1844
=> update-control: update documentation

docs/application/web/guides/connectivity/bluetooth.md, docs/application/web/guides/connectivity/connectivity.md, docs/application/web/guides/connectivity/iotcon.md, docs/application/web/guides/multimedia/camera.md, docs/application/web/guides/multimedia/media-key.md, docs/application/web/guides/multimedia/radio.md
File count: 6
/application/web/guides/multimedia/media-key.md
/application/web/guides/multimedia/radio.md
/application/web/guides/multimedia/camera.md
/application/web/guides/connectivity/connectivity.md
/application/web/guides/connectivity/bluetooth.md
/application/web/guides/connectivity/iotcon.md
=> Web application site fix (Part - 16)

docs/application/web/guides/personal/account.md, docs/application/web/guides/personal/calendar.md, docs/application/web/guides/personal/call-history.md, docs/application/web/guides/personal/personal.md, docs/application/web/guides/text-input/input-device.md, docs/application/web/guides/text-input/voice-control.md
File count: 6
/application/web/guides/text-input/input-device.md
/application/web/guides/text-input/voice-control.md
/application/web/guides/personal/personal.md
/application/web/guides/personal/account.md
/application/web/guides/personal/calendar.md
/application/web/guides/personal/call-history.md
=> Web application site fix (Part - 19)

docs/application/web/guides/data/data-filter.md, docs/application/web/guides/data/data.md, docs/application/web/guides/data/file-system.md, docs/application/web/guides/data/stored-content.md, docs/application/web/guides/personal/contacts.md, docs/application/web/guides/personal/sync.md
File count: 6
/application/web/guides/personal/contacts.md
/application/web/guides/personal/sync.md
/application/web/guides/data/data.md
/application/web/guides/data/data-filter.md
/application/web/guides/data/file-system.md
/application/web/guides/data/stored-content.md
=> Web application site fix (Part - 20)

docs/application/web/guides/w3c/device/browser-state.md, docs/application/web/guides/w3c/device/screen-orientation.md, docs/application/web/guides/w3c/graphics/canvas.md, docs/application/web/guides/w3c/graphics/graphics-guide.md, docs/application/web/guides/w3c/graphics/svg.md, docs/application/web/guides/w3c/multimedia/media-guide.md
File count: 6
/application/web/guides/w3c/device/browser-state.md
/application/web/guides/w3c/device/screen-orientation.md
/application/web/guides/w3c/graphics/graphics-guide.md
/application/web/guides/w3c/graphics/canvas.md
/application/web/guides/w3c/graphics/svg.md
/application/web/guides/w3c/multimedia/media-guide.md
=> Web application site fix (Part - 24)

docs/application/features/feature.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> update platform.core.abi information

docs/application/features/feature.md
Suggested-by: Minseok Jang <m.s.jang@samsung.com>
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> update platform.core.cpu.arch information

docs/application/web/guides/w3c/security/cors.md, docs/application/web/guides/w3c/security/security-guide.md, docs/application/web/guides/w3c/storage/appcache.md, docs/application/web/guides/w3c/storage/indexdb.md, docs/application/web/guides/w3c/storage/web-storage.md, docs/application/web/guides/w3c/storage/websql.md
File count: 6
/application/web/guides/w3c/storage/indexdb.md
/application/web/guides/w3c/storage/web-storage.md
/application/web/guides/w3c/storage/appcache.md
/application/web/guides/w3c/storage/websql.md
/application/web/guides/w3c/security/security-guide.md
/application/web/guides/w3c/security/cors/
=> Web application site fix (Part - 27)

docs/application/web/guides/w3c/perf-opt/page.md, docs/application/web/guides/w3c/perf-opt/performance-guide.md, docs/application/web/guides/w3c/security/iframe.md
File count: 3
/application/web/guides/w3c/security/iframe.md
/application/web/guides/w3c/perf-opt/performance-guide.md
/application/web/guides/w3c/perf-opt/page.md
=> Web application site fix (Part - 28)

docs/application/web/guides/w3c/perf-opt/performance-improvement.md, docs/application/web/guides/w3c/perf-opt/timing-control.md, docs/application/web/guides/w3c/perf-opt/web-workers.md
File count: 3
/application/web/guides/w3c/perf-opt/timing-control.md
/application/web/guides/w3c/perf-opt/performance-improvement.md
/application/web/guides/w3c/perf-opt/web-workers.md
=> Web application site fix (Part - 29)

docs/application/web/guides/w3c/perf-opt/jquery-performance-improvement.md, docs/application/web/guides/w3c/perf-opt/js-performance-improvement.md, docs/application/web/guides/w3c/perf-opt/minify-js-css.md
File count: 3
/application/web/guides/w3c/perf-opt/js-performance-improvement.md
/application/web/guides/w3c/perf-opt/minify-js-css.md
/application/web/guides/w3c/perf-opt/jquery-performance-improvement.md
=> Web application site fix (Part - 30)

docs/application/web/tutorials/web-runtime.md
Add description of restrictions on using window.open() function in WebRuntime.
=> Add description to WebRuntime guide

docs/application/native/guides/text-input/tts.md
[ACR-1840][tts] Add add text with synthesis parameter and silent utterance
=> [ACR-1840][tts] Add add text with synthesis parameter and silent utterance

docs/application/native/guides/text-input/tts-engine.md, docs/application/native/guides/text-input/tts.md
[ACR-1862][tts] Add API to support personal voice
=> [ACR-1862][tts] Add API to support personal voice

docs/application/native/guides/app-management/tidl.md
=> Add tidl Rust description

docs/application/dotnet/guides/applications/tizen-core/tizen-core-channel.md, docs/application/dotnet/guides/applications/tizen-core/tizen-core-event.md, docs/application/dotnet/guides/applications/tizen-core/tizen-core.md, docs/application/toc_all.md
This PR adds new guide documents for Tizen.Core API.
For instance,
-TCSACR-595
=> [TCSACR-595] Add new guide documents for Tizen.Core

docs/platform/release-notes/tizen-9-0-m2.md, docs/platform/toc_all.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Add Tizen 9.0 M2 Release Notes

docs/application/tizen-studio/release-notes/6-0-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Add Tizen Studio 6.0 Release Notes

docs/application/web/api/9.0/device_api/mobile/index.xml, docs/application/web/api/9.0/device_api/tv/index.xml, docs/application/web/api/9.0/device_api/wearable/index.xml, docs/application/web/api/toc.xml
Same change as https://github.com/Samsung/tizen-docs/pull/1931 but for Tizen 9.0 TOC
=> [Web][9.0] Add 9.0 to TOC

docs/application/native/guides/machine-learning/machine-learning-inference.md
- Add doc for ml_pipeline_flush.
=> [6.5][capi-machine-learning][Add] New API to flush pipeline data

docs/platform/developing/flashing-rpi.md
The location of sd_fusing.py was changed.
Update to new url instead of old url.
- repository was changed from platform/kernel/u-boot to platform/kernel/tizen-fusing-scripts
=> Update flahsing-rpi.md file

docs/application/native/guides/connectivity/http-api.md
ACR-1856
https://jira.sec.samsung.net/browse/ACR-1856
=> [ACR-1856] Update http-api.md 

docs/application/native/tutorials/details/native-removed-history.md
Add newly removed functions to notice table
- ACR: ACR-1874
=> Add newly removed functions to notice table

docs/application/native/guides/connectivity/http-api.md
=> Updated changes

docs/application/native/guides/location-sensors/user-awareness.md
Add `User Awareness` API reference link
nothing
nothing
=> [User-Awareness] Add API reference link

docs/application/dotnet/guides/machine-learning/machine-learning-inference.md, docs/application/dotnet/guides/machine-learning/machine-learning-train.md, docs/application/dotnet/guides/machine-learning/overview.md, docs/application/dotnet/guides/machine-learning/pipeline.md, docs/application/dotnet/guides/machine-learning/singleshot.md, docs/application/native/guides/machine-learning/machine-learning-inference.md, docs/application/native/guides/machine-learning/machine-learning-service.md, docs/application/native/guides/machine-learning/machine-learning-training.md, docs/application/native/guides/machine-learning/overview.md
Add links pointing API refenrence for nativa and dotnet API.
No
=> [MachineLearning] Add links pointing API references

docs/application/dotnet/guides/multimedia/media-vision.md, docs/application/dotnet/guides/multimedia/overview.md, docs/application/dotnet/guides/multimedia/pose-detection.md, docs/application/dotnet/guides/multimedia/webrtc.md
[Multimedia] Add Dotnet API reference link
nothing
nothing
=> [Multimedia] Add Dotnet API reference link

docs/application/native/guides/multimedia/media-playback.md
- Update API reference link in playback file
=> [Multimedia] Update API reference link

docs/application/dotnet/guides/connectivity/bluetooth.md, docs/application/dotnet/guides/connectivity/connection.md, docs/application/dotnet/guides/connectivity/iotcon.md, docs/application/dotnet/guides/connectivity/nfc.md, docs/application/dotnet/guides/connectivity/nsd.md, docs/application/dotnet/guides/connectivity/overview.md, docs/application/dotnet/guides/connectivity/smartcard.md, docs/application/dotnet/guides/connectivity/stc.md, docs/application/dotnet/guides/connectivity/wifi-direct.md, docs/application/dotnet/guides/connectivity/wifi.md
Add links of the API reference pages to Guides in Connectivity section.
=> Add Dotnet API reference link

docs/application/native/guides/device/diagnostics.md
=> [Diagnostics API] Add API reference link

docs/application/dotnet/guides/uix/sticker.md, docs/application/native/guides/app-management/sticker.md
=> [Sticker] Add API reference links

docs/application/native/guides/multimedia/face-detection.md, docs/application/native/guides/multimedia/face-recognition.md, docs/application/native/guides/multimedia/facial-landmark.md, docs/application/native/guides/multimedia/image-barcode.md, docs/application/native/guides/multimedia/image-classification.md, docs/application/native/guides/multimedia/image-recognition.md, docs/application/native/guides/multimedia/object-detection.md, docs/application/native/guides/multimedia/pose-landmark.md, docs/application/native/guides/multimedia/roi-tracker.md
Add Mediavision relevant Native API reference link.
=> [Mediavision] Add Native API reference link

docs/application/native/guides/device/attached-devices.md, docs/application/native/guides/device/feedback.md, docs/application/native/guides/device/overview.md, docs/application/native/guides/device/resource-monitor.md, docs/application/native/guides/device/runtime.md, docs/application/native/guides/device/settings.md, docs/application/native/guides/device/system.md
Add Native API Reference link in System module.
- System
- Device
- Feedback
- System Settings
- Resource Monitor
- Runtime Information
=> [System] Add Native API Reference link

docs/application/dotnet/guides/system/attached-devices.md, docs/application/dotnet/guides/system/feedback.md, docs/application/dotnet/guides/system/overview.md, docs/application/dotnet/guides/system/settings.md, docs/application/dotnet/guides/system/system.md
=> [System] Add API reference links

docs/application/tizen-studio/release-notes/6-1-release-notes.md, docs/application/tizen-studio/release-notes/release-notes.md, docs/application/toc_all.md
Updating Tizen Studio 6.1 Release Notes
=> Tizen Studio 6.1 Release Notes

docs/application/vstools/tools/api-privilege-checker.md, docs/application/vstools/tools/device-manager.md
=> fix_broken_link

docs/application/native/tutorials/details/native-removed-history.md
- removed a column for unnecessary Tizen profile
=> Update removed history page for new table

docs/application/dotnet/index.md
- tizen schools are removed. contents should be removed.
=> Remove tizen school from index

docs/application/sdktool_index.md
Fix a wrong document format for SDK Tools index.
=> Fix a wrong document format for SDK Tools index

docs/application/sdktool_index.md
Fix a wrong link url information to each tool
=> Fix a wrong link url information to each tool

docs/platform/release-notes/tizen-2-1.md, docs/platform/release-notes/tizen-2-2-1.md, docs/platform/release-notes/tizen-2-2.md, docs/platform/release-notes/tizen-2-3-1.md, docs/platform/release-notes/tizen-2-3.md, docs/platform/release-notes/tizen-2-4.md, docs/platform/release-notes/tizen-3-0-m2.md, docs/platform/release-notes/tizen-3-0-m3.md, docs/platform/release-notes/tizen-3-0-m4.md, docs/platform/release-notes/tizen-4-0-m1.md, docs/platform/release-notes/tizen-4-0-m2.md, docs/platform/release-notes/tizen-4-0-m3.md, docs/platform/release-notes/tizen-5-0-m1.md, docs/platform/release-notes/tizen-5-0-m2.md, docs/platform/release-notes/tizen-5-5-m1.md, docs/platform/release-notes/tizen-5-5-m2.md, docs/platform/release-notes/tizen-5-5-m3.md, docs/platform/release-notes/tizen-6-0-m1.md, docs/platform/release-notes/tizen-6-0-m2.md, docs/platform/release-notes/tizen-6-5-m1.md, docs/platform/release-notes/tizen-6-5-m2.md, docs/platform/release-notes/tizen-7-0-m1.md, docs/platform/release-notes/tizen-7-0-m2.md, docs/platform/release-notes/tizen-8-0-m1.md, docs/platform/release-notes/tizen-8-0-m2.md, docs/platform/release-notes/tizen-9-0-m1.md, docs/platform/release-notes/tizen-9-0-m2.md
- fix broken link of the release notes.
=> fix broken link of the release notes

docs/application/native/guides/connectivity/stc.md
- Deprecate all STC API
- ACR: ACR-1910
=> [10.0][capi-network-stc][Deprecate] All STC API

docs/application/native/guides/connectivity/nsd.md
- Deprecate all SSDP APIs
- ACR: ACR-1912
=> [10.0][capi-network-nsd][Deprecated] SSDP APIs

docs/application/dotnet/guides/connectivity/nsd.md
- Deprecated all ssdp related APIs
For instance,
- ACR: TCSACR-617
=> [10.0][Tizen.Network.Nsd][Deprecate] SSDP related APIs

docs/application/native/api/common/8.0/group__CAPI__NETWORK__STC__MANAGER__MODULE.html, docs/application/native/api/common/8.0/group__CAPI__NETWORK__STC__MODULE.html, docs/application/native/api/common/8.0/group__CAPI__NETWORK__STC__RESTRICTION__MODULE.html, docs/application/native/api/common/8.0/group__CAPI__NETWORK__STC__STATISTICS__MODULE.html, docs/application/native/api/common/8.0/group__OPENSRC__LIBXML__FRAMEWORK.html, docs/application/native/api/common/8.0/group__OPENSRC__MINIZIP__FRAMEWORK.html, docs/application/native/api/common/8.0/group__OPENSRC__SQLITE__FRAMEWORK.html, docs/application/native/api/common/8.0/group__OPENSRC__ZLIB__FRAMEWORK.html, docs/application/native/api/common/8.0/search-config.php, docs/application/native/api/common/9.0/group__CAPI__CONTENT__MEDIA__FILTER__MODULE.html, docs/application/native/api/common/9.0/group__CAPI__NETWORK__STC__MANAGER__MODULE.html, docs/application/native/api/common/9.0/group__CAPI__NETWORK__STC__MODULE.html, docs/application/native/api/common/9.0/group__CAPI__NETWORK__STC__RESTRICTION__MODULE.html, docs/application/native/api/common/9.0/group__CAPI__NETWORK__STC__STATISTICS__MODULE.html, docs/application/native/api/common/9.0/group__CAPI__SYSTEM__PERIPHERAL__IO__ADC__MODULE.html, docs/application/native/api/common/9.0/group__CAPI__SYSTEM__PERIPHERAL__IO__PWM__MODULE.html, docs/application/native/api/common/9.0/group__CAPI__SYSTEM__PERIPHERAL__IO__SPI__MODULE.html, docs/application/native/api/common/9.0/group__CAPI__SYSTEM__PERIPHERAL__IO__UART__MODULE.html, docs/application/native/api/common/9.0/group__CAPI__TELEPHONY__INFORMATION.html, docs/application/native/api/common/9.0/group__CAPI__USB__HOST__ASYNC__MODULE.html, docs/application/native/api/common/9.0/group__CAPI__USB__HOST__SYNCIO__MODULE.html, docs/application/native/api/common/9.0/group__OPENSRC__LIBXML__FRAMEWORK.html, docs/application/native/api/common/9.0/group__OPENSRC__MINIZIP__FRAMEWORK.html, docs/application/native/api/common/9.0/group__OPENSRC__SQLITE__FRAMEWORK.html, docs/application/native/api/common/9.0/group__OPENSRC__ZLIB__FRAMEWORK.html, docs/application/native/api/common/9.0/search-config.php
- Updated opensource version
- Fixed minor issues
* No need to review the content of API Reference. API Part have checked the output.
=> Update 8.0/9.0  Natvie API Reference

docs/application/native/guides/app-management/package-manager.md
Add first installed time
- ACR: ACR-1901
=> [ACR-1901] first installed time

docs/platform/porting/kernel.md
- Fix typo about user.img
- Update wronng build script name
=> Update porting kernel file

docs/application/toc_vs-ext_dotnet.md, docs/application/toc_vs-ext_native.md, docs/application/toc_vs-ext_web.md
=> fix document hierarchy

docs/application/native/guides/personal/context.md
- Deprecated Context APIs
- ACR: ACR-1916
=> [10.0][context][Deprecate] Deprecate Context API

docs/application/dotnet/guides/app-management/package-manager.md
Add FirstInstalledTime
- ACR: TCSACR-623
=> [TCSACR-623] Add FirstInstalledTime

docs/application/native/guides/connectivity/curl.md
Improve and add the cURL guide for app developers' convenience.
N/A
N/A
=> Improve curl guide

docs/application/dotnet/guides/index.md, docs/application/dotnet/guides/system/overview.md, docs/application/dotnet/guides/system/usb-host.md, docs/application/toc_all.md, docs/application/toc_all_new.md
=> Add dotnet USB host guide.
