Samsung/tizen-docs

docs/application/web/api/5.0/device_api/mobile/tizen/filesystem.html, docs/application/web/api/5.0/device_api/tv/tizen/filesystem.html, docs/application/web/api/5.0/device_api/wearable/tizen/filesystem.html
The remark about escaping '%' character in FileFilter description did
not take into account the fact, that '\' escape character needs itself
to be escaped from the string with another backslash.
The description was updated.
Signed-off-by: Pawel Wasowski <p.wasowski2@partner.samsung.com>
=> [Filesystem] Amend the remark about proper escaping in the FileFilter

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
network.tethering.wifi.direct feature has been added since tizen 4.0
[related ACR]
http://suprem.sec.samsung.net/jira/browse/ACR-967
=> Add feature key for wifi-direct tethering

docs/iot/getting-started/tizen-image-download-flash.md
We clearly commented that only the USB SD card reader is supported.
Signed-off-by: Jihoon Park <jpark0@samsung.com>
- Clearly commented that only the USB SD card reader is supported in IoT Setup Manager
=> Modified the usage of IoT Setup Manager

docs/application/tizen-studio/release-notes/2-3-release-notes.md, docs/application/tizen-studio/release-notes/2-4-release-notes.md
According to the Tizen Doc Team checklist, made some minor changes in the files.
- Changed v3.0 to version 3.0, v2.0 to version 2.0, and v1.1 to version 1.1.
As we cant set the version to version 2.0 and 3.0 at the same time, the & symbol is replaced by or.
For example, set OpenGL ES version to v2.0 & v3.0, rephrased to 
set OpenGL ES version to version 2.0 or to version 3.0.
- Rephrased a sentence to avoid possessive apostrophe.
"the Emulator Manager's shortcut image" rephrased to 
"the shortcut image of Emulator Manager"
- Changed hyphenated words:
life-cycle to lifecycle
start-up to startup
Please verify the changes.
=> Updated files with minor changes according to review checklist

docs/application/native/api/overview.md
Fix the links of API references on docs/applications/native/api/overview page.
=> Fix the links of API references on overview page

docs/application/native/guides/internationalization/i18n.md
Added guide for immutable index module from base-utils library.
[ACR] http://suprem.sec.samsung.net/jira/browse/ACR-1118
Signed-off-by: Lukasz Pik <lu.pik@samsung.com>
=> [base-utils] Add guides for immutable index module

docs/application/native/guides/multimedia/sound.md
Signed-off-by: Sangchul Lee <sc11.lee@samsung.com>
Remove deprecated enum value in code snippet.
It is related to ACR-1228
=> [sound-manager] remove deprecated enum value in code snippet

docs/application/dotnet/guides/notification/attach-panel.md
In ACR  [TCSACR-150] [ACR-1243]  telephony privilege is added to use
Camera UI gadget, same is updated in this document.
In public attach-panel API attach_panel_add_content_category(), under CAMERA content,
Camera app should not be launched if video call is active. To check the status of the video call,
Telephony API (telephony_call_get_type) is called, and telephony privilege is necessary to use telephony API.
List of API changes
API:  public void AddCategory(ContentCategory category, Bundle extraData)
Description: add http://tizen.org/privilege/telephony to use camera content category.
- ACR: TCSACR-150
Added 
+         
+       <privilege>http://tizen.org/privilege/telephony</privilege>
=> Updated ACR Changes [TCSACR-150] [ACR-1243]

docs/application/native/guides/multimedia/face-detection.md, docs/application/native/guides/multimedia/image-recognition.md
Signed-off-by: Tae-Young Chung <ty83.chung@samsung.com>
Update face-detection and image-recognition.
- image_util_decode_jpeg() is deprecated from Tizen 5.0. Instead, use image_util_decode_create() and imge_util_decode_run().
ACR: http://suprem.sec.samsung.net/jira/browse/ACR-1123
=> Update face-detection.md and image-recognition.md

docs/application/native/guides/internationalization/i18n.md
Signed-off-by: Lukasz Pik <lu.pik@samsung.com>
- Add guides for plural format module in base-utils
- ACR: ACR-1079 http://suprem.sec.samsung.net/jira/browse/ACR-1079
=> [base-utils][ACR-1079] Add guides for plural format module

docs/application/native/guides/multimedia/sound-manager.md
Signed-off-by: Sangchul Lee <sc11.lee@samsung.com>
Add new APIs to get device state. The running state of a device represents whether an audio stream is routed to the device or not. User can notice the state by using these new APIs.
ACR-1147
=> [sound-manager][ACR-1147] Add guide for new device state

docs/open-source-project/release-notes/tizen-5-0-m1.md
- Fix typo
- Remove the word public/internal
- D-bus, dbus, Dbus => D-Bus
- edbus => EDbus
- Gdbus => GDBus
need to check this release note entirely if there are another typo, grammatical error.
also need to check if the use of API, APIs and API set is correct.
=> Fix Tizen 5.0 M1 Release note 

docs/application/native/guides/internationalization/i18n.md
Add notes due to deprecation of some functions, which utilize locale parameters
- ACR: ACR-1182
http://suprem.sec.samsung.net/jira/browse/ACR-1182
=> [ACR-1182]Change documentation due to locale changes

docs/application/native/guides/security/privacy-related-permissions.md
Signed-off-by: Ernest Borowski <e.borowski@partner.samsung.com>
Fixed dependency of Privacy privileges.
PrivacyPrivilegeManager was introduced in tizen 4.0, but inside docs there is tizen 2.3.x.
This patch should be cherry-picked to all branches.
=> [Native/guide] Fix Privacy related prermissions dependency in docs

docs/application/native/guides/device/system.md, docs/application/native/tutorials/details/app-filtering.md
Change-Id: I105e158139c2a9cd792fe06a05ea56481c0432c3
Signed-off-by: Konrad Kuchciak <k.kuchciak@samsung.com>
- Add Peripheral-IO feature keys
- Use colon instead of period after the sentence containing a words like follow, following and so on.
- ACR: ACR-1271
=> [ACR-1271] Add Peripheral-IO feature keys

docs/application/native/guides/multimedia/media-controller.md
Add guide for ACR-1235, ACR-1237, ACR-1252 and ACR-1268
Add guide for new APIs to send commands, to reply callback, to support playlist and metadata and to send custom event and reply callback.
The APIs support Tizen 4.0 and higher for Mobile.
- ACR: ACR-1235, ACR-1237, ACR-1252 and ACR-1268
http://suprem.sec.samsung.net/jira/browse/ACR-1235
http://suprem.sec.samsung.net/jira/browse/ACR-1237
http://suprem.sec.samsung.net/jira/browse/ACR-1252
http://suprem.sec.samsung.net/jira/browse/ACR-1268
=> Add guide for ACR-1235, ACR-1237, ACR-1252 and ACR-1268

docs/application/native/guides/app-management/event.md
The Event Broadcast and Subscription guide was revised because it is hard to read that the width of table is wilder than that of contents.
You can see ## Platform Event Types section,  which is composed a big table on https://developer.tizen.org/node/21539/revisions/62839/view.
=> Revise the Event Broadcast and Subscription guide to divide a table

docs/open-source-project/developing/setting-up.md
Add guide in case of not cloning 'scm/meta/build-config' git.
If 'scm/meta/build-config' git is not cloned in working directory, every line which starts with "buildconf=./scm/meta/build-config" should be removed
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Add "Note" in case of build-config absense

docs/application/native/tutorials/details/sec-privileges.md
- The privilege http://tizen.org/privilege/permission.check is added by ACR-1296, but was missing in sec-privileges.md hence update the document.
=> Update native privilege document

docs/application/dotnet/guides/connectivity/nfc.md
Fix wrong privilege level information in NFC guide
http://tizen.org/privilege/nfc.admin
this privilege level is platform level on Native and .Net Application
https://github.com/Samsung/TizenFX/issues/462
None
=> Fix wrong privilege level information

docs/application/dotnet/guides/app-management/data-control.md
The links for TizenFX API Reference were xxx.l so I fixed the typo from xxx.l to xxx.html on Data Control page.
=> Fix broken links on Data Control page

docs/application/native/guides/ui/efl/mobile/component-multibuttonentry.md, docs/application/native/guides/ui/efl/mobile/component-plug.md, docs/application/native/guides/ui/efl/mobile/component-segmentcontrol.md, docs/application/native/guides/ui/efl/wearable/component-plug.md, docs/application/web/api/toc.xml
Related update with #509.
- As below file names are changed the links in the guide pages should be updated, too
- group__Multibuttonentry.html -> group__Elm__Multibuttonentry.html
- group__Plug.html -> group__Elm__Plug.html
- group__Elm__SegmentControl.html -> group__Elm__Segment__Control.html
- As some pages are added in Native API, toc.xml file should be updated
- group__Elm__Interface__Atspi__Text.html
- group__longpress__group.html
- group__softcursor__group.html
=> Fix some links to API files and update toc.xml according to #509

docs/application/web/api/5.0/device_api/mobile/tizen/power.html, docs/application/web/api/5.0/device_api/wearable/tizen/power.html
Since Tizen 5.0 user can check wheter device supports changing display state.
Native ACR:   [ACR-1304]
WebAPI ACR: [TWDAPI-197]
Signed-off-by: Rafal Walczyna <r.walczyna@partner.samsung.com>
Added http://tizen.org/feature/display.state to Related Feature section
---
Native ACR:   [ACR-1304]
WebAPI ACR: [TWDAPI-197]
=> [Power] Adding information about display.state feature

docs/application/web/guides/device/system-information.md
WIFI_NETWORK properties listener triggers before change of some values.
Example code to get proper values has been added.
Signed-off-by: Rafal Walczyna <r.walczyna@partner.samsung.com>
Example code to get proper values from property value change listener in SystemInfo module been added.
[TDAF-765]
--
=> [Web][Guide] Add remark about Wi-Fi properties change

docs/application/web/api/2.4/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm, docs/application/web/api/2.4/ui_fw_api/ui_fw_api_cover.htm, docs/application/web/api/3.0/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm, docs/application/web/api/3.0/ui_fw_api/ui_fw_api_cover.htm, docs/application/web/api/4.0/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm, docs/application/web/api/4.0/ui_fw_api/ui_fw_api_cover.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm, docs/application/web/api/5.0/ui_fw_api/ui_fw_api_cover.htm
There are some broken links from web api reference files to web guide.
So I fixed the broken links.
- From API Reference files, the links to guide/training should should go to TD, not to md file.
=> Fix broken links in Web API Reference

docs/application/native/guides/multimedia/media-content.md, docs/application/native/guides/multimedia/thumbnail-images.md
If the width and height of the thumbnail to be generated exceeds the original resolution,
the value changes to the original resolution instead of returning the error.
- ACR: ACR-1327
=> Modify the thumbnail size instead of returning the error

docs/application/toc_all.md
I should change the menu tree of native API reference, but I changed dotnet's menu tree.
I moved  dotnet's submenus to native.
=> Fix menu tree for dotnet API reference

docs/application/native/guides/applications/efl-ui-app.md
Even if the background-network is declared, the running application is freezed if the network is not connected. (Since Tizen 4.0)
=> Add a note about background-category

docs/application/dotnet/getting-started/sec-privileges.md, docs/application/dotnet/index.md, docs/application/native/tutorials/details/details.md, docs/application/native/tutorials/details/old-versioned-sec-privileges.md, docs/application/native/tutorials/details/sec-privileges.md, docs/application/toc_all.md, docs/application/web/tutorials/old-versioned-sec-privileges.md, docs/application/web/tutorials/overview.md, docs/application/web/tutorials/sec-privileges.md
The API version restriction of privileges are deprecated since Tizen platform 5.0 and 
API versions were removed from privilege document. 
However, there are apps that are being developed in a lower version(< 5.0) somewhere, and 
we need to provide information for them, so I added pages for that.
=> Add privilege tables with API version

docs/application/dotnet/getting-started/app-filtering.md
Update App filtering description page under getting-started.
- Merged mobile & wearable table into one, as dotnet doesn't classify them.
- Update "since" info.
- Remove unnecessary tags.
=> Update dotnet app filtering page

docs/application/web/api/5.5/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/5.5/device_api/wearable/tizen/bluetooth.html, docs/application/web/guides/connectivity/bluetooth.md
Some of the HDP functions are deprecated. There is no replacement because of no usecase and supported devices. It should be also deprecated in our API.
Elements marked as deprecated:
enum BluetoothProfileType { "HEALTH" };
enum BluetoothHealthChannelType { "RELIABLE", "STREAMING" };
BluetoothProfileHandler getBluetoothProfileHandler(BluetoothProfileType profileType) raises(WebAPIException);
[NoInterfaceObject] interface BluetoothHealthProfileHandler : BluetoothProfileHandler
readonly attribute BluetoothProfileType profileType;
[NoInterfaceObject] interface BluetoothHealthProfileHandler : BluetoothProfileHandler
void registerSinkApplication(unsigned short dataType, DOMString name, BluetoothHealthApplicationSuccessCallback successCallback, optional ErrorCallback? errorCallback) …
=> [5.5][bluetooth][deprecated] Deprecate HDP(Health Device Profile) APIs

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_viewSwitcher.htm
[Problem] getActiveIndex method signature had return value type missing
[Solution] Add missing return value type
=> viewSwitcher: Add missing return type

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_swipelist.htm
[Problem] SwipeList options table had different layout than another pages
[Solution] Unify table layout with rest of documentation
=> SwipeList: Unify options table with rest of documentation pages

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Listview.htm
[Problem] Documentation contained mixed HTML and JS code in examples
[Solution] Code examples were separated
=> Mobile, Listview: Separate JS and HTML code in examples

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm
[Problem] Code snippets with examples have mixed HTML markups and JS code,
it makes that the examples are unreadable for users.
[Solution] Separation into two blocks improves readability.
Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>
=> CircularIndexScrollbar: Mixed HTML & JS

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_FloatingActions.htm
[Problem] Documentation contained mixed HTML and JS code in examples
[Solution] Code examples were separated
=> Mobile, FloatingActions: Separate JS and HTML code in examples

docs/application/web/api/5.5/device_api/mobile/tizen/content.html, docs/application/web/api/5.5/device_api/tv/tizen/content.html, docs/application/web/api/5.5/device_api/wearable/tizen/content.html
[5.5][content] Deprecate StorageType enum and attributes.
ACR-TWDAPI-203
deprecated:
- enum ContentDirectoryStorageType
- attribute ContentDirectory.storageType
N/A
-ACR: TWDAPI-203
=> [5.5][content] Deprecate StorageType enum and attributes.

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm
[Problem] There were no return types in method signatures
[Solution] Add missing return types
=> Checkbox add missing return types and separate HTML and JS code in examples

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Drawer.htm
[Problem]  Documentation contained mixed HTML and JS code in examples,
Method return types in signatures were missing
[Solution] Code examples were separated and missing return types were added
=> Mobile, Drawer: Improve widget documentation readability

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Expandable.htm
[Issue] Documentation contained mixed HTML and JS code in examples,
Method return types in signatures were missing
[Solution] Code examples were separated and missing return types were added
=> Expandable: Improve widget documentation readability

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_indexscrollbar.htm
[Problem] Code snippets with examples have mixed HTML markups and JS code,
it makes that the examples are unreadable for users.
[Solution] Separation into two blocks improves readability.
Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>
=> IndexScrollbar: Mixed HTML & JS

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Drawer.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Navigation.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Progress.htm
[Problem] Some methods did not have a "return section" in their description.
[Solution] Add missing sections.
=> Filling gaps in the "return value" section.

docs/application/web/api/5.5/device_api/mobile/tizen/keymanager.html, docs/application/web/api/5.5/device_api/tv/tizen/keymanager.html, docs/application/web/api/5.5/device_api/wearable/tizen/keymanager.html
New attribute informing whether data stored under alias
is password protected has been added.
[ACR] TWDAPI-194
Signed-off-by: Rafal Walczyna <r.walczyna@partner.samsung.com>
New attribute informing whether data stored under alias
is password protected has been added.
None
[ACR] TWDAPI-194
=> [KeyManager] Add isProtected attribute description

docs/application/tizen-studio/setup/prerequisites.md
The JDK download URL was changed from Java SE 9 to Java SE 8 because Java SE 9 has reached end of support.
=> Change JDK download URL from Java SE 9 to Java SE 

docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_GridView.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_IndexScrollBar.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_PageIndicator.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Popup.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Radio.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SearchInput.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_SectionChanger.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Slider.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Tabs.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_TextEnveloper.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_TextInput.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_ToggleSwitch.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circleprogressbar.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_drawer.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_pageindicator.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_popup.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_sectionchanger.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_snaplistview.htm
[Problem] HTML and JS code are mixed in documentation
[Solution] Add label "HTML code" and "JS code" if code snippet contains both JS and HTML code.
Signed-off-by: Dominik Orliński <d.orlinski@samsung.com>
=> Seperate HTML and JS code

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html, docs/application/web/guides/multimedia/media-controller.md
Add documentation for WebAPI content age rating feature.
+ Add MediaControllerContentAgeRating enum.
+ Add age rating attribute to playback info interface.
+ Add playback age rating setter to server interface.
N/A
ACR: http://suprem.sec.samsung.net/jira/browse/TWDAPI-207
=> [TWDAPI-207] Content age rating for mediacontroller playback.

docs/application/web/api/5.0/ui_fw_api/ui_fw_api_cover.htm, docs/application/web/guides/tau/download-tau.md
[Problem]  TAU documentation not up to date with latest TAU release.
[Solution] Added TAU presentation page link, github url and updated
clonning information
=> Update TAU documentation with links and new source code url

docs/application/web/api/2.3.2/ui_fw_api/mobile/ns_widget_mobile_MultimediaView.htm
- Add the missed <head> tag in old Web API Reference.
=> [Web API Reference] Add the missed <head> tag

docs/application/web/api/5.5/device_api/tv/tizen/systeminfo.html, docs/application/web/api/5.5/device_api/tv/tizen/tvwindow.html
[TWDAPI-206][5.5][TV][tvwindow][systeminfo] 
Brief description and purpose
Brief description
Adding 1 attribute to SystemInfoVideoSourceInfo object:
signal - boolean value representing whether there is signal provided or not.
Purpose
Provide functionality that will be no longer supported by ex.B2BBroadcast plugins
Complete ACR contents
Headers containing changes
systeminfo.html
List of API changes and corresponding descriptions:
Adding 1 attribute to SystemInfoVideoSourceInfo object.
ACR: TWDAPI-206
=> Add information whether there is signal or not to SystemInfoVideoSourceInfo object

docs/application/web/api/3.0/ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm, docs/application/web/api/4.0/ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm, docs/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm
`</code>` were missing in ui_fw_api/Mobile_UIComponents/mobile_Checkbox.htm files,
causing display error on docs staging page.
=> Add missing </code>

docs/application/web/api/5.5/device_api/mobile/tizen/content.html, docs/application/web/api/5.5/device_api/tv/tizen/content.html, docs/application/web/api/5.5/device_api/wearable/tizen/content.html, docs/application/web/guides/data/data-filter.md, docs/application/web/guides/data/stored-content.md
Few properties were marked as readonly since 5.5 with below ACR, but the code examples
still existed in API documentation which used to modify the properties now marked as
readonly.
Examples were fixed to use still editable attributes only.
[ACR] http://suprem.sec.samsung.net/jira/browse/TWDAPI-203
=> [Content] [5.5] Cleaning code examples from modification of readonly members

docs/application/web/api/5.5/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.5/device_api/wearable/tizen/mediacontroller.html, docs/application/web/guides/multimedia/media-controller.md
Add documentation for WebAPI content type feature.
Add API to get and set playback content type.
For instance,
+ Add MediaControllerContentType enum.
+ Add MediaControllerServer::updatePlaybackContentType() method.
+ Add MediaControllerPlaybackInfo::contentType attribute.
-ACR: TWDAPI-219
=> [TWDAPI-219][MediaController] Get/Set playback content type.

docs/application/dotnet/api/xamarin-forms-limitations.md
WebView feature of Xamarin.Forms is not supported on TV, so the corresponding document is updated.
Descriptions in 'tizen-docs/docs/application/dotnet/api/xamarin-forms-limitations.md' are updated as follow:
- Before: Some properties of the WebView class are limited.
- After: Whole WebView class is limited.
=> Update 'Current Xamarin.Forms Limitations' for TV

docs/application/toc_all.md, docs/application/vscode-ext/dotnet.md, docs/application/vscode-ext/index.md
Related with https://github.com/Samsung/tizen-docs/pull/743,
it is required to separate the prerequisites part from VS Code Extension for .NET page.
=> Separate VS Code Extension Prerequisites page

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_button.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_checkbox.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circleprogressbar.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_circularindexscrollbar.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_datepicker.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_list.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_numberpicker.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_pageindicator.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_popup.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_processing.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_sectionchanger.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_selector.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_slider.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_snaplistview.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_timepicker.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_toggleswitch.htm, docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_virtuallist.htm
Issue: https://github.com/Samsung/TAU/issues/199
Problem: No links for wearable examples
Solution: Add links in documentation
=> Add links for wearable examples (5.0)

docs/application/tizen-studio/setup/prerequisites.md
With reference to the following mail chain, I have modified the required information. 
I have removed the email addresses purposefully and just kept the names. 
_______________
Hello Nawab,
Your understanding is correct that we will only support Nvidia.
Thanks & Regards,
Manish
--------- Original Message ---------
Sender : Nawab Ahmad Reshi
Date : 2019-07-22 17:57 (GMT+5:30)
Title : RE: Request to update prerequisites documentation
Hello,
Thanks for the information. 
We will do the required changes and send a PR to update current live documentation and simultaneously update our revamped page that is expected to go live in coming days replacing the current live document.
In this context, we need to remove the following information from the page:
ATI
RADEON HD 4850, RADEON HD 5450
Intel
HD …
=>  Removed ATI and Intel Graphics card information

docs/application/tizen-studio/web-tools/debugging.md, docs/application/toc_all.md
Remove Dynamic Analyzer from Tizen Studio > Web Tools.
Requested by dongkyun.s@samsung.com
SWAP part> 
- WSP (web startup profiling):
- swap-modules:
- wsp: remove module https://review.tizen.org/gerrit/#/c/platform/kernel/swap-modules/+/191136/
- swap-manager:
- Remove web startup profiling (WSP) feature https://review.tizen.org/gerrit/#/c/platform/core/system/swap-manager/+/191135/
- Web Profilling:
- swap-modules:
- wsi: remove feature https://review.tizen.org/gerrit/#/c/platform/kernel/swap-modules/+/153910/
- swap-manager:
- wsi: remove feature https://review.tizen.org/gerrit/#/c/platform/core/system/swap-manager/+/153909/
=> Remove Dynamic Analyzer from Tizen Studio > Web Tools.

docs/application/web/api/5.5/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/5.5/device_api/wearable/tizen/humanactivitymonitor.html
[Bug] There was an issue with type of timestamp member of HumanActivitySleepMonitorData
timestamp was described as long value, but also in milliseconds. 'long' type is not wide
enough to keep the current timestamp in milliseconds, so it need to be extended.
Backward compatibility is kept, only the range of values was extended.
[ACR] http://suprem.sec.samsung.net/jira/browse/TWDAPI-228
#806 is the modification of legacy versions also
=> [HAM][3.0] Changed type of timestamp of HumanActivitySleepMonitorData

docs/application/web/api/3.0/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/3.0/device_api/wearable/tizen/humanactivitymonitor.html, docs/application/web/api/4.0/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/4.0/device_api/wearable/tizen/humanactivitymonitor.html, docs/application/web/api/5.0/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/5.0/device_api/wearable/tizen/humanactivitymonitor.html
Changed type of timestamp of HumanActivitySleepMonitorData
[Bug] There was an issue with type of timestamp member of HumanActivitySleepMonitorData
timestamp was described as long value, but also in milliseconds. 'long' type is not wide
enough to keep the current timestamp in milliseconds, so it need to be extended.
Backward compatibility is kept, only the range of values was extended.
[ACR] http://suprem.sec.samsung.net/jira/browse/TWDAPI-228
=> [HumanActivityMonitor][3.0] Changed type of timestamp

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_viewSwitcher.htm
- Add missing information about deprecation of ViewSwitcher component
- Component has been replaced with SectionChanger since Tizen 5.0
=> Mark ViewSwitcher component as deprecated

docs/application/tizen-studio/setup/prerequisites.md
JDK9 is no longer supported on oracle website.
For instance,
- Remove JDK9 from prerequisite list.
=> Remove JDK9 from prerequisites

docs/application/tizen-studio/rt-ide/get-started/overview.md
Remove JDK9 from rt-ide prerequisites because oracle doesn't support the JDK9.
=> Remove JDK9 from rt-ide prerequisites

docs/application/dotnet/index.md, docs/application/vstools/install.md
We have links to Visual Studio Tools for Tizen, but it is based on old version, Visual Studio **2017**.
For now, the latest version is Visual Studio 2019, and it has different link.
Visual Studio **2017** : https://marketplace.visualstudio.com/items?itemName=tizen.VisualStudioToolsforTizen
&nbsp;&nbsp;=> This link is guided in the document.
Visual Studio **2019** : https://marketplace.visualstudio.com/items?itemName=tizen.VSToolsforTizen
Asking @winstone77's opinion, 
I got the suggestion that it'd be better to remove the links to Visual Studio Marketplace 
as the tool itself guide the user to proper version link (2017 or 2019).
So the links are removed in this PR.
=> Remove old link to Visual Studio Marketplace for Tizen

docs/application/web/api/5.5/device_api/mobile/tizen/download.html, docs/application/web/api/5.5/device_api/tv/tizen/download.html, docs/application/web/api/5.5/device_api/wearable/tizen/download.html, docs/application/web/guides/connectivity/download.md
Correcting exceptions for cancel, pause and resume methods.
NotFoundError and TypeMismatchError exceptions are removed from above functions.
Abandon method added.
ABANDONED value added to DownaloadState enum.
[ACR] http://suprem.sec.samsung.net/jira/browse/TWDAPI-222
Signed-off-by: Arkadiusz Pietraszek <a.pietraszek@partner.samsung.com>
=> [Download] Download module exception correction

docs/application/web/api/2.4/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/2.4/device_api/mobile/tizen/messaging.html, docs/application/web/api/3.0/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/3.0/device_api/mobile/tizen/messaging.html, docs/application/web/api/3.0/device_api/wearable/tizen/mediacontroller.html, docs/application/web/api/4.0/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/4.0/device_api/mobile/tizen/messaging.html, docs/application/web/api/4.0/device_api/wearable/tizen/mediacontroller.html, docs/application/web/api/5.0/device_api/mobile/tizen/mediacontroller.html, docs/application/web/api/5.0/device_api/mobile/tizen/messaging.html, docs/application/web/api/5.0/device_api/tv/tizen/mediacontroller.html, docs/application/web/api/5.0/device_api/wearable/tizen/mediacontroller.html
Fixing few issues in messaging and mediacontroller:
removed not necessary errorCallback descriptions (messaging)
organized code examples similar as it was on 5.5 in PR #834
small fixes of variable names in mediacontroller module
=> [mediacontroller][messaging] fixes in webapi

docs/iot/get-started/overview.md, docs/iot/guides/zigbee.md
Removed 'the' from unique nouns.
e.g.
- Tizen, Tizen 3.x, 4.x, 5.x
- Tizen Mobile, Tizen Mobile 3.x, 4.x, 5.x
- Tizen TV
- Tizen Wearable
- Tizen IoT
- Tizen IVI
- Tizen .NET
- Tizen SDK
- Tizen Store
- Tizen Studio, Tizen Studio 2.x, 3.x
=> [IoT] Remove 'the' from unique nouns

CONTRIBUTING.md, README.md, styleguide/naming-rules.md
I added naming rules for Tizen terms because Tizen brand and Tizen terms are used in various formats.
=> Add naming rules for Tizen terms

docs/application/tizen-studio/setup/prerequisites.md, docs/application/vstools/install.md
Signed-off-by: seok.oh <seok.oh@samsung.com>
- Change prerequisite of TS (Ubuntu x86 arch supporting is removed.)
- Change prerequisite of VS (Tizen-5.5 is suppoted by only VS2019)
=> Change prerequisite for TS and VS.

docs/platform/toc_all.md
Remove Tizen RT from the menu tree.
> We will rollback Tizen RT is updated.
=> Remove Tizen RT from menu tree

docs/application/web/api/6.0/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/6.0/device_api/wearable/tizen/humanactivitymonitor.html, docs/application/web/guides/sensors/ham.md
Adding accumulative pedometer data to HumanActivityPedometerData to enable getting data gathered from device boot by getHumanActivityData function
[ACR]
http://suprem.sec.samsung.net/jira/browse/TWDAPI-251
=> [humanactivitymonitor] Add accumulative data to HumanActivityPedometerData

docs/application/web/api/6.0/device_api/tv/tizen/tvwindow.html
[6.0][tvwindow] Adding PictureSizeType implementation instead of AspectRatio
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-252
=> [6.0][tvwindow] Adding PictureSizeType implementation instead of AspectRatio

docs/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm, docs/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm
Value "ellipsis" for option "ellipsisEffect" in Marquee widget
has been deprecated. New guiedline defines only "gradient" effect
as marquee border effect.
no issue
no ACR
=> Web UI (TAU): Deprecated option "ellipsis" in Marquee widget

docs/application/toc_all.md
In toc-all.md file, 
the link to app-filtering file in dotnet is leading to app-filtering in native.
=> Fix wrong link in toc_all.md

docs/application/native/guides/index.md
According to ACR-1532 The Ui-Viewmgr has been deprecated.
N/A
- https://code.sec.samsung.net/jira/browse/ACR-1521
=> Delete ui-viewmgr Docs.

docs/application/native/get-started/wearable-watch/first-app-watch.md, docs/application/native/get-started/wearable-widget/first-app-widget.md, docs/application/native/get-started/wearable/first-app.md, docs/application/web/get-started/wearable-watch/first-app-watch.md, docs/application/web/get-started/wearable-widget/first-app-widget.md, docs/application/web/get-started/wearable/first-app.md
- Cause: If the OS version of the target device is lower than the API version of the package, the package is not installed.
- Resolve: I reemove Device Manager screenshots showing the platform version.
- ToDo: I will update screenshots later so I didn't delete image files. 
=> Remove Device Manager screenshots showing the platform version

docs/application/native/guides/ui/efl/wearable/component-icon.md
In Wearable profile, elm_icon does not support functions related to the standard icon.
Remove the contents of the docs associated with it.
=> Wearable.Icon: Remove unsupported content related to standard icon

docs/application/web/api/6.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/6.0/device_api/tv/tizen/bluetooth.html, docs/application/web/api/6.0/device_api/wearable/tizen/bluetooth.html
[6.0] Bluetooth - fixed descriptions and code examples
* there were descriptions refering deprecated features
* uuid used in code examples was not valid, thus fixed
=>  [6.0] Bluetooth - fixed descriptions and code examples

docs/application/native/tutorials/details/native-removed-history.md
privilege_info_get_privacy_privilege_status() will be removed since 6.0, deprecated since 5.0
=> Adds newly removed function via ACR-1557

docs/application/web/api/5.5/w3c_api/w3c_api_tv.html
In w3c_api_tv.html, some \<a> tags are missing closing tags.
- Issue https://github.sec.samsung.net/RS8-TIZENWEBSITE/docs.tizen.org/issues/278?email_source=notifications&email_token=AAAHCPWEHWZNGGAOI5M2GIDRUXQODA5CNFSM4AAKQLFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOAAFL7PQ
=> [Web API] Add missing closing tag

docs/application/web/api/6.0/w3c_api/w3c_api_tv.html
In w3c_api_tv.html, some \<a> tags are missing closing tags.
Same fix with https://github.com/Samsung/tizen-docs/pull/1134 for tizen_6.0_prepare.
- Issue https://github.sec.samsung.net/RS8-TIZENWEBSITE/docs.tizen.org/issues/278?email_source=notifications&email_token=AAAHCPWEHWZNGGAOI5M2GIDRUXQODA5CNFSM4AAKQLFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOAAFL7PQ
=> [6.0][Web API]Add missing closing tag

docs/platform/get-started/open-source-project.md, docs/platform/toc_all.md
- Issue: platform/index.md was not used after the landing page of Platform was changed to what-is-tizen/overview.md.
- Resolution: The content is fit on the 'get started' page so I moved it to platform/get-started and changed the name.
=> Change platform/index.md to the first page of Platform > Get Started.

docs/application/toc_all.md
Changed menu tree for Visual Studio for Mac Extension for Tizen.
When there is no child, the page has its own link.
=> Change menu tree for Visual Studio for Mac Extension for Tizen

docs/application/native/guides/app-management/app-preferences.md
Parameter "previous_value" is wrong. The user data is passed.
So the code snippet is edited.
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> Fix the parameter on preference_set_changed_cb

docs/application/native/guides/security/privilege.md
Remove guide for removed API privilege_info_get_privacy_privilege_status().
- ACR: https://code.sec.samsung.net/jira/browse/ACR-1555
=> [Security][ACR-1555] Remove guide for removed API

docs/application/get-started/iot.md
Updated the link to the tutorial page for  'Getting started with Raspberry PI 3&4'.
(from http://tizenschool.org/tutorial/137 to http://tizenschool.org/tutorial/191)
For instance,
-  ...
=> Change the link to the tutorial page

docs/application/native/guides/security/privilege.md
- Remove privacy privilege status related description.
privilege-info API to get privacy privilege status was removed by ACR-1555.
=> [Security] Remove removed API's description

styleguide/style.md
- We decided to use the verb form in the headings instead of gerund form.
I add it to the Style Guide.
- (minor) Giving heading style to capitalization rule.
=> Add Heading rule to use Verb form to Style Guide

docs/application/web/api/2.3.2/device_api/wearable/tizen/alarm.html, docs/application/web/api/2.3.2/device_api/wearable/tizen/push.html, docs/application/web/api/2.4/device_api/mobile/tizen/alarm.html, docs/application/web/api/2.4/device_api/mobile/tizen/push.html, docs/application/web/api/3.0/device_api/mobile/tizen/alarm.html, docs/application/web/api/3.0/device_api/mobile/tizen/push.html, docs/application/web/api/3.0/device_api/tv/tizen/alarm.html, docs/application/web/api/3.0/device_api/tv/tizen/push.html, docs/application/web/api/3.0/device_api/wearable/tizen/alarm.html, docs/application/web/api/3.0/device_api/wearable/tizen/push.html, docs/application/web/api/4.0/device_api/mobile/tizen/alarm.html, docs/application/web/api/4.0/device_api/mobile/tizen/push.html, docs/application/web/api/4.0/device_api/tv/tizen/alarm.html, docs/application/web/api/4.0/device_api/tv/tizen/push.html, docs/application/web/api/4.0/device_api/wearable/tizen/alarm.html, docs/application/web/api/4.0/device_api/wearable/tizen/push.html, docs/application/web/api/5.0/device_api/mobile/tizen/alarm.html, docs/application/web/api/5.0/device_api/mobile/tizen/push.html, docs/application/web/api/5.0/device_api/tv/tizen/alarm.html, docs/application/web/api/5.0/device_api/tv/tizen/push.html, docs/application/web/api/5.0/device_api/wearable/tizen/alarm.html, docs/application/web/api/5.0/device_api/wearable/tizen/push.html, docs/application/web/api/5.5/device_api/mobile/tizen/alarm.html, docs/application/web/api/5.5/device_api/mobile/tizen/humanactivitymonitor.html, docs/application/web/api/5.5/device_api/mobile/tizen/push.html, docs/application/web/api/5.5/device_api/tv/tizen/alarm.html, docs/application/web/api/5.5/device_api/tv/tizen/push.html, docs/application/web/api/5.5/device_api/wearable/tizen/alarm.html, docs/application/web/api/5.5/device_api/wearable/tizen/humanactivitymonitor.html, docs/application/web/api/5.5/device_api/wearable/tizen/push.html
Some items are deprecated 2 or earlier version since generated html
but are still in the documentation.
This commit removes these items and its descriptions.
Also fixes some minor issues
=> [fix] Remove items (and it's descriptions) deprecated 2+ versions earlier

docs/application/web/api/toc.xml
There was a mismatch between the toc.xml for Native API files and the toc.xml on the github.
So for now there are some menu bars for non-existent API pages, 
and some other menu bars for added API pages are missing.
=> Sync toc.xml for Native API reference with the latest

docs/application/web/guides/multimedia/media-controller.md
The order of RequestReply attributes was incorrect in one of code examples. This commit fixes this issue.
=> Fix the order of RequestReply attributes

docs/application/native/tutorials/details/native-removed-history.md
Following enums are newly removed.
- CURLE_SSL_CACERT
- CURLOPT_DNS_USE_GLOBAL_CACHE
=> Adds newly removed enums of Curl

docs/application/dotnet/guides/security/privacy-related-permissions.md, docs/application/native/guides/security/privacy-related-permissions.md, docs/application/web/guides/security/privacy-related-permissions.md
The note was added by https://github.com/Samsung/tizen-docs/pull/1056 because of the popup behavior change. But in the end of implementation, 'group mode' launch wasn't applied to component based app hence remove that case from the description.
=> Fix description about PPM popup behavior change

docs/application/tizen-studio/setup/prerequisites.md
According to "OS and System Requirements"
the at least supported version for Ubuntu is 16.04.
So I remove the 14.04 description in "Driver".
- https://github.com/Samsung/tizen-docs/issues/1291
=> Change Version Info in Tizen Studio setup

docs/application/dotnet/guides/nui/nui-components/Slider.md
Add SliderValueChangedEventArgs class and SliderSlidingFinishedEventArgs
class.
Deprecate Slider.ValueChangedArgs class and Slider.SlidingFinishedArgs
class.
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [NUI][TCSACR-345] Add and deprecate Slider EventArgs classes

docs/application/dotnet/guides/nui/nui-components/Button.md, docs/application/dotnet/guides/nui/nui-components/CheckBox.md, docs/application/dotnet/guides/nui/nui-components/RadioButton.md
Add ClickedEventArgs class.
Deprecate Button.ClickEventArgs class.
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [NUI][TCSACR-349] Add and deprecate Button EventArgs classes

docs/application/dotnet/samples/appfw/overview.md, docs/application/dotnet/samples/general/overview.md, docs/application/dotnet/samples/ui/overview.md, docs/application/dotnet/samples/watch/overview.md
Update the sample links in .NET samples from developer.tizen. to docs.tizen.
- Issue https://github.com/Samsung/tizen-docs/issues/1269
=> Change Sample URLs in .NET Samples

docs/application/web/api/3.0/device_api/tv/index.html, docs/application/web/api/3.0/device_api/tv/tizen/tvinfo.html, docs/application/web/api/4.0/device_api/tv/index.html, docs/application/web/api/4.0/device_api/tv/tizen/tvinfo.html, docs/application/web/api/5.0/device_api/tv/index.html, docs/application/web/api/5.0/device_api/tv/tizen/tvinfo.html, docs/application/web/api/5.5/device_api/tv/index.html, docs/application/web/api/5.5/device_api/tv/tizen/tvinfo.html, docs/application/web/api/6.0/device_api/tv/index.html, docs/application/web/api/6.0/device_api/tv/tizen/tvinfo.html
Issue: https://github.com/Samsung/tizen-docs/issues/1335
Fixed descriptions of TV modules - they were mixed up.
=> [TV] Fixed descriptions for TV modules

docs/application/dotnet/guides/nui/tizenshell.md
Changes:
```
using Tizen.NUI.WindowSystem;
Shell.TizenShell tzsh = new Shell.TizenShell();
```
produces compilation error: 
The type or namespace name 'Shell' could not be found (are you missing a using directive or an assembly reference?) [NUI_tzsh]csharp(CS0246)
=> [NUI] Window system

docs/application/dotnet/guides/nui/quickpanelclient.md
Code examples don't work on Visual Studio Code (Ubuntu). Shell namespace is not accessible.
=> [NUI] WindowSystem - fixed examples

CONTRIBUTING.md
I changed http:// to https:// in the tizen-docs repo URL to push commit without warning message.
We can open the URL without `.git` on any web browser. I removed it to reduce typing.
=> Change http:// to https:// in the tizen-docs repo URL

docs/application/native/guides/ui/efl/learn-edc-part.md
In edc, SOURCE keyword is not yet supported for max,min of image part.
Therefore, delete description related to SOURCE.
=> native/ui/efl: Delete description of unsupported features

docs/application/web/api/2.3.2/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/2.4/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/3.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/3.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/4.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/4.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/5.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/5.0/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/5.5/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/5.5/device_api/wearable/tizen/bluetooth.html, docs/application/web/api/6.0/device_api/mobile/tizen/bluetooth.html, docs/application/web/api/6.0/device_api/tv/tizen/bluetooth.html, docs/application/web/api/6.0/device_api/wearable/tizen/bluetooth.html
Some functions may fail when a connection with a remote GATT server is being established. This commit adds a
remark about it.
=> [WebAPI][Bluetooth] Added remark about BT stack business

docs/application/tizen-studio/setup/openjdk.md
After user query, adding the note to help readers know that JAVA is managed and bundled with Tizen Studio 3.7 and onwards.
=> Add compulsory note to JDK to give clarity to readers.

docs/application/tizen-studio/native-tools/ui-builder/component-attributes.md, docs/application/web/api/6.0/ui_fw_api/Mobile_UIComponents/mobile_Navigation.htm, docs/application/web/api/6.0/ui_fw_api/Mobile_UIComponents/mobile_PanelChanger.htm, docs/application/web/api/6.0/ui_fw_api/Wearable_UIComponents/wearable_drawer.htm
Fix the issues under ui_fw_api and Tizen Studio, from #1401 
- Issue https://github.com/Samsung/tizen-docs/issues/1401
=> Fix link errors in ui_fw_api and tizen-studio

docs/application/native/guides/machine-learning/machine-learning-inference.md, docs/application/native/guides/machine-learning/machine-learning-training.md
This patch adds documentation about API change in `ml_train_*` api.
**Major Changes proposed in this PR:**
- Add description about newly added layer
- Add how-to for inference
- Fix wrong description
**related ACR**
- [ACR-1613](https://code.sec.samsung.net/jira/browse/ACR-1613)
Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>
=> [ML_TRAIN][6.5 ACR] Change ML_TRAIN_ documentation

docs/platform/porting/system.md
Added porting guide for stability-monitor.
Continuation of https://github.com/Samsung/tizen-docs/pull/1417
=> Add guide for stability-monitor

docs/application/native/api/overview.md, docs/application/web/api/index.md
The old version API reference was moved from TD to Docs because of the security issue of TD.
=> Add API Reference 2.3.1 & 2.3

docs/application/native/tutorials/process/debugging-app.md
Updated the Notes section for Native Attach-Debugging in Tizen Studio
For instance,
-  ...
For instance,
- Issue #265
For instance,
=> [Tizen Studio] Attach-Debugging Notes section update

docs/application/web/api/4.0/device_api/mobile/index.html, docs/application/web/api/4.0/device_api/tv/index.html, docs/application/web/api/4.0/device_api/tv/tizen/libteec.html, docs/application/web/api/4.0/device_api/wearable/index.html, docs/application/web/api/5.0/device_api/mobile/index.html, docs/application/web/api/5.0/device_api/tv/index.html, docs/application/web/api/5.0/device_api/wearable/index.html, docs/application/web/api/5.5/device_api/mobile/index.html, docs/application/web/api/5.5/device_api/tv/index.html, docs/application/web/api/5.5/device_api/wearable/index.html, docs/application/web/api/6.0/device_api/mobile/index.html, docs/application/web/api/6.0/device_api/tv/index.html, docs/application/web/api/6.0/device_api/wearable/index.html, docs/application/web/api/toc.xml
Libteec module was supported on TV since 4.0, but it was not present in
index file. Also html file for 4.0 TV was missing.
Reference - 4.0 ACR https://code.sec.samsung.net/jira/browse/TWDAPI-172
Please notice that whole Libteec API is deprecated since 6.5 https://github.com/Samsung/tizen-docs/pull/1419
=> [web index][4.0-5.5] Fixed index file to include Libteec module

docs/application/dotnet/guides/app-management/app-icons.md, docs/application/dotnet/guides/app-management/app-manager.md
To keep documentation consistency code snippets uses same tags.
=> [6.5][NET] Fixed code snippets in app manager and app icon.

docs/application/web/api/6.5/device_api/mobile/tizen/iotcon.html, docs/application/web/api/6.5/device_api/tv/tizen/iotcon.html, docs/application/web/api/6.5/device_api/wearable/tizen/iotcon.html
ACR: TWDAPI-279
A new exception is added to tizen.iotcon.initialize()
Signed-off-by: Pawel Wasowski <p.wasowski2@samsung.com>
- ACR: https://code.sec.samsung.net/jira/browse/TWDAPI-279
=> [Web API][Iotcon] Add NotSupportedError to initialize()

docs/platform/developing/building-all.md, docs/platform/developing/building.md, docs/platform/developing/cloning.md, docs/platform/developing/contributing.md, docs/platform/developing/creating.md, docs/platform/developing/flashing-rpi.md, docs/platform/developing/flashing.md, docs/platform/developing/installing.md, docs/platform/developing/setting-up.md, docs/platform/developing/tips.md
Since headers in these topics/files were written in title case and gerund forms, I have updated the headers as per Tizen writing style guidelines.
=> Fixing headers format issue in topics (docs/platform/developing)

docs/application/dotnet/samples/appfw/overview.md
Alarm app is now pointing the github link: https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Mobile/Xamarin.Forms/Alarms
=> Update the github repo link of C# Sample - Mobile - Alarms

docs/application/web/guides/index.md
line 81
```
docs/application/web/guides/index.md
```
enable you `to to` handle => enable you `to` handle
=> Guides/index.md : Fixed small typo

docs/application/vstools-mac/overview.md
Signed-off-by: Dongkyun Son <dongkyun.s@samsung.com>
- There are no further distribution plan for Visual Studio for Mac Extension for Tizen after Oct. 29, 2021 release (version 1.6).
=> Add deprecated note for Visual Studio for Mac Extension for Tizen

docs/application/native/guides/text-input/tts.md
Signed-off-by: Suyeon Hwang <stom.hwang@samsung.com>
Add description for `tts_prepare_sync()`
Fix some contents to fit style guide and description of dotnet
> This PR does not include description for `ttse_terminate()` because there is no guide for tts engine API.
- ACR: ACR-1685
=> [tts][ACR-1685] Add description for tts_prepare_sync()

docs/application/web/api/2.4/device_api/mobile/tizen/notification.html, docs/application/web/api/3.0/device_api/mobile/tizen/notification.html, docs/application/web/api/3.0/device_api/wearable/tizen/notification.html, docs/application/web/api/4.0/device_api/mobile/tizen/notification.html, docs/application/web/api/4.0/device_api/wearable/tizen/notification.html, docs/application/web/api/5.0/device_api/mobile/tizen/notification.html, docs/application/web/api/5.0/device_api/wearable/tizen/notification.html, docs/application/web/api/5.5/device_api/mobile/tizen/notification.html, docs/application/web/api/5.5/device_api/wearable/tizen/notification.html, docs/application/web/api/6.0/device_api/mobile/tizen/notification.html, docs/application/web/api/6.0/device_api/wearable/tizen/notification.html, docs/application/web/api/6.5/device_api/mobile/tizen/notification.html, docs/application/web/api/6.5/device_api/wearable/tizen/notification.html
Apply changes from #1622 to all versions.
- fix typing/spelling mistakes (missing articles, missing commas, etc.)
N/A
N/A
=> [Web API] Fix typing/spelling mistakes in notifications API

docs/application/toc_all.md
Signed-off-by: Dongkyun Son <dongkyun.s@samsung.com>
- `Baseline SDK` (`.NET CLI`, `Certificate Manager`, `Emulator Manager`)
- `Native CLI`
- `Native IDE`
- `Native Toolchain`
- `Web CLI`
- `Web IDE`
**Captured by `Package Manager` :**
=> Replace "Common Tools" with "Tizen SDK Tools"

docs/application/native/tutorials/details/native-removed-history.md
- activity/gesture functions are deprecated since 6.0 and removed since 7.0
=> Update removed history page for activity/gesture

docs/platform/reference/gbs/gbs.conf.md
The current GBS configuration in this document is broken!
1. URLs for Tizen snapshots are updated.
2. We don't have IVI profiles anymore.
=> [Fix] Update gbs configuration reflecting recent URLs (OBS-->QB)

docs/application/native/guides/app-management/data-control.md, docs/application/native/guides/applications/service-app.md, docs/application/tizen-studio/native-tools/manifest-text-editor.md, docs/application/tizen-studio/web-tools/config-editor.md
The auto-restart and on-boot options are not supported since Tizen 2.4.
This PR removes related guides.
=> Remove guides related to auto-restart and on-boot

docs/application/native/guides/multimedia/face-detection.md, docs/application/native/guides/multimedia/face-recognition.md, docs/application/native/guides/multimedia/image-classification.md, docs/application/native/guides/multimedia/image-recognition.md, docs/application/native/guides/multimedia/pose-detection.md
Some guides are using old APIs for decoding an image. It has been deprecated since Tizen 5.5.
So I modify the parts that use deprecated APIs.
Deprecated APIs
-  [image_util_decode_set_output_buffer](https://docs.tizen.org/application/native/api/iot-headed/5.5/group__CAPI__MEDIA__IMAGE__UTIL__ENCODE__DECODE__MODULE.html#gac5be85e5c3176c61ed0a16562f21cf3b)
- [image_util_decode_run](https://docs.tizen.org/application/native/api/iot-headed/5.5/group__CAPI__MEDIA__IMAGE__UTIL__ENCODE__DECODE__MODULE.html#gaa04997e8a94ae9c5c2d20b32fb6945cd)
=> Change some guides for decoding an image

docs/application/dotnet/guides/app-management/app-icons.md, docs/application/dotnet/guides/app-management/app-manager.md, docs/application/dotnet/guides/app-management/application-launcher.md, docs/application/dotnet/guides/app-management/application-preference.md, docs/application/dotnet/guides/app-management/cion.md, docs/application/dotnet/guides/app-management/component-manager.md, docs/application/dotnet/guides/app-management/component-port.md, docs/application/dotnet/guides/app-management/package-manager.md, docs/application/dotnet/guides/app-management/widget-control.md, docs/application/dotnet/guides/app-management/widget-viewer.md
This is the fifth PR in the process of updating the .NET applications section of Tizen Docs site.
This PR includes the fix of the following topic 
1. **Application management**.
List of files on which changes were made:
- /application/dotnet/guides/app-management/app-icons/
- /application/dotnet/guides/app-management/app-manager/
- /application/dotnet/guides/app-management/application-launcher/
- /application/dotnet/guides/app-management/application-preference/
- /application/dotnet/guides/app-management/cion/
- /application/dotnet/guides/app-management/component-manager/
- /application/dotnet/guides/app-management/component-port/
- /application/dotnet/guides/app-management/package-manager/
- /application/dotnet/guides/app-management/widget-control/
- …
=> .NET application site fix (Part - 5)

docs/application/dotnet/guides/user-interface/nui/text.md
Public APIs Copy, Cut, Paste and SelectedText in TextField or  TextEditor
According to ACR request.
We need to explain how to use public APIs Copy, Cut, Paste and SelectedText in TextField or TextEditor.
Added at the end of docs in "**docs/application/dotnet/guides/user-interface/nui/text.md**" a header.
The header is "**Use public APIs Copy, Cut, Paste and SelectedText in TextField or TextEditor**"
Explained APIs and added sequence of steps how to use them together.
For instance,
- Issue #1735
For instance,
- ACR: ACR-455
=> [NUI]  Public APIs Copy, Cut, Paste and SelectText

docs/application/dotnet/guides/location/geofences.md, docs/application/dotnet/guides/location/location.md, docs/application/dotnet/guides/location/overview.md, docs/application/dotnet/guides/machine-learning/machine-learning-inference.md, docs/application/dotnet/guides/machine-learning/machine-learning-train.md, docs/application/dotnet/guides/machine-learning/overview.md, docs/application/dotnet/guides/machine-learning/pipeline.md, docs/application/dotnet/guides/machine-learning/singleshot.md, docs/application/dotnet/guides/maps/here-credentials.md, docs/application/dotnet/guides/maps/maps.md
This is the eighth PR in updating the .NET applications section of the Tizen Docs site.
This PR includes the fix of the following topics:
Location [File count: 3]
Machine Learning [File count: 5]
Maps [File count: 2]
List of files on which changes were made:
/application/dotnet/guides/location/overview.md
/application/dotnet/guides/location/location.md
/application/dotnet/guides/location/geofences.md
/application/dotnet/guides/machine-learning/overview.md
/application/dotnet/guides/machine-learning/machine-learning-inference.md
/application/dotnet/guides/machine-learning/singleshot.md
/application/dotnet/guides/machine-learning/pipeline.md
/application/dotnet/guides/machine-learning/machine-learning-train.md
/application/dotnet/guides/maps/maps.md …
=> .NET application site fix (Part - 8)

docs/application/native/guides/security/privilege.md
- privilege_info_get_privacy_display_name() is deprecated since Tizen 7.5 hence remove docs related to it accordingly.
- ACR: https://code.sec.samsung.net/jira/browse/ACR-1737
=> [privilege-info][ACR-1737] Remove deprecated API from doc

docs/application/dotnet/guides/multimedia/camera.md, docs/application/dotnet/guides/multimedia/media-conversions.md, docs/application/dotnet/guides/multimedia/radio.md, docs/application/dotnet/guides/multimedia/screen-mirroring.md, docs/application/dotnet/guides/multimedia/webrtc.md
This is the twelfth PR in updating the .NET applications section of the Tizen Docs site.
**File count: 5**
This PR includes the fix of the following files:
/application/dotnet/guides/multimedia/media-conversions.md
/application/dotnet/guides/multimedia/screen-mirroring.md
/application/dotnet/guides/multimedia/radio.md
/application/dotnet/guides/multimedia/camera.md
/application/dotnet/guides/multimedia/webrtc.md
=> .NET application site fix (Part - 12)

docs/application/web/guides/security/privacy-related-permissions.md
Mark all Privacy Privilege Manager APIs as deprecated since Tizen 7.5
ACR: https://code.sec.samsung.net/jira/browse/ACR-1738
=> [ACR-1738] Mark all Privacy Privilege Manager APIs as deprecated

docs/application/web/api/7.5/device_api/mobile/index.html, docs/application/web/api/7.5/device_api/mobile/tizen/ppm.html, docs/application/web/api/7.5/device_api/wearable/index.html, docs/application/web/api/7.5/device_api/wearable/tizen/ppm.html
PPM module was required by mobile and wearable profiles, now it is not needed.
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-290
=> [PPM] Deprecate whole module

docs/platform/release-notes/tizen-7-0-m2.md
Fix links in Tizen 7.0 Public M2 Release Notes: `snapshots` -> `releases/milestone`.
No
No
cc @alpencolt @gbalykov
=> Fix links in Tizen 7.0 Public M2 release notes

docs/platform/porting/system.md
It seems that `/opt/user/share/crash/` contains a typo. The default path seems to be `/opt/usr/share/crash/`. This PR fixes that typo.
=> Fix default for crash manager crash reports root path

docs/application/dotnet/guides/security/privacy-related-permissions.md, docs/application/native/guides/security/privacy-related-permissions.md, docs/application/web/guides/security/privacy-related-permissions.md
Mark all Privacy Privilege Manager APIs as deprecated since Tizen 7.5
ACR: https://code.sec.samsung.net/jira/browse/ACR-1738
TWDAPI: https://code.sec.samsung.net/jira/browse/TWDAPI-290
TCSACR: https://code.sec.samsung.net/jira/browse/TCSACR-525
=> [ACR-1738/TWDAPI-290/TCSACR-525] Mark all Privacy Privilege Manager APIs as deprecated

docs/application/dotnet/guides/nlp/nlp.md
- Mark NLP APIs as deprecated since Tizen 7.5
- ACR: https://code.sec.samsung.net/jira/browse/TCSACR-528
=> Mark NLP APIs as deprecated since Tizen 7.5

docs/application/dotnet/guides/messaging/email.md, docs/application/dotnet/guides/messaging/messages.md, docs/application/dotnet/guides/messaging/overview.md, docs/application/dotnet/guides/messaging/push-server.md, docs/application/dotnet/guides/messaging/push.md
This PR includes the fix of the following files which is part of the .NET applications section of the Tizen Docs site:
File count: 5
/application/dotnet/guides/messaging/overview.md
/application/dotnet/guides/messaging/email.md
/application/dotnet/guides/messaging/messages.md
/application/dotnet/guides/messaging/push.md
/application/dotnet/guides/messaging/push-server.md
=> .NET application site fix (Part - 13)

docs/application/dotnet/get-started/api-privileges.md, docs/application/native/tutorials/details/sec-privileges.md, docs/application/web/tutorials/sec-privileges.md
Since Tizen 7.5, Privacy feature will be disabled in all profile. All Privacy Privilege Manager APIs and a privacy related privilege-info API are deprecated and security.privacy_privilege feature value is modified to false.
=> Note privacy feature off in privilege docs

docs/application/native/tutorials/details/native-removed-history.md
The Tizen Version Policy has been changed.
- *.5 will not be used anymore
- 7.5 must be changed to 8.0 for this year release
=> Change tizen platform version of this year from 7.5 to 8.0

docs/application/dotnet/guides/security/dpm.md, docs/application/dotnet/guides/security/overview.md, docs/application/dotnet/guides/security/privacy-related-permissions.md, docs/application/dotnet/guides/security/privilege.md, docs/application/dotnet/guides/security/secure-repository.md, docs/application/dotnet/guides/security/tee-client.md
This PR includes the fix of the following files which is part of the Security section under the .NET application guides section of the Tizen Docs site:
Files changed (6):
application/dotnet/guides/security/overview.md
application/dotnet/guides/security/secure-repository.md
application/dotnet/guides/security/privilege.md
application/dotnet/guides/security/privacy-related-permissions.md
application/dotnet/guides/security/tee-client.md
application/dotnet/guides/security/dpm.md
Signed-off by: safir.zawad@samsung.com
=> .NET application site fix (Part - 16)

docs/application/dotnet/guides/telephony/index.md, docs/application/dotnet/guides/telephony/phonenumber.md, docs/application/dotnet/guides/telephony/telephony.md
This PR includes the fix of the following files which is part of the System section under .NET application guides section of the Tizen Docs site:
File count: 3
- /application/dotnet/guides/telephony/index.md
- /application/dotnet/guides/telephony/telephony.md
- /application/dotnet/guides/telephony/phonenumber.md
=> .NET application site fix (Part - 18)

docs/application/dotnet/guides/uix/input-method-manager.md, docs/application/dotnet/guides/uix/input-method.md, docs/application/dotnet/guides/uix/overview.md, docs/application/dotnet/guides/uix/sticker.md
This PR includes the fix of the following files which is part of the Text input and voice section under .NET application guides section of the Tizen Docs site:
File count: 4
/application/dotnet/guides/uix/overview.md
/application/dotnet/guides/uix/input-method.md
/application/dotnet/guides/uix/input-method-manager.md
/application/dotnet/guides/uix/sticker.md
=> .NET application site fix (Part - 19)

docs/application/dotnet/guides/uix/stt.md, docs/application/dotnet/guides/uix/tts.md, docs/application/dotnet/guides/uix/voice-control-manager.md, docs/application/dotnet/guides/uix/voice-control.md
This PR includes the fix of the following files which is part of the Text input and voice section under .NET application guides section of the Tizen Docs site:
File count: 4
/application/dotnet/guides/uix/stt.md
/application/dotnet/guides/uix/tts.md
/application/dotnet/guides/uix/voice-control.md
/application/dotnet/guides/uix/voice-control-manager.md
=> .NET application site fix (Part - 20)

docs/platform/developing/installing.md
Update "Install Development Tools" page with tool version upgrade
GBS : 0.25.30 → 2.0.1
MIC : 0.28.19 → 2.0.1
And delete Linux distros which are no longer supported by Tizen Tools
=> Update Linux distro version supported by Tizen SCM Tools

docs/application/native/guides/multimedia/media-content.md
Exposure time, F-number, ISO, Model have been deprecated since tizen 8.0. 
But guide page says tizen 9.0.
Refer: [ACR-1777](https://jira.sec.samsung.net/browse/ACR-1777)
=> Modify deprecation version

docs/application/native/tutorials/details/native-removed-history.md
- Added some functions removed in 9.0 to history table.
- ACR-1825, Media-Controller (some deprecated functions)
- ACR-1826, Media-Streamer (whole functions)
=> Add newly removed functions to removed list

docs/application/web/tutorials/process/app-dev-process.md, docs/application/web/tutorials/process/coding-app.md, docs/application/web/tutorials/process/creating-app-project.md, docs/application/web/tutorials/process/run-debug-app.md, docs/application/web/tutorials/process/setting-properties.md
File count: 5
/application/web/tutorials/process/app-dev-process.md
/application/web/tutorials/process/creating-app-project.md
/application/web/tutorials/process/setting-properties.md
/application/web/tutorials/process/coding-app.md
/application/web/tutorials/process/run-debug-app.md
=> Web application site fix (Part - 03)

docs/application/web/guides/applications/overview.md, docs/application/web/guides/applications/service-app.md, docs/application/web/guides/applications/watch-app.md, docs/application/web/guides/applications/web-widget.md, docs/application/web/guides/index.md, docs/application/web/tutorials/deprecation-policy.md
File count: 6
/application/web/tutorials/deprecation-policy.md
/application/web/guides/index.md
/application/web/guides/applications/overview.md
/application/web/guides/applications/watch-app.md
/application/web/guides/applications/web-widget.md
/application/web/guides/applications/service-app.md
=> Web application site fix (Part - 05)

docs/application/web/guides/app-management/app-controls.md, docs/application/web/guides/app-management/app-group.md, docs/application/web/guides/app-management/app-icons.md, docs/application/web/guides/app-management/overview.md, docs/application/web/guides/app-management/preference.md, docs/application/web/guides/applications/addon.md
File count: 6
/application/web/guides/applications/addon.md
/application/web/guides/app-management/overview.md
/application/web/guides/app-management/app-group.md
/application/web/guides/app-management/preference.md
/application/web/guides/app-management/app-icons.md
/application/web/guides/app-management/app-controls.md
=> Web application site fix (Part - 06)

docs/application/dotnet/guides/uix/tts.md, docs/application/native/guides/text-input/tts.md
- Update TTS guide related to completed callback.
-
=> Update TTS guide related to completed callback

docs/application/web/guides/app-management/common-appcontrols.md, docs/application/web/guides/app-management/data-control.md, docs/application/web/guides/app-management/message-port.md, docs/application/web/guides/app-management/packages.md, docs/application/web/guides/app-management/widget-info.md, docs/application/web/guides/cordova/cordova.md
File count: 6
/application/web/guides/app-management/common-appcontrols.md
/application/web/guides/app-management/widget-info.md
/application/web/guides/app-management/packages.md
/application/web/guides/app-management/message-port.md
/application/web/guides/app-management/data-control.md
/application/web/guides/cordova/cordova.md
=> Web application site fix (Part - 07)

docs/application/web/guides/cordova/console.md, docs/application/web/guides/cordova/core.md, docs/application/web/guides/cordova/device.md, docs/application/web/guides/cordova/devicemotion.md, docs/application/web/guides/cordova/events.md, docs/application/web/guides/cordova/file.md
File count: 6
/application/web/guides/cordova/core.md
/application/web/guides/cordova/console.md
/application/web/guides/cordova/device.md
/application/web/guides/cordova/devicemotion.md
/application/web/guides/cordova/events.md
/application/web/guides/cordova/file.md
=> Web application site fix (Part - 08)

docs/application/web/api/8.0/device_api/mobile/index.xml, docs/application/web/api/8.0/device_api/tv/index.xml, docs/application/web/api/8.0/device_api/wearable/index.xml, docs/application/web/api/toc.xml
The goal of this PR is to add missing 8.0 reference in doc page:
=> [Web][8.0] Add 8.0 to TOC

docs/application/web/guides/multimedia/audio.md, docs/application/web/guides/multimedia/jpeg-exif.md, docs/application/web/guides/multimedia/media-controller.md, docs/application/web/guides/multimedia/metadata.md, docs/application/web/guides/multimedia/overview.md, docs/application/web/guides/multimedia/player-util.md
File count: 6
/application/web/guides/multimedia/overview.md
/application/web/guides/multimedia/jpeg-exif.md
/application/web/guides/multimedia/metadata.md
/application/web/guides/multimedia/audio.md
/application/web/guides/multimedia/player-util.md
/application/web/guides/multimedia/media-controller.md
=> Web application site fix (Part - 15)

docs/application/web/guides/connectivity/download.md, docs/application/web/guides/connectivity/nbs.md, docs/application/web/guides/connectivity/nfc.md, docs/application/web/guides/connectivity/secure-element.md, docs/application/web/guides/messaging/messages.md, docs/application/web/guides/messaging/overview.md
File count: 6
/application/web/guides/connectivity/nfc.md
/application/web/guides/connectivity/secure-element.md
/application/web/guides/connectivity/download.md
/application/web/guides/connectivity/nbs.md
/application/web/guides/messaging/overview.md
/application/web/guides/messaging/messages.md
=> Web application site fix (Part - 17)

docs/application/web/guides/messaging/push.md, docs/application/web/guides/sensors/device-sensors.md, docs/application/web/guides/sensors/ham.md, docs/application/web/guides/sensors/sensors.md, docs/application/web/guides/text-input/input-method.md, docs/application/web/guides/text-input/text-input.md
File count: 6
/application/web/guides/messaging/push.md
/application/web/guides/sensors/sensors.md
/application/web/guides/sensors/ham.md
/application/web/guides/sensors/device-sensors.md
/application/web/guides/text-input/text-input.md
/application/web/guides/text-input/input-method.md
=> Web application site fix (Part - 18)

docs/application/web/guides/device/feedback.md, docs/application/web/guides/device/web-view.md, docs/application/web/guides/error/error.md, docs/application/web/guides/security/privacy-related-permissions.md, docs/application/web/guides/security/secure-key.md, docs/application/web/guides/security/tee-client.md
File count: 6
/application/web/guides/device/web-view.md
/application/web/guides/device/feedback.md
/application/web/guides/security/secure-key.md
/application/web/guides/security/tee-client.md
/application/web/guides/security/privacy-related-permissions.md
/application/web/guides/error/error.md
=> Web application site fix (Part - 22)

docs/application/native/guides/ui/efl/mobile/component-list.md
Changed to correct object name
Updated incorrect object type to correct object type. It should help people who copy-paste the example code. 
Example code would not compile with an incorrect data type.
N/A
=> Fix code typo

docs/application/web/guides/w3c/communication/comm-guide.md, docs/application/web/guides/w3c/multimedia/getusermedia.md, docs/application/web/guides/w3c/multimedia/media-capture.md, docs/application/web/guides/w3c/multimedia/sound-policy.md, docs/application/web/guides/w3c/multimedia/video-audio.md, docs/application/web/guides/w3c/multimedia/webaudio.md
File count: 6
/application/web/guides/w3c/multimedia/getusermedia.md
/application/web/guides/w3c/multimedia/video-audio.md
/application/web/guides/w3c/multimedia/media-capture.md
/application/web/guides/w3c/multimedia/webaudio.md
/application/web/guides/w3c/multimedia/sound-policy.md
/application/web/guides/w3c/communication/comm-guide.md
=> Web application site fix (Part - 25)

docs/application/web/guides/w3c/communication/server-sent.md, docs/application/web/guides/w3c/communication/web-messaging.md, docs/application/web/guides/w3c/communication/websocket.md, docs/application/web/guides/w3c/communication/xmlhttprequest.md, docs/application/web/guides/w3c/storage/file.md, docs/application/web/guides/w3c/storage/storage-guide.md
File count: 6
/application/web/guides/w3c/communication/web-messaging.md
/application/web/guides/w3c/communication/websocket.md
/application/web/guides/w3c/communication/xmlhttprequest.md
/application/web/guides/w3c/communication/server-sent.md
/application/web/guides/w3c/storage/storage-guide.md
/application/web/guides/w3c/storage/file.md
=> Web application site fix (Part - 26)

docs/application/dotnet/index.md
It seems that the following commit changed the place of index.md file, and missed a link refering the file.
commit 90b92f054f8cd8a646298975e1fb8627e6559724
Author: Michal Szczecinski <mihashco89@gmail.com>
Date:   Fri Oct 1 10:55:52 2021 +0200
[6.5][NET] Move NUI and WCircularUI to User interface section. (#1511)
* [6.5][NET] Move NUI and WCircularUI to User interface section.
This commit moves NUI and WCircularUI to one user interface section.
User interface is common and important topic. This change makes it
easier to search for it in the documentation tree.
* [6.5][NET] User interface: Fixed menu order.
* Update docs/application/toc_all.md
Co-authored-by: sagarkedari <85727367+sagarkedari@users.noreply.github.com>
* Update docs/application/dotnet/guides/index.md
Co-authored-by: …
=> [Fix] Update a link using renamed address

docs/application/native/guides/multimedia/image-barcode.md
Obvious typo fix. The variable name should be `image_height`. It is referenced correctly in the subsequent lines.
=> Barcode Tutorial Typo Fix

docs/application/web/guides/w3c/location/geolocation.md, docs/application/web/guides/w3c/supplement/supplement-guide.md
File count: 2
/application/web/guides/w3c/location/geolocation.md
/application/web/guides/w3c/supplement/supplement-guide.md
=> Web application site fix (Part - 30) Part 1

docs/application/web/guides/w3c/supplement/camera.md, docs/application/web/guides/w3c/supplement/fullscreen.md, docs/application/web/guides/w3c/supplement/webgl.md
File count: 3
/application/web/guides/w3c/supplement/webgl.md
/application/web/guides/w3c/supplement/fullscreen.md
/application/web/guides/w3c/supplement/camera.md
=> Web application site fix (Part - 32)

docs/platform/developing/flashing.md, docs/platform/porting/kernel.md
TM1 was deprecated since Tizen8.0.
Its guidance is not valid. To provide a correct guidance, Update the flashing.md and kernel.md.
- Add U-boot build guidance
- Update a kernel build guidance from TM1 to RPi4
- Remove unlinked URL (wiki.tizen.orkg was shut-down.)
=> Update kernel.md and flashing.md

docs/platform/developing/flashing-rpi.md, docs/platform/porting/kernel.md
The `# Title` was broken because of the non-printing characters.
This commit is removing the characters.
=> Remove non-printing characters M-oM-;M-?

docs/application/native/guides/error/error-handling.md, docs/application/native/guides/error/overview.md, docs/application/web/guides/tau/accessibility.md, docs/application/web/guides/tau/circle-progressbar.md, docs/application/web/guides/tau/circular-ui.md, docs/application/web/guides/tau/creating-animation.md, docs/application/web/guides/tau/download-tau.md, docs/application/web/guides/tau/footerbutton.md, docs/application/web/guides/tau/globalization.md, docs/application/web/guides/tau/header.md, docs/application/web/guides/tau/helloworld.md, docs/application/web/guides/tau/helper.md, docs/application/web/guides/tau/indexscrollbar.md, docs/application/web/guides/tau/list.md, docs/application/web/guides/tau/managing-page.md, docs/application/web/guides/tau/moreoptions.md, docs/application/web/guides/tau/notepad.md, docs/application/web/guides/tau/popup.md, docs/application/web/guides/tau/processing.md, docs/application/web/guides/tau/tau-porting.md, docs/application/web/guides/tau/tau-rotary.md, docs/application/web/guides/tau/tau.md, docs/application/web/guides/tau/thumbnail.md, docs/application/web/guides/tau/ui-component.md
Added links to API Reference for guide search feature
=> Add links to API Reference for Common Error / TAU module

docs/application/dotnet/guides/uix/stt.md, docs/application/dotnet/guides/uix/tts.md, docs/application/dotnet/guides/uix/voice-control-manager.md, docs/application/dotnet/guides/uix/voice-control.md, docs/application/native/guides/text-input/stt.md, docs/application/native/guides/text-input/tts-engine.md, docs/application/native/guides/text-input/tts.md, docs/application/native/guides/text-input/voice-control-engine.md, docs/application/native/guides/text-input/voice-control-manager.md, docs/application/native/guides/text-input/voice-control.md
- Add links pointing API references
=> [TTS/STT/VC] Add links pointing API references

docs/application/toc_vs-ext_dotnet.md, docs/application/toc_vs-ext_native.md, docs/application/toc_vs-ext_web.md, docs/application/toc_vscode_dotnet.md, docs/application/toc_vscode_native.md, docs/application/toc_vscode_web.md
Raise the depth of SDK tool index to a higher level.
Expose the SDK tool index menu at the same level as menus like Overview and Release Notes.
=> Raise the depth of SDK tool index to a higher level

docs/application/web/api/10.0/device_api/mobile/index.xml, docs/application/web/api/10.0/device_api/wearable/index.xml
While preparing index files update for 9.0 version, deprecate version was corrupted - probably with replace-all function.
This change restores original deprecate version == 8.0 for messaging and ppm.
This is the same change as
https://github.com/Samsung/tizen-docs/pull/2142 but for 10.0 API docs structure.
=> [Webapi] [10.0] Fixed invalid deprecation version in index.xml file

docs/application/toc_vscode_web.md
Fix a wrong link address in VS code's web content index. 
(Here, dotnet is a typo. We need a page for creating a Web project.)
=> Fix a wrong link address in VS code's web content index

docs/application/web/api/8.0/device_api/mobile/index.html, docs/application/web/api/9.0/device_api/mobile/index.html
"Deprecated API" table was duplicated in index.html file. This PR fixes this issue and integrates content of both "Deprecated API" tables.
=> Fixed index.html file by removing duplicated deprecated API table

docs/application/dotnet/guides/data/data-storages.md, docs/application/native/guides/data/data-storages.md
The explanation for 'total size' and 'available size' is written incorrectly and needs to be corrected
Update data-storages.md to correct the wrong explanation.
For instance,
-  ...
None
None
=> Update docs/guides/data/data-storages.md to fix incorrect explannation
